dpc-sdp/ripple-framework

- README.md
> Ripple 2.0

- packages/ripple-ui-core/src/components/page-action/page-action.stories.mdx
- packages/ripple-ui-core/src/styles/components/_document.css
**Issue**: https://digital-vic.atlassian.net/browse/R20-312
- Inline title
- Move component
> [R20-312] Page action feedback

- .storybook/preview.js
- .storybook/storybook.css
- .storybook/utils/withBackground.js
- packages/ripple-ui-core/src/components/card/avatar-card.stories.mdx
- packages/ripple-ui-core/src/components/card/call-to-action.stories.mdx
- packages/ripple-ui-core/src/components/card/category-grid-card.stories.mdx
- packages/ripple-ui-core/src/components/card/key-dates-card.stories.mdx
- packages/ripple-ui-core/src/components/card/nav-card.stories.mdx
- packages/ripple-ui-core/src/components/card/promo-card.stories.mdx
- packages/ripple-ui-core/src/components/chip/chip.stories.mdx
- packages/ripple-ui-core/src/components/search-bar/constants.ts
- packages/ripple-ui-core/src/components/search-bar/search-bar.css
- packages/ripple-ui-core/src/components/search-bar/search-bar.stories.mdx
- packages/ripple-ui-core/src/components/search-bar/search-bar.vue
- packages/ripple-ui-core/src/components/stats-grid/stats-grid.stories.mdx
R20-44
**Issue**:
- Added the search bar component
- 
- 
-
> [R20-44] Search bar component

- .storybook/themes.json
- packages/ripple-ui-core/src/components/search-bar/search-bar.css
- packages/ripple-ui-core/src/styles/_vars.css
- packages/ripple-ui-core/tokens/settings/color.yaml
- packages/ripple-ui-core/tokens/settings/theme.yaml
https://digital-vic.atlassian.net/browse/R20-318
**Issue**:
- 
- 
- 
-
> feat(@dpc-sdp/ripple-ui-core): added new alpha token for search bar

- __tests__/setup.js
- jest.config.js
**Issue**:
- Suppress warnings for console methods by mocking them (discovered while I was looking at jest coverage)
- 
- 
-
> Mock console in jest

- packages/ripple-ui-core/src/components/header/header-actions.css
- packages/ripple-ui-core/src/components/header/header-actions.vue
- packages/ripple-ui-core/src/components/header/header-graphic.vue
- packages/ripple-ui-core/src/components/header/header-links.css
- packages/ripple-ui-core/src/components/header/header-links.vue
- packages/ripple-ui-core/src/components/header/header.css
- packages/ripple-ui-core/src/components/header/hero-header.stories.mdx
- packages/ripple-ui-core/src/components/header/hero-header.vue
- packages/ripple-ui-core/src/components/image/constants.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-90
- Font sizing changes, i.e. a couple more sections within the header switch tokens on a large screens. I've added a local utility for this, if it becomes more widely used we may want a global utility.
> [R20-90]: more fixed sizing for large screens

- patches/@outlinestudio+designtokenscss+1.0.6.patch
-  Patch @outlinestudio/designtokenscss so we can use commas in tokens e.g. linear gradients
- See Storybook -> Header -> Hero/Pattern, then change the theme, the gradients used in the corner patterns should now work
> fix(@dpc-sdp/ripple-ui-core): patch @outlinestudio/designtokenscss

- packages/ripple-ui-core/src/components/vertical-nav/vertical-nav.css
…me as links
**Issue**: https://digital-vic.atlassian.net/browse/R20-278
- Make buttons the same style i.e. line height and letter spacing as other links
- See storybook -> Vertical Nav
> [R20-278] update vertical nav buttons

- packages/ripple-ui-core/src/styles/utilities/_focus.css
**Issue**: https://digital-vic.atlassian.net/browse/R20-310
- Minor focus state feedback items
> [R20-310] update focus state and firefox fix

- packages/ripple-ui-core/src/components/campaign-banner/campaign-banner.css
- Replace 100vw usage to prevent horizontal scroll appearing on windows
> fix(@dpc-sdp/ripple-ui-core): :bug: fix horizontal scroll appearing on windows

- packages/ripple-ui-core/src/components/alert/alert.css
- packages/ripple-ui-core/src/components/alert/alert.stories.mdx
- packages/ripple-ui-core/src/components/alert/alert.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-309
Note: there's a hand full of unapproved UI tests relating to typography changes, can whomever worked on that check/approve those changes. Cheers
- Design feedback
- See Storybook
> [R20-309] design feedback

- packages/ripple-tide-grant/component.mapping.ts
- packages/ripple-tide-landing-page/src/component.mapping.ts
- Change accordion mapping ids to strings
- Add ids mapping for accordion items
> fix(@dpc-sdp/ripple-ui-core): :bug: change accordion mapping ids to strings

- .circleci/config.yml
- examples/nuxt-app/nuxt.config.ts
- examples/nuxt-app/package.json
- examples/nuxt-app/test/features/grant/grant.feature
- examples/nuxt-app/test/features/grant/grant.ts
- examples/nuxt-app/test/features/landingpage/home.feature
- examples/nuxt-app/test/features/site/theme.feature
- examples/nuxt-app/test/fixtures/landingpage/home.json
- examples/nuxt-app/test/mockttp.ts
- examples/nuxt-app/test/support/step_definitions/landingpage/components.ts
**Issue**:
- Fix API_URL not being set in runtimeConfig correctly - https://v3.nuxtjs.org/guide/going-further/runtime-config/
- Cleanup existing tests 
- 
- 
-
> test: :white_check_mark: fix API_URL not being set in tests

- packages/ripple-tide-api/src/nuxt/components/Page.vue
- packages/ripple-ui-core/src/components/footer/footer.vue
- packages/ripple-ui-core/src/components/footer/nav-section.vue
> fix(@dpc-sdp/ripple-ui-core): fixed hydration mismatch issue in footer

- .circleci/config.yml
> build: fix CI step not attaching workspace

- examples/nuxt-app/app.config.ts
- packages/ripple-tide-api/src/services/lib/site-menu.ts
- packages/ripple-ui-core/src/components/primary-nav/constants.ts
- packages/ripple-ui-core/src/components/primary-nav/nav-bar.vue
**Issue**:
- Footer and site section nav stopped working after hooking up the primary nav and the menu mapping was changed to use 'href'
- I changed the mapping back to 'url' and updated primary nav to use 'url' to match other components
- Example site
-
> Fixed footer and site section nav

- packages/ripple-tide-api/src/nuxt/components/sidebar/TideSidebarSocialShare.vue
- packages/ripple-ui-core/package.json
- packages/ripple-ui-core/src/components/social-share/constants.ts
- packages/ripple-ui-core/src/components/social-share/social-share-link.vue
- packages/ripple-ui-core/src/components/social-share/social-share.css
- packages/ripple-ui-core/src/components/social-share/social-share.stories.mdx
- packages/ripple-ui-core/src/components/social-share/social-share.vue
- packages/ripple-ui-core/src/composables/usePopupWindow.ts
- yarn.lock
- Replaced social share dependency with local subcomponent `RplSocialShareLink`
- Now defines url based on page rather than via prop
- Added composable for spawning a popup window, haven't exported this one for external use yet
- Updated `ripple-tide-api` for default sidebar
- Works in nuxt-app 😍 
- 
-
> Refactor social share

- _templates/content-type/new/nuxt.ts.t
- examples/nuxt-app/nuxt.config.ts
- examples/nuxt-app/package.json
- examples/nuxt-app/test/features/media/media.ts
- examples/nuxt-app/test/features/news/news.feature
- examples/nuxt-app/test/features/news/news.ts
- examples/nuxt-app/test/fixtures/news/sample-news.json
- packages/ripple-tide-api/src/utils/mapping-utils.ts
- packages/ripple-tide-news/package.json
- packages/ripple-tide-news/src/components/tide-news-body.vue
- packages/ripple-tide-news/src/components/tide-news-header.vue
- packages/ripple-tide-news/src/index.ts
- packages/ripple-tide-news/src/index.vue
- packages/ripple-tide-news/src/news.stories.mdx
- packages/ripple-tide-news/src/nuxt.ts
- packages/ripple-tide-news/src/types.ts
- packages/ripple-tide-news/tsconfig.json
- packages/ripple-ui-core/src/components/image/image.css
**Issue**: https://digital-vic.atlassian.net/browse/R20-142
- Added news template
- See storybook/reference site
> [R20-142] adding news template

- packages/ripple-ui-core/src/components/page-links/page-links.stories.mdx
- packages/ripple-ui-core/src/components/pagination/constants.ts
- packages/ripple-ui-core/src/components/pagination/pagination-link.vue
- packages/ripple-ui-core/src/components/pagination/pagination.css
- packages/ripple-ui-core/src/components/pagination/pagination.stories.mdx
- packages/ripple-ui-core/src/components/pagination/pagination.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-364
- Added new simple pagination varaint
- See storybook https://624ac117357335003a84dac3-tmemxddhjk.chromatic.com/?path=/story/core-navigation-pagination--simple-tally
> [R20-364]: adding new pagination variant

- packages/ripple-ui-core/src/components/pagination/pagination-link.vue
- packages/ripple-ui-core/src/components/pagination/pagination.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-364
- Use xs icons on simple variant
> [R20-364] update icon size for 'simple' variant

- packages/ripple-tide-publication-page/package.json
> build: :green_heart: export nuxt in publication-page

- .circleci/config.yml
> ci: fix curl command in ci

- packages/ripple-tide-api/src/mapping/sidebar-related-links/__test__/sidebar-related-links-mapping.test.ts
- packages/ripple-tide-api/src/mapping/sidebar-related-links/sidebar-related-links-mapping-types.ts
- packages/ripple-tide-api/src/mapping/sidebar-related-links/sidebar-related-links-mapping.ts
- packages/ripple-tide-api/src/mapping/sidebar-whats-next/__test__/rawdata.ts
- packages/ripple-tide-api/src/mapping/sidebar-whats-next/__test__/sidebar-whats-next-mapping.test.ts
- packages/ripple-tide-api/src/mapping/sidebar-whats-next/sidebar-whats-next-mapping.ts
- packages/ripple-tide-api/src/mapping/tide-page-base-mapping.ts
- packages/ripple-tide-api/src/nuxt/components/ContentPage.vue
- packages/ripple-tide-api/src/nuxt/components/sidebar/TideSidebarRelatedLinks.vue
- packages/ripple-tide-api/types.d.ts
- packages/ripple-tide-landing-page/src/index.ts
- packages/ripple-ui-forms/src/formkit-features.ts
> [R20-362] Sidebar - What's next

- packages/ripple-ui-core/src/components/header/header-graphic.css
- packages/ripple-ui-core/src/components/header/header-links.css
- Just adding missed breakpoint imports
> feat(@dpc-sdp/ripple-ui-core): adding missed breakpoints import

- packages/ripple-tide-event/src/index.ts
- Added transformation for event details taxonomy (original implementation was just mirroring API response since there was no test data)
*Before*
*After*
> refactor(@dpc-sdp/ripple-tide-event): :recycle: transform event details taxonomy

- packages/ripple-ui-core/src/components/vertical-nav/vertical-nav.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-278
- Fix aria-labelledby pointing to an id using an loop index rather than the item id
- Storybook
> [R20-278] - Vertical nav feedback

- packages/ripple-ui-forms/src/components/RplFormAlert/RplFormAlert.vue
> fix(@dpc-sdp/ripple-ui-forms): tidied up form alert styling

- packages/ripple-ui-core/src/components/acknowledgement/acknowledgement.css
- Added CSS parent selector to enforce height on acknowledgement flags
> Fix flag height

- packages/ripple-ui-forms/src/components/RplFormCounter/RplFormCounter.vue
- packages/ripple-ui-forms/src/components/RplFormInput/RplFormInput.vue
- packages/ripple-ui-forms/src/components/RplFormTextarea/RplFormTextarea.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-74
- Slight copy update
> feat(@dpc-sdp/ripple-ui-core): remaining copy update

- packages/ripple-ui-core/src/components/card-carousel/card-carousel.stories.mdx
- packages/ripple-ui-core/src/components/error-message/error-message.stories.mdx
- packages/ripple-ui-core/src/components/media-embed/media-embed.stories.mdx
- packages/ripple-ui-core/src/components/media-gallery/media-gallery.stories.mdx
> chore(@dpc-sdp/ripple-ui-core): move stories out of WIP

- packages/ripple-ui-forms/src/components/RplFormAlert/RplFormAlert.css
> fix(@dpc-sdp/ripple-ui-forms): added missing breakpoint import

- .storybook/storybook.css
- packages/ripple-ui-core/src/components/card/avatar-card.vue
- packages/ripple-ui-core/src/components/card/call-to-action.vue
- packages/ripple-ui-core/src/components/card/card.css
- packages/ripple-ui-core/src/components/card/card.vue
- packages/ripple-ui-core/src/components/card/category-grid-card.vue
- packages/ripple-ui-core/src/components/card/key-dates-card.vue
- packages/ripple-ui-core/src/components/card/nav-card.vue
- packages/ripple-ui-core/src/components/card/promo-card.vue
- packages/ripple-ui-core/src/components/result-listing/result-listing.css
- packages/ripple-ui-core/src/components/result-listing/result-listing.stories.mdx
- packages/ripple-ui-core/src/components/result-listing/result-listing.vue
- packages/ripple-ui-core/src/components/text-link/text-link.vue
- packages/ripple-ui-core/src/composables/useAccessibleContainer.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-96
- Adding result listing component
- Fixed issue with cards showing as clickable even when the card isn't linked
- Fixed issue with useAccessibleContainer where clicking the title triggered two click events/page navigations
> feat(@dpc-sdp/ripple-ui-core): adding result listing

- examples/nuxt-app/test/features/media/media.ts
- packages/ripple-tide-media/src/components/tide-media-body.vue
- packages/ripple-tide-media/src/pages/audio/tide-media-audio.vue
- packages/ripple-tide-media/src/pages/embedded-video/tide-media-embedded-video.vue
- packages/ripple-ui-core/src/index.ts
- packages/ripple-ui-core/src/web-components.ts
- Add media embed to exports
- Use the new media embed component in the media template
> [R20-301] update exports and media template

- examples/nuxt-app/test/features/grant/grant.ts
- packages/ripple-tide-grant/src/components/tide-grant-overview.vue
- packages/ripple-ui-core/src/components/list/constants.ts
- packages/ripple-ui-core/src/components/list/list-content.vue
- packages/ripple-ui-core/src/components/list/list.vue
- packages/ripple-ui-core/src/components/result-listing/result-listing.css
- packages/ripple-ui-core/src/components/result-listing/result-listing.stories.mdx
- packages/ripple-ui-core/src/components/result-listing/result-listing.vue
https://digital-vic.atlassian.net/browse/R20-96
- Move grant overview details to RplList
- Note: RplList is actually style-less
> [R20-96] use list component for grant details

- packages/ripple-ui-core/src/components/button/button.vue
- packages/ripple-ui-core/src/components/card/call-to-action.vue
- Remove phantom lines
- Remove tabindex on CTA button
- Update defineExpose() in button component to just expose the link (to match text-link)
> fix(@dpc-sdp/ripple-ui-core): remove tabindex, update button

- packages/ripple-ui-core/src/components/page-links/page-links.vue
- Noticed the page links had disappeared from storybook https://www.chromatic.com/test?appId=624ac117357335003a84dac3&id=63ae810ddfecc812dd0f6223
- Storybook -> Navigation -> Page Links
> fix(@dpc-sdp/ripple-ui-core): page links disappeared from storybook

- packages/ripple-tide-landing-page/mapping/secondary-campaign/secondary-campaign-mapping.ts
Responding to a backend change that will happen in the future https://digital-vic.atlassian.net/browse/SDPAP-6835
**Issue**:
- 
- 
- 
-
> fix(@dpc-sdp/ripple-tide-api): removed deprecated video includes

- packages/nuxt-ripple/pages/sitemap.vue
- packages/ripple-ui-core/src/components/list/list.vue
- packages/ripple-ui-core/src/components/sitemap/RplSitemap.css
- packages/ripple-ui-core/src/components/sitemap/RplSitemap.stories.mdx
- packages/ripple-ui-core/src/components/sitemap/RplSitemap.vue
**Issue**: R20-138
- Added sitemap component to ripple-ui-core
- Added sitemap page in nuxt-ripple
- Storybook
- Reference sote
> [R20-138] - Sitemap

- packages/ripple-ui-core/src/components/layout/back-to-top.css
- packages/ripple-ui-core/src/components/layout/back-to-top.vue
- packages/ripple-ui-core/src/components/layout/layout.css
- packages/ripple-ui-core/src/components/layout/layout.stories.mdx
- packages/ripple-ui-core/src/components/layout/layout.vue
- packages/ripple-ui-core/src/components/layout/skip-link.css
- packages/ripple-ui-core/src/components/layout/skip-link.vue
- packages/ripple-ui-core/stories/components/spacer.vue
**Issue**: R20 334, R20-378
- Added back to top button to layout
- Added skip links to layout
- Added a story for demoing back to top and skip links
- Reference site
- Storybook: http://localhost:6006/?path=/story/core-layout--back-to-top-and-skip-links&globals=themeVariableCss.name:Default
> [R20 334, R20-378] Back to top and skip links

- packages/nuxt-ripple/components/TideSidebarContactUs.vue
- packages/ripple-ui-core/src/components/campaign-banner/secondary-campaign.vue
**Issue**: R20-398
- Clicking on the email link went to a 404 because it linked to actual email rather than a mailto link, I switched them so that it now works as intended
- changed secondary campaign to use a h2
- 
-
> [R20-398,R20-427] Bug fixes

- packages/ripple-tide-publication/components/TidePublicationBody.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-530
- Use `formatDate` on publication body component from `@dpc-sdp/ripple-ui-core` lib util 
- Reference site
> [R20-530] Fix date display in publication

- packages/ripple-tide-publication/components/TidePublicationBody.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-518
- Set sidebar always true to set maximum number of carousel cards across to 2
- `pnpm -F nuxt-app dev`
- /demo-publication/demo-publication-chapter-2/demo-publication-chapter-2-page-3 
- Might need to re-add a carousel with 3 test cards on the above page if the DB is wiped again
> [R20-518] Card carousel display on publication

- .vscode/settings.json
- examples/nuxt-app/test/features/site/shared-elements.feature
- packages/nuxt-ripple/components/TideUpdatedDate.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-333
- Updated wording and date format on last updated (aka _Page update stamp_)
- `pnpm -F nuxt-app dev`
- /
> [R20-333] Last updated formatting

- examples/nuxt-app/test/features/landingpage/forms.feature
- examples/nuxt-app/test/features/landingpage/forms.ts
- examples/nuxt-app/test/fixtures/landingpage/full-form.json
- package.json
- packages/ripple-storybook/package.json
- packages/ripple-tide-landing-page/mapping/page-components/webforms/webform-validation.ts
- packages/ripple-ui-forms/src/components/RplForm/RplForm.stories.mdx
- packages/ripple-ui-forms/src/components/RplFormCounter/RplFormCounter.cy.ts
- packages/ripple-ui-forms/src/components/RplFormCounter/RplFormCounter.vue
- packages/ripple-ui-forms/src/components/RplFormInput/RplFormInput.vue
- packages/ripple-ui-forms/src/components/RplFormTextarea/RplFormTextarea.vue
- pnpm-lock.yaml
- Fixing the pluralization for 0/No length
- Update integration test
- Add component tests
- Remove countWords prop as it's not needed
- Update counter validation message
- Can be tested in storybook
> fix(@dpc-sdp/ripple-ui-core): counter updates

- .circleci/config.yml
> ci: rollback playwright docker version to match chrome version

- .circleci/config.yml
- examples/nuxt-app/app.config.ts
- packages/nuxt-ripple/app.config.ts
- packages/nuxt-ripple/components/TideBaseLayout.vue
- packages/nuxt-ripple/types.d.ts
- packages/ripple-tide-landing-page/components/global/TideLandingPage/CallToAction.vue
**Issue**:
- Fixes typing for feature flags and theme variables
- Fixes button theme neutral flag in CTA component
- 
- Try adding feature flag values in `examples/nuxt-app/app.config.ts`
- `buttonTheme: 'nuetral'` should set CTA card button to neutral theme
> refactor(nuxt-ripple): :technologist: fix featureflag typing

- .circleci/config.yml
> ci: bump playwright version

- packages/ripple-tide-api/src/utils/markup-transpiler/default-plugins.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-449
- Adding button content markup plugin
> [R20-449] adding button content markup plugin 

- packages/ripple-ui-core/src/components/layout/card-grid.css
- packages/ripple-ui-core/src/components/layout/card-grid.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-363
- Just updating the card grid break point (when there's a sidebar)
- And the component 'name'
> [R20-363] update card breakpoint

- packages/ripple-ui-core/src/components/button/RplButton.css
- packages/ripple-ui-core/src/styles/_vars.css
- packages/ripple-ui-core/stories/colors.stories.mdx
- packages/ripple-ui-core/tokens/settings/color.yaml
**Issue**: https://digital-vic.atlassian.net/browse/R20-342
- Remove error-alt token
> [R20-342] remove error-alt token

- packages/ripple-ui-core/src/components/header/RplHeader.css
- packages/ripple-ui-core/src/components/header/RplHeaderActions.css
- packages/ripple-ui-core/src/components/header/RplHeaderLinks.css
- packages/ripple-ui-core/src/components/header/RplIntroHeader.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-330
- Design feedback i.e. minor spacing, breakpoint and colour updates
> [R20-330] design feedback

- packages/ripple-storybook/.storybook/main.js
- packages/ripple-storybook/.storybook/preview.js
- packages/ripple-storybook/.storybook/themes.js
- packages/ripple-storybook/.storybook/utils/withTheme.js
- packages/ripple-storybook/package.json
- pnpm-lock.yaml
**Issue**:
- removed "@outlinestudio/designtokenscss" in favour of a storybook global variable https://storybook.js.org/docs/react/essentials/toolbars-and-globals
- Reasoning for the change is that `designtokenscss` doesn't properly read the theme from the URL, which is needed for the docs site examples
- 
-
> Custom storybook theme switch

- packages/ripple-ui-core/src/components/primary-nav/RplPrimaryNav.stories.mdx
Jira: https://digital-vic.atlassian.net/browse/R20-345
- Make all nav stories full screen for consistency
> [R20-345] make all nav stories fullscreen

- docs/components/app/AppLayout.vue
- docs/layouts/default.vue
> feat(docs): added theming for module section of docs site

- .circleci/config.yml
- .vscode/extensions.json
> ci: :construction_worker: limit chromatic step behind approval

- packages/ripple-ui-core/src/components/media-embed/RplMediaEmbed.vue
> fix(@dpc-sdp/ripple-ui-core): :bug: fixed typo in media embed

- .circleci/config.yml
to avoid manual approval step, chromatic check is still needed to merge into develop
**Issue**:
- 
- 
- 
-
> ci: ignore chromatic step on develop branch

- packages/ripple-tide-publication/components/global/TidePublicationPage.vue
- packages/ripple-tide-publication/server/plugins/publication.ts
> [R20-451] Fixed publication page stats grid includes and body components not displaying

- packages/ripple-ui-core/src/composables/useAnimateHeight.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-557
- Stop expandable content showing when toggled quickly
- Tested/testable in all expandable items: accordion, vertical nav, footer, media embed, tide search
> [R20-557] expandable content fix

- packages/ripple-storybook/.storybook/themes.js
> style: updated theme in storybook

- packages/ripple-tide-landing-page/mapping/components/webforms/webform-conditional-logic.test.ts
- packages/ripple-tide-landing-page/mapping/components/webforms/webform-conditional-logic.ts
- packages/ripple-tide-landing-page/mapping/components/webforms/webform-validation.ts
- packages/ripple-tide-landing-page/mapping/components/webforms/webforms-mapping.ts
- packages/ripple-ui-forms/src/components/RplForm/RplForm.css
- packages/ripple-ui-forms/src/components/RplForm/RplForm.vue
- packages/ripple-ui-forms/src/components/RplFormOptions/RplFormRadioGroup.vue
**Issue**: 
https://digital-vic.atlassian.net/browse/R20-578
https://digital-vic.atlassian.net/browse/R20-590
https://digital-vic.atlassian.net/browse/R20-662
- Add keys to each field to fix unpredictable conditional logic in formkit
- Fixed 'empty' conditional rule not accepting undefined as an empty value
- Fixed 'value' conditional rule breaking with values that have spaces
- Add URL field validation, similar to how the email field works
- Hide the default formkit error message that appears at the bottom of each form
- Fixed radio group items having non-unique ids, causing seperate radio groups to interact with eachother
- 
- 
-
> Form bug fixes

- examples/nuxt-app/test/fixtures/landingpage/home.json
- packages/ripple-tide-grant/components/TideGrantTimeline.vue
- packages/ripple-tide-grant/mapping/index.ts
- packages/ripple-tide-grant/types.ts
- packages/ripple-tide-landing-page/mapping/components/timeline/timeline-mapping.test.ts
- packages/ripple-tide-landing-page/mapping/components/timeline/timeline-mapping.ts
- packages/ripple-ui-core/src/components/campaign-banner/RplPrimaryCampaign.vue
- packages/ripple-ui-core/src/components/campaign-banner/RplSecondaryCampaign.vue
- packages/ripple-ui-core/src/components/card-carousel/constants.ts
- packages/ripple-ui-core/src/components/card/RplAvatarCard.vue
- packages/ripple-ui-core/src/components/card/RplCallToActionCard.vue
- packages/ripple-ui-core/src/components/card/RplCategoryGridCard.vue
- packages/ripple-ui-core/src/components/card/RplNavCard.vue
- packages/ripple-ui-core/src/components/card/RplPromoCard.vue
- packages/ripple-ui-core/src/components/content/RplContent.stories.mdx
- packages/ripple-ui-core/src/components/document/RplDocument.vue
- packages/ripple-ui-core/src/components/header/RplHeroHeader.vue
- packages/ripple-ui-core/src/components/timeline/RplTimeline.css
- packages/ripple-ui-core/src/components/timeline/RplTimeline.stories.mdx
- packages/ripple-ui-core/src/components/timeline/RplTimeline.vue
- packages/ripple-ui-core/src/styles/utilities/_focus.css
**Issues**
https://digital-vic.atlassian.net/browse/R20-425
https://digital-vic.atlassian.net/browse/R20-395
https://digital-vic.atlassian.net/browse/R20-399
https://digital-vic.atlassian.net/browse/R20-424
- Check for timeline title on grants pages
- Add alt text support for timeline images
- Update RplImageType instances to use the new IRplImageType
- Various minor fixes for timeline display, see screenshot below
- Make sure documents can be opened via keyboard in all browsers
> [R20-425] [R20-395] [R20-399] [R20-424] grants QA feedback

- packages/ripple-ui-core/src/components/contact-us/RplContactUs.css
- packages/ripple-ui-core/src/components/text-link/RplTextLink.css
**Issue**: https://digital-vic.atlassian.net/browse/R20-740
- Make sure link text wraps, there were several places where links overflowed
> [R20-740] make sure link text wraps

- packages/ripple-tide-api/src/utils/markup-transpiler/default-plugins.ts
- packages/ripple-tide-event/mapping/index.ts
- packages/ripple-tide-grant/mapping/index.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-450
- Add alternate callout class
- Run event and grant descriptions through markup plugins
> [R20-450] callout not applied

- packages/nuxt-ripple/components/TideBaseLayout.vue
- packages/nuxt-ripple/components/TideTopicTags.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-437
- Make sure tags line up and are spaced correctly
> fix(@dpc-sdp/nuxt-ripple): fix topics and tags touching

- packages/ripple-tide-api/src/utils/markup-transpiler/default-plugins.ts
- packages/ripple-ui-core/src/components/content/fixtures/testcontent.html
**Issue**: https://digital-vic.atlassian.net/browse/R20-424
- Updated embedded documents to match grant updates
> fix(@dpc-sdp/ripple-tide-api): update doc plugin and testcontent

- packages/ripple-tide-landing-page/mapping/components/webforms/webform-validation.ts
> [R20-705] fixed word count validator not handling punctuation correctly

- packages/ripple-tide-landing-page/mapping/components/card-carousel/card-carousel-mapping.ts
- packages/ripple-ui-forms/package.json
- pnpm-lock.yaml
**Issue**: https://digital-vic.atlassian.net/browse/R20-743
- Added missing includes under landing page mapping (I had added them temporarily to publication on my branch so didn't notice)
- 
- 
-
> [R20-743] Add missing includes for card carousel

- examples/nuxt-app/test/features/landingpage/forms.feature
- packages/ripple-ui-forms/src/components/RplFormCounter/RplFormCounter.cy.ts
- packages/ripple-ui-forms/src/components/RplFormCounter/RplFormCounter.vue
> fix(@dpc-sdp/ripple-ui-forms): tidied up word counter messaging

- packages/ripple-tide-landing-page/mapping/components/webforms/webforms-mapping.ts
> fix(@dpc-sdp/ripple-ui-forms): fixed label form input not having conditional logic

- packages/ripple-tide-event/mapping/index.ts
> fix(@dpc-sdp/ripple-tide-event): fixed event page crashing when event has no location

- packages/ripple-tide-grant/components/TideGrantOverview.vue
> fix(@dpc-sdp/ripple-tide-grant): fixed audience not appearing when funding was blank

- packages/nuxt-ripple/utils/hideAlertsOnLoadScript.ts
**Issue**:
- Some of the UUIDs coming from drupal have a slightly different format
- 
- 
-
> fix(@dpc-sdp/nuxt-ripple): loosened alerts script guid regex requirements

- packages/nuxt-ripple/components/TideBaseLayout.vue
> fix(@dpc-sdp/nuxt-ripple): fixed search page crashing

- packages/ripple-ui-core/src/components/slider/RplSlider.vue
- packages/ripple-ui-core/src/composables/useAccessibleContainer.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-799
- fix accessible links non working in carousels and search results
> [R20-799] fix accessible links in carousels and search results

- docs/package.json
> fix(docs): add packageManager to doc/package.json

- packages/ripple-ui-core/src/components/primary-nav/RplPrimaryNav.css
- packages/ripple-ui-core/src/components/primary-nav/components/search-form/RplPrimaryNavSearchForm.vue
- packages/ripple-ui-core/src/components/search-bar/RplSearchBar.css
- packages/ripple-ui-core/src/components/search-bar/RplSearchBar.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-765
- Open menu/search 'fullscreen'
- Focus header search input
- Fix ios input style
> [R20-765] search qa items

- packages/ripple-tide-landing-page/mapping/components/webforms/webforms-mapping.ts
- packages/ripple-ui-forms/src/components/RplFormOptions/RplFormCheckboxGroup.vue
- packages/ripple-ui-forms/src/components/RplFormOptions/RplFormOption.vue
- packages/ripple-ui-forms/src/formkit-features.ts
- packages/ripple-ui-forms/src/inputs/checkbox.ts
- packages/ripple-ui-forms/src/inputs/input-utils.ts
> [R20-593] show required message for checkboxes with no label

- packages/ripple-ui-core/src/components/button/RplButton.css
…
**Issue**:R20-719
- 
- 
- 
-
> [R20-719] updated button busy state after design feedback

- packages/ripple-ui-core/src/components/button/RplButton.css
> fix(@dpc-sdp/ripple-ui-core): fixed button styling in IOS 15 and below

- packages/ripple-tide-publication/server/plugins/publication.ts
> [R20-845] - Added all missing publication page includes

- .circleci/config.yml
> ci: run chromatic step on develop

- packages/ripple-ui-core/src/components/primary-nav/RplPrimaryNav.vue
- packages/ripple-ui-core/src/components/primary-nav/components/mega-menu/RplPrimaryNavMegaMenu.css
- packages/ripple-ui-core/src/components/primary-nav/components/mega-menu/RplPrimaryNavMegaMenu.vue
- packages/ripple-ui-core/src/components/primary-nav/components/mega-menu/RplPrimaryNavMegaMenuAction.vue
- packages/ripple-ui-core/src/components/primary-nav/components/mega-menu/RplPrimaryNavMegaMenuList.vue
- packages/ripple-ui-core/src/components/primary-nav/components/nav-bar/RplPrimaryNavBar.vue
- packages/ripple-ui-core/src/components/primary-nav/constants.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-348
- hide empty quick links
- align chevron
- use token for 'border' 
- remove transform for mobile
- don't close the menu when going back the 'home' view on mobile
> [R20-348] primary nav design feedback

- packages/ripple-ui-core/src/components/primary-nav/components/search-form/RplPrimaryNavSearchForm.vue
> fix(@dpc-sdp/ripple-ui-core): fixed nav search auto focus in IOS

- docs/package.json
- pnpm-lock.yaml
**Issue**:
See https://github.com/nuxt/nuxt/discussions/20266.
> fix: use latest `@nuxtlabs/github` module

- packages/ripple-tide-api/src/utils/markup-transpiler/default-plugins.ts
- packages/ripple-ui-core/src/components/button/RplButton.css
- packages/ripple-ui-core/src/components/media-embed/RplMediaEmbed.css
- packages/ripple-ui-core/src/components/media-embed/RplMediaEmbed.vue
- packages/ripple-ui-core/src/components/result-listing/RplSearchResult.css
- packages/ripple-ui-core/src/components/result-listing/RplSearchResult.vue
- packages/ripple-ui-forms/src/components/RplFormActions/RplFormActions.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-760
- Minor print style changes and additions
> [R20-760] print style feedback and additions

- packages/nuxt-ripple/components/TideBaseLayout.vue
- packages/nuxt-ripple/package.json
- pnpm-lock.yaml
**Issue**: R20-798
- Fixed ios 14 crashing because of array.at() usage in deepmerge-ts
- Switched to a more popular deepmerge library
- 
-
> [R20-798] - Fixed ios 14 crashing because of array.at() usage in deepmerge-ts

- packages/nuxt-ripple/components/TideAlerts.vue
- packages/nuxt-ripple/components/TideBaseLayout.vue
- packages/nuxt-ripple/mapping/base/index.ts
- packages/ripple-tide-api/src/services/tide-page.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-407
- Share preview and draft notice
> [R20-407] share previews

- packages/nuxt-ripple/nuxt.config.ts
**Issue**:  https://digital-vic.atlassian.net/browse/R20-534
- Set cache headers for static assets to 1 year
- 
- Check cache headers on js assets once on v2 branch
-
> perf(@dpc-sdp/nuxt-ripple): :zap: set cache age on static assets to 1 year

- packages/ripple-ui-core/src/components/acknowledgement/RplAcknowledgement.vue
> perf(@dpc-sdp/ripple-ui-core): :zap: set image dimensions on flag

- packages/ripple-ui-core/src/nuxt/runtime/plugin.ts
> fix(@dpc-sdp/nuxt-ripple): added missing import for analytics module

- docs/components/content/DocsContent.vue
- docs/layouts/home.vue
- docs/layouts/module.vue
- docs/layouts/page.vue
**Issue**:
- Docs styles were broken after changes to the way ripple components are imported
- 
- 
-
> fix(docs): fixed docs content styling issues after performance fixes

- packages/ripple-ui-core/src/components/card/RplCallToActionCard.vue
- packages/ripple-ui-core/src/components/card/RplCard.css
**Issue**: https://digital-vic.atlassian.net/browse/R20-281
- ensure inset card image doesn't get too small
- remove fixed type class from cta headings
> [R20-281] navigation and cta card feedback

- packages/ripple-ui-core/src/components/image/RplImage.stories.mdx
**Issue**:
- fixed remaining broken storybook images
- 
- 
-
> fix(@dpc-sdp/ripple-ui-core): fixed remaining broken storybook images

- packages/ripple-tide-publication/composables/use-tide-publication-children.ts
- packages/ripple-tide-publication/pages/[...slug]/print-all.vue
> fix(@dpc-sdp/ripple-tide-publication): fixed print all page crash when no publication children

- packages/ripple-tide-search/components/TideSearchPage.vue
- packages/ripple-tide-search/components/global/TideSearchResult.vue
- packages/ripple-tide-search/pages/search.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-890
- 
- 
- 
-
> fix(@dpc-sdp/ripple-tide-search): fixed search results not displaying after performance updates

- packages/ripple-tide-landing-page/components/global/TideLandingPage/Accordion.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-893
- 
- 
- 
-
> fix(@dpc-sdp/ripple-tide-landing-page): removed double accordion title

- packages/ripple-ui-core/src/components/primary-nav/components/mega-menu/RplPrimaryNavMegaMenu.css
- packages/ripple-ui-core/src/components/primary-nav/components/mega-menu/RplPrimaryNavMegaMenu.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-348
- Reduce menu padding when actions are present
> [R20-348]: reduce menu padding when actions are present

- packages/ripple-tide-search/components/TideSearchPage.vue
> [R20-810] Added empty search message

- packages/ripple-tide-publication/server/api/tide/publication-children.ts
**Issue**: [R20-861](https://digital-vic.atlassian.net/browse/R20-861)
- 
- 
- 
- 
[R20-861]: https://digital-vic.atlassian.net/browse/R20-861?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [R20-861] ensure order of print all pages

- packages/ripple-tide-event/components/TideEventOverview.vue
- packages/ripple-tide-publication/components/TidePublicationBody.vue
- packages/ripple-ui-core/src/components/description-list/RplDescriptionList.stories.mdx
- packages/ripple-ui-core/src/components/description-list/RplDescriptionList.vue
- packages/ripple-ui-core/src/components/description-list/RplDescriptionListItem.vue
- packages/ripple-ui-core/src/components/description-list/constants.ts
- packages/ripple-ui-core/src/components/profile/RplProfile.vue
**Issue**: R20-889
- Allowed description list to take items as slots to support links
- Replace custom html in event page with proper component
- 
-
> [R20-889] Fixed event details regression

- packages/ripple-tide-api/package.json
- pnpm-lock.yaml
> fix(@dpc-sdp/ripple-tide-api): fixed circular deps breaking publish step

- packages/ripple-tide-api/src/utils/normaliseImageUrl.ts
**Issue**:https://digital-vic.atlassian.net/browse/R20-889
- 
- 
- 
-
> fix(@dpc-sdp/ripple-tide-api): handled case where image url doesn't exist

- packages/ripple-ui-core/src/components/social-share/RplSocialShare.css
**Issue**: https://digital-vic.atlassian.net/browse/R20-460
- Update style as per feedback
- Unwound SASS-style name nesting, I think we talked about changing to this style instead a long time ago
- Storybook / nuxt-app / reference
-
> [R20-460] Social share style fixes from feedback

- packages/ripple-tide-api/src/utils/markup-transpiler/default-plugins.ts
- packages/ripple-ui-core/src/styles/components/_callout.css
**Issue**: [R20-448](https://digital-vic.atlassian.net/browse/R20-448)
Ripple 1
Ripple 2 (before)
Ripple 2 (after)
- 
- 
[R20-448]: https://digital-vic.atlassian.net/browse/R20-448?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(@dpc-sdp/ripple-tide-api): fixed callout markup and added neutral callouts

- packages/nuxt-ripple/components/TideSidebarContactUs.vue
- packages/ripple-ui-core/src/components/icon/RplIcon.vue
> fix(@dpc-sdp/ripple-ui-core): fixed page crash when trying to import missing icon

- packages/ripple-ui-forms/src/components/RplFormTextarea/RplFormTextarea.css
- packages/ripple-ui-forms/src/components/RplFormTextarea/RplFormTextarea.vue
**Issue**: https://digital-vic.atlassian.net/browse/SDPAP-7414
- Minor feedback items
> [SDPAP-7414]: textarea feedback

- packages/ripple-ui-core/src/components/header/RplHeader.css
- packages/ripple-ui-core/src/components/header/RplHeroHeader.vue
- packages/ripple-ui-core/src/styles/utilities/_typography.css
**Issue**: https://digital-vic.atlassian.net/browse/R20-472
- add new design token i.e. highlight class
> chore(@dpc-sdp/ripple-ui-core): add new design token

- packages/nuxt-ripple/app.vue
> chore(@dpc-sdp/nuxt-ripple): add loading indicator

- __tests__/setup.js
- packages/ripple-tide-api/src/utils/mapping-utils.ts
> fix(@dpc-sdp/ripple-tide-api): fixed old env var being used

- packages/ripple-ui-core/src/components/breadcrumbs/RplBreadcrumbs.css
**Issue**: https://digital-vic.atlassian.net/browse/R20-965
- Stop breadcrumbs extending beyond the primary nav
> fix(@dpc-sdp/ripple-ui-core): update breadcrumb max-width

- packages/ripple-tide-landing-page/mapping/components/card-carousel/card-carousel-mapping.test.ts
- packages/ripple-tide-landing-page/mapping/components/card-carousel/custom-mapping.ts
> [R20-945] - Fixed missing card carousel images

- packages/ripple-ui-core/src/components/header/RplHeroHeader.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-947
- 
- 
- 
-
> [R20-947] - Fixed header logo not showing with a background image

- packages/ripple-tide-landing-page/components/global/TideLandingPage/InPageNavigation.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-930
- 
- 
- 
-
> [R20-930] - Fixed 'On this page' nav displaying without content

- packages/ripple-ui-core/src/components/header/RplHeroHeader.vue
- packages/ripple-ui-core/src/composables/useEmptySlotCheck.ts
**Issue**:https://digital-vic.atlassian.net/browse/R20-946
- 
- 
- 
-
> [R20-946] - Fixed hero header intro text showing when empty

- packages/ripple-ui-core/src/components/vertical-nav/RplVerticalNav.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-931
- 
- 
- 
-
> [R20-931] - Ensured top level site section links are accessible

- packages/ripple-tide-publication/components/TidePublicationSidebar.vue
- packages/ripple-tide-publication/mapping/publication-page.ts
**Issue**:
- Fixed publication child page when it's not connected to a parent publication 
- 
- 
-
> fix(@dpc-sdp/ripple-tide-publication): fixed crash when no publication children

- packages/ripple-tide-landing-page/components/global/TideLandingPage/MediaGallery.vue
- packages/ripple-tide-landing-page/mapping/components/media-gallery/media-gallery-mapping.test.ts
- packages/ripple-tide-landing-page/mapping/components/media-gallery/media-gallery-mapping.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-962
- 
- 
- 
-
> fix(@dpc-sdp/ripple-tide-landing-page): removed titles from media gallery

- packages/ripple-tide-landing-page/components/global/TideLandingPage/PromoCard.vue
**Issue**:https://digital-vic.atlassian.net/browse/R20-929
- 
- 
- 
-
> [R20-929] fixed profile cards with no images displaying incorrectly

- packages/ripple-ui-core/src/components/card/RplCard.css
**Issue**: https://digital-vic.atlassian.net/browse/R20-954
- 
- 
- 
-
> fix(@dpc-sdp/ripple-ui-core): fixed card padding with no image

- packages/ripple-ui-core/src/components/primary-nav/RplPrimaryNav.vue
**Issue**: https://digital-vic.atlassian.net/browse/
- 
- 
- 
-
> [R20-942] :bug: fixed skip link covered by nav if user is yet to scroll page

- packages/ripple-tide-event/components/TideEventOverview.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-803
- Added weekday into custom date format
- Alphabetical order on details (Location, Price)
- Renamed 'Booking' label to 'Website'
- 
-
> [R20-803] Event overview reorder details, display weekday

- packages/ripple-tide-api/package.json
- packages/ripple-tide-api/src/logger/logger.ts
- pnpm-lock.yaml
**Issue**: https://digital-vic.atlassian.net/browse/R20-979
- 
- 
- 
-
> [R20-979] - connect logs to sumologic

- packages/nuxt-ripple-cli/src/commands/add/_templates/add/content-type/fixture.json.ts.t
- packages/nuxt-ripple-cli/src/commands/add/_templates/add/content-type/test.feature.t
- packages/nuxt-ripple-cli/src/commands/init/_templates/site/latest/app.config.ts.t
- packages/nuxt-ripple-cli/src/commands/init/index.ts
- packages/nuxt-ripple-cli/src/commands/mock/index.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-991
- Just some text updates
- Fix error when createTests is not passed
> [R20-991] minor tweaks

- examples/nuxt-app/test/features/landingpage/forms.feature
- examples/nuxt-app/test/fixtures/landingpage/full-form.json
- packages/ripple-test-utils/step_definitions/components/forms.ts
- packages/ripple-tide-landing-page/mapping/components/webforms/webforms-mapping.ts
- packages/ripple-ui-forms/src/components/RplForm/RplForm.stories.mdx
- packages/ripple-ui-forms/src/components/RplFormOptions/RplFormCheckboxGroup.stories.mdx
- packages/ripple-ui-forms/src/components/RplFormOptions/RplFormCheckboxGroup.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-993
- Add mapping for checkboxes
> [R20-993] webform checkboxes

- packages/nuxt-ripple-cli/src/commands/init/_templates/layer/latest/nuxt.config.ts.t
- packages/nuxt-ripple-cli/src/commands/init/_templates/layer/latest/package.json.t
- packages/nuxt-ripple-cli/src/commands/init/_templates/layer/latest/playground/env.example.t
- packages/nuxt-ripple-cli/src/commands/init/_templates/site/latest/example.env
- packages/nuxt-ripple-cli/src/commands/init/_templates/site/latest/package.json.t
- packages/nuxt-ripple-cli/src/commands/init/init.ts
> chore(@dpc-sdp/nuxt-ripple-cli): :technologist: update new layer template deps and fix paths

- packages/ripple-tide-landing-page/mapping/components/webforms/webforms-mapping.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-838
- Add #multiple option to select mapping
> [R20-838] add multiple option to selects

- examples/nuxt-app/package.json
- examples/vue-app/package.json
- packages/nuxt-ripple-cli/src/commands/init/_templates/layer/latest/package.json.t
- packages/nuxt-ripple-cli/src/commands/init/_templates/site/latest/package.json.t
- packages/ripple-tide-api/package.json
- packages/ripple-ui-core/package.json
- packages/ripple-ui-core/src/nuxt/index.ts
- packages/ripple-ui-forms/package.json
- packages/ripple-ui-forms/src/nuxt.ts
- pnpm-lock.yaml
**Issue**:
- 
- 
- Added `pathPrefix: false` to fix nuxt imports after updating
- Updated vue because nuxt required it
- Changed ripple-ui-forms to 'type: module' to match ripple-ui-core (nuxt complained about this after update)
- Changed ripple-ui-forms to use addComponentsDir to match ui-core
> feat: upgraded nuxt and vue to latest versions

- packages/ripple-ui-forms/src/components/RplFormDate/RplFormDate.vue
> fixed date input jumbling the month and day fields

- packages/ripple-tide-landing-page/mapping/components/webforms/webform-conditional-logic.test.ts
- packages/ripple-tide-landing-page/mapping/components/webforms/webform-conditional-logic.ts
- packages/ripple-ui-forms/src/components/RplForm/RplForm.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-993
- Add CL support for checkbox lists and multi selects
> [R20-993] conditional logic for arrays

- examples/nuxt-app/app.config.ts
- packages/nuxt-ripple-cli/src/commands/init/_templates/layer/latest/babel.config.json.t
- packages/nuxt-ripple-cli/src/commands/init/_templates/layer/latest/gitignore.t
- packages/nuxt-ripple-cli/src/commands/init/_templates/layer/latest/jest.config.js.t
- packages/nuxt-ripple-cli/src/commands/init/_templates/layer/latest/package.json.t
- packages/nuxt-ripple-cli/src/commands/init/_templates/layer/latest/playground/app.config.ts.t
Rolling some changes back in from https://digital-vic.atlassian.net/browse/R20-918
- Update `nuxt-ripple-cli` generator to include jest setup
- Update `nuxt-app` theme config with new boilerplate
- 
-
> Update nuxt layer init template

- packages/ripple-ui-core/src/components/button/RplButton.css
- packages/ripple-ui-core/src/components/expandable/RplExpandable.vue
- packages/ripple-ui-core/src/components/media-gallery/RplMediaGallery.vue
- packages/ripple-ui-core/src/components/media-gallery/RplMediaGalleryContent.vue
- packages/ripple-ui-core/src/components/modal/RplModal.css
- packages/ripple-ui-core/src/components/pagination/RplPagination.css
- packages/ripple-ui-core/src/components/pagination/RplPagination.vue
- packages/ripple-ui-core/src/components/slider/RplSlider.vue
- packages/ripple-ui-core/src/composables/useComputedSpeed.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-405
- several small tweaks, i.e. tokens updates etc
- add keyboard navigation for fullscreen gallery
> [R20-405] design/QA feedback

- packages/ripple-tide-search/components/TideSearchPage.vue
- packages/ripple-tide-search/composables/use-tide-search.ts
- packages/ripple-tide-search/pages/search.vue
- packages/ripple-tide-search/types.ts
- pnpm-lock.yaml
> Get site search working again with the search listing features

- packages/ripple-tide-api/src/utils/mapping-utils.ts
- packages/ripple-tide-landing-page/components/global/TideLandingPage/ContentCollection.vue
- packages/ripple-tide-landing-page/mapping/components/content-collection/content-collection-mapping.test.ts
- packages/ripple-tide-landing-page/mapping/components/content-collection/content-collection-mapping.ts
- packages/ripple-tide-landing-page/mapping/components/content-collection/test-data.js
**Issue**: https://digital-vic.atlassian.net/browse/R20-891
- fix card display in content collections
- add cta link mapping
> [R20-891] fix card display, add cta link mapping

- packages/ripple-ui-forms/src/components/RplFormActions/RplFormActions.vue
- packages/ripple-ui-forms/src/components/RplFormDropdown/RplFormDropdown.css
- packages/ripple-ui-forms/src/components/RplFormDropdown/RplFormDropdown.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-434
- Feedback
- Select option on enter
> [R20-434] Feedback

- packages/ripple-ui-forms/src/inputs/actions.ts
- Fix to allow variant to be set on actions
> fix(@dpc-sdp/ripple-ui-forms): fix RplFormActions variants

- packages/ripple-tide-landing-page/mapping/components/content-collection/content-collection-mapping.ts
- packages/ripple-tide-landing-page/mapping/components/content-collection/test-data.js
**Issue**: https://digital-vic.atlassian.net/browse/R20-357
- Add new itemsToLoad mapping
> [R20-357] add new itemsToLoad mapping

- packages/nuxt-ripple-analytics/plugins/analytics.ts
- packages/nuxt-ripple-cli/src/commands/add/_templates/add/content-type/header-component.vue.t
- packages/nuxt-ripple/components/TideBreadcrumbs.vue
- packages/nuxt-ripple/components/TideContentRating.vue
- packages/nuxt-ripple/composables/use-tide-page-meta.ts
- packages/ripple-tide-event/components/TideEventBody.vue
- packages/ripple-tide-event/components/TideEventHeader.vue
- packages/ripple-tide-event/components/TideEventOverview.vue
- packages/ripple-tide-grant/components/TideGrantHeader.vue
- packages/ripple-tide-landing-page/components/global/TideLandingPage/CardCarousel.vue
- packages/ripple-tide-landing-page/components/global/TideLandingPage/HeroHeader.vue
- packages/ripple-tide-landing-page/components/global/TideLandingPage/MediaGallery.vue
- packages/ripple-tide-landing-page/components/global/TideLandingPage/WebForm.vue
- packages/ripple-tide-news/components/TideNewsHeader.vue
- packages/ripple-tide-news/components/global/TideNews.vue
- packages/ripple-tide-publication/components/TidePublicationBody.vue
- packages/ripple-tide-publication/components/TidePublicationHeader.vue
- packages/ripple-tide-publication/components/global/TidePublication.vue
- packages/ripple-tide-publication/components/global/TidePublicationPage.vue
- packages/ripple-ui-core/src/components/description-list/RplDescriptionList.vue
- packages/ripple-ui-core/src/components/header/RplHeroHeader.vue
- packages/ripple-ui-core/src/components/media-embed/RplMediaEmbed.vue
- packages/ripple-ui-core/src/components/media-gallery/RplMediaGallery.vue
- packages/ripple-ui-core/src/components/modal/RplModal.vue
- packages/ripple-ui-core/src/nuxt/index.ts
- packages/ripple-ui-forms/src/components/RplFormOptions/RplFormOption.vue
- packages/ripple-ui-forms/src/nuxt.ts
- Fix numerous console errors like:
-- Hydration mismatch
-- Invalid prop types
-- Missing/optional props
-- Filter on null, etc
> [R20-1050] cleaning up browser console warnings

- packages/nuxt-ripple/server/api/tide/site.ts
**Issue**: N/A
- This was raising a confusing error when bad request error occured
- 
- 
-
> fix(nuxt-ripple): added missing import for BadRequestError

- packages/nuxt-ripple-cli/src/commands/add/_templates/add/content-type/header-component.vue.t
- packages/ripple-tide-event/components/TideEventHeader.vue
- packages/ripple-tide-grant/components/TideGrantHeader.vue
- packages/ripple-tide-landing-page/components/global/TideLandingPage/HeroHeader.vue
- packages/ripple-tide-news/components/TideNewsHeader.vue
- packages/ripple-tide-publication/components/TidePublicationHeader.vue
- packages/ripple-ui-core/src/components/header/RplHeroHeader.vue
> chore: remove block level elements breaking highlight in hero

- packages/ripple-ui-core/package.json
- pnpm-lock.yaml
> fix(@dpc-sdp/ripple-ui-core): move deps

- .circleci/config.yml
- examples/nuxt-app/nuxt.config.ts
- packages/nuxt-ripple-cli/src/commands/init/_templates/layer/latest/playground/nuxt.config.ts.t
- packages/nuxt-ripple-cli/src/commands/init/_templates/site/latest/nuxt.config.ts.t
- packages/ripple-tide-landing-page/nuxt.config.ts
- packages/ripple-tide-search/nuxt.config.ts
- Move search related runtime config options to ripple-tide-search
- Updated ci config to use `corepack` for installing a specific version of pnpm https://pnpm.io/continuous-integration#circleci
> [R20-1050] move search related runtime config options

- packages/nuxt-ripple-cli/src/commands/init/_templates/layer/latest/jest.config.js.t
- remove spaces to appease eslint
> [R20-1050] remove spaces to appease eslint

- docs/content/design-system/5.components/accordion.md
- docs/content/design-system/5.components/carousel.md
- docs/content/design-system/5.components/category-grid.md
- docs/content/design-system/5.components/checkbox.md
- docs/content/design-system/5.components/chip.md
- docs/content/design-system/5.components/contact-us.md
- docs/content/design-system/5.components/date-input.md
- docs/content/design-system/5.components/dropdown.md
- docs/content/design-system/5.components/form.md
- docs/content/design-system/5.components/input-field.md
- docs/content/design-system/5.components/media-embed.md
- docs/content/design-system/5.components/media-fullscreen.md
- docs/content/design-system/5.components/option-button.md
- docs/content/design-system/5.components/radio-button.md
- docs/content/design-system/5.components/social-share.md
- docs/content/design-system/5.components/table.md
- docs/content/design-system/5.components/tabs.md
- docs/content/design-system/5.components/text-area.md
- docs/content/design-system/5.components/timeline.md
- docs/content/design-system/5.components/vertical-navigation.md
> docs(docs): updated all theming guide links

- packages/nuxt-ripple/pages/[...slug].vue
> fix(nuxt-ripple): fixed console errors appearing for static assets

- package.json
- packages/ripple-storybook/package.json
- packages/ripple-ui-core/package.json
- pnpm-lock.yaml
> chore: update vite versions

- examples/nuxt-app/package.json
- package.json
- packages/nuxt-ripple-cli/package.json
- packages/ripple-storybook/.storybook/main.js
- packages/ripple-storybook/package.json
- packages/ripple-test-utils/package.json
- packages/ripple-ui-core/package.json
- pnpm-lock.yaml
> chore: updated packages after pnpm audit

- docs/content/framework/3.guides/4.creating-content-types.md
**Issue**: https://digital-vic.atlassian.net/browse/R20-1092
- Add basic content type guide
> docs: add content types guide

- packages/nuxt-ripple-analytics/README.md
- packages/nuxt-ripple/README.md
- Add additional content to readme's
> [R20-1050] readme updates

- packages/ripple-ui-core/src/components/alert/RplAlert.stories.mdx
**Issue**: https://digital-vic.atlassian.net/browse/R20-1003
- 
- 
- 
-
> docs(@dpc-sdp/ripple-ui-core): tweaked alert story display

- docs/content/design-system/1.about/3.getting-support.md
**Issue**: https://digital-vic.atlassian.net/browse/R20-1206
- 
- 
- 
-
> docs(docs): updated support link

- docs/app.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-1220
- 
- 
- 
-
> feat(docs): added google analytics scripts to docs site

- docs/content/framework/3.guides/3.brand-application.md
**Issue**: https://digital-vic.atlassian.net/browse/R20-1094
- Added documentation for using theming tokens and `app.config`
- 
- 
-
> [R20-1094] Document framework theming

- docs/content/framework/1.index.md
- docs/content/framework/2.key-concepts/1.nuxt.md
- docs/content/framework/2.key-concepts/3.API-endpoints.md
- docs/content/framework/3.guides/1.migrating.md
- docs/content/framework/3.guides/2.new-sites.md
- docs/content/framework/3.guides/3.brand-application.md
- docs/content/framework/3.guides/5.creating-new-layers.md
- docs/content/framework/3.guides/5.dynamic-components.md
- minor content tweaks and fixes
> docs: minor content tweaks

- docs/content/design-system/2.design/1.getting-started.md
- docs/content/design-system/2.design/2.our-design-principles.md
- docs/content/design-system/2.design/3.design-tokens.md
> Docs markdown migration

- docs/content/design-system/1.about/1.what-is-ripple.md
- docs/content/design-system/1.about/3.getting-support.md
- docs/content/design-system/2.design/1.getting-started.md
- docs/content/design-system/3.develop/1.getting-started.md
> docs(docs): fixed broken links in docs

- docs/app.config.ts
> docs(docs): :memo: enable framework docs

- docs/public/css/openforms.css
> [SDPSUP-5533] Add openforms.css

- packages/ripple-tide-landing-page/components/global/TideLandingPage/ContentCollection.vue
- packages/ripple-tide-landing-page/mapping/components/content-collection/content-collection-mapping.test.ts
- packages/ripple-tide-landing-page/mapping/components/content-collection/content-collection-mapping.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-1098
- add sort "override" for news content type 
- and fallback text when no results are found
> [R20-1098] add sort "override" for news

- packages/ripple-tide-event/mapping/index.ts
- Remove publication breadcrumb mapping from events package
> chore(@dpc-sdp/ripple-tide-event): remove breadcrumb mapping

- packages/nuxt-ripple-cli/README.md
- packages/nuxt-ripple-cli/src/commands/add/_templates/add/content-type/body-component.vue.t
- packages/nuxt-ripple-cli/src/commands/add/_templates/add/content-type/fixture.json.ts.t
- packages/nuxt-ripple-cli/src/commands/add/_templates/add/content-type/header-component.vue.t
- packages/nuxt-ripple-cli/src/commands/add/_templates/add/content-type/mapping.ts.t
- packages/nuxt-ripple-cli/src/commands/add/_templates/add/content-type/package.json.t
- packages/nuxt-ripple-cli/src/commands/add/_templates/add/content-type/page-component.vue.t
- packages/nuxt-ripple-cli/src/commands/add/_templates/add/content-type/server-plugin.ts.t
- packages/nuxt-ripple-cli/src/commands/add/_templates/add/content-type/test.feature.t
- packages/nuxt-ripple-cli/src/commands/add/_templates/add/content-type/types.ts.t
- packages/nuxt-ripple-cli/src/commands/add/helpers.ts
- packages/nuxt-ripple-cli/src/commands/add/index.ts
- add rplVersion to content-type
- adding support for content type names with numbers
> feat(@dpc-sdp/nuxt-ripple-cli): update content type

- examples/nuxt-app/test/features/search-listing/aggregations.feature
- examples/nuxt-app/test/features/search-listing/errors.feature
- examples/nuxt-app/test/features/search-listing/grants.feature
- examples/nuxt-app/test/features/search-listing/grid-list.feature
- examples/nuxt-app/test/features/search-listing/pagination.feature
- examples/nuxt-app/test/fixtures/search-listing/aggregations/page.json
- examples/nuxt-app/test/fixtures/search-listing/aggregations/request.json
- examples/nuxt-app/test/fixtures/search-listing/aggregations/response.json
- examples/nuxt-app/test/fixtures/search-listing/grants/page.json
- examples/nuxt-app/test/fixtures/search-listing/grants/request.json
- examples/nuxt-app/test/fixtures/search-listing/grants/response.json
- examples/nuxt-app/test/fixtures/search-listing/grid/page.json
- packages/ripple-test-utils/step_definitions/common/mocks.ts
- packages/ripple-test-utils/step_definitions/content-types/listing.ts
- packages/ripple-tide-search/components/TideSearchListingPage.vue
- packages/ripple-tide-search/components/global/TideSearchFilterDropdown.vue
- packages/ripple-tide-search/composables/useTideSearch.ts
> refactor(@dpc-sdp/ripple-tide-search): form field options derived from aggregations

- packages/ripple-ui-core/src/components/data-table/RplDataTable.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-1052
- Make data table row items computed (reactive)
> [R20-1052] make data table row items computed

- packages/ripple-ui-core/src/components/primary-nav/RplPrimaryNav.css
- packages/ripple-ui-core/src/components/primary-nav/RplPrimaryNav.vue
- packages/ripple-ui-core/src/composables/useViewportHeight.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-347
- Use "dynamic" height for menu/search
> [R20-347] use "dynamic" height for menu/search

- packages/nuxt-ripple/composables/use-tide-page.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-1276
- Add 301 redirect into page data composable (`ripple-tide-api` was correctly responding with a redirect type on the API call, but we weren't actioning it at page render)
- 
- Create a redirect in reference site
-
> [R20-1276] Implement 301 redirect

- packages/nuxt-ripple-cli/.gitignore
- packages/nuxt-ripple-cli/package.json
- packages/nuxt-ripple-cli/src/commands/init/_templates/layer/latest/.prettierrc.t
- packages/nuxt-ripple-cli/src/commands/init/_templates/layer/latest/nvmrc.t
- packages/nuxt-ripple-cli/src/commands/init/_templates/layer/latest/package.json.t
- packages/nuxt-ripple-cli/src/commands/init/_templates/layer/latest/playground/env.t
- packages/nuxt-ripple-cli/src/commands/init/_templates/site/latest/app.config.ts.t
- packages/nuxt-ripple-cli/src/commands/init/_templates/site/latest/editorconfig.t
- packages/nuxt-ripple-cli/src/commands/init/_templates/site/latest/env.t
- packages/nuxt-ripple-cli/src/commands/init/_templates/site/latest/eslint.rc.t
- packages/nuxt-ripple-cli/src/commands/init/_templates/site/latest/nuxt.config.ts.t
- packages/nuxt-ripple-cli/src/commands/init/_templates/site/latest/nvmrc.t
- packages/nuxt-ripple-cli/src/commands/init/_templates/site/latest/package.json.t
- packages/nuxt-ripple-cli/src/commands/init/_templates/site/latest/tsconfig.json.t
- packages/nuxt-ripple-cli/src/commands/init/index.ts
- packages/nuxt-ripple-cli/src/commands/init/init.ts
- pnpm-lock.yaml
**Issue**:
- Adds default ripple package versions so it doesn't have to be set via CLI option
- Adds ability to set .env value defaults for backend from CLI option
- 
- 
-
> CLI updates for site upgrade process

- packages/ripple-tide-search/components/TideSearchListingPage.vue
- packages/ripple-tide-search/components/global/TideTideSearchListing.vue
- packages/ripple-tide-search/package.json
- packages/ripple-tide-search/types.ts
- pnpm-lock.yaml
**Issue**: https://digital-vic.atlassian.net/browse/R20-1300
- Added content managed page features
- 
- 
-
> [R20-1300] Add breadcrumbs, page rating

- packages/ripple-tide-api/types.d.ts
- packages/ripple-tide-grant/mapping/index.ts
…l interfaces for ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-974
- Added a check for dependent timeline field (causing a 500 on existing grants without timelines - new grants have an empty timeline added by default)
- Also added mapping util interfaces for ts
- https://app.v2.vic-gov-au.sdp4.sdp.vic.gov.au/Multicultural-Seniors-Support-Program
-
> [R20-974] Check for timeline field in mapping

- examples/nuxt-app/app.config.ts
- examples/nuxt-app/test/features/search-listing/aggregations.feature
- examples/nuxt-app/test/features/search-listing/filters.feature
- examples/nuxt-app/test/features/search-listing/grants.feature
- examples/nuxt-app/test/features/search-listing/sort.feature
- examples/nuxt-app/test/fixtures/search-listing/filters/page.json
- examples/nuxt-app/test/fixtures/search-listing/filters/request-clear-empty.json
- examples/nuxt-app/test/fixtures/search-listing/filters/request-clear-filled.json
- examples/nuxt-app/test/fixtures/search-listing/filters/request-function-filter.json
- examples/nuxt-app/test/fixtures/search-listing/filters/request-raw.json
- examples/nuxt-app/test/fixtures/search-listing/filters/request-term-array.json
- examples/nuxt-app/test/fixtures/search-listing/filters/request-term-single.json
- examples/nuxt-app/test/fixtures/search-listing/filters/request-terms-array.json
- examples/nuxt-app/test/fixtures/search-listing/filters/request-terms-single.json
- examples/nuxt-app/test/fixtures/search-listing/filters/response.json
- examples/nuxt-app/test/fixtures/search-listing/grants/page.json
- examples/nuxt-app/test/fixtures/search-listing/sort/page.json
- examples/nuxt-app/test/fixtures/search-listing/sort/request.json
- examples/nuxt-app/test/fixtures/search-listing/sort/response.json
- packages/nuxt-ripple/app.config.ts
- packages/nuxt-ripple/composables/use-tide-site.ts
- packages/ripple-test-utils/step_definitions/content-types/listing.ts
- packages/ripple-tide-grant/app.config.ts
- packages/ripple-tide-search/components/TideSearchFilters.vue
- packages/ripple-tide-search/components/TideSearchListingPage.vue
- packages/ripple-tide-search/composables/useTideSearch.ts
…with URL
**Issue**:
- 
- 
- 
-
> Search listing - filters

- packages/ripple-tide-api/src/utils/markup-transpiler/default-plugins.ts
- packages/ripple-ui-core/src/styles/components/_iframe.css
- packages/ripple-ui-core/src/styles/global.css
**Issue**: https://digital-vic.atlassian.net/browse/R20-1273
- Adding iFrame markup plugin and styles to match R1
> [R20-1273] iframe markup plugin

- packages/ripple-ui-core/src/components/data-table/fixtures/sample.ts
- packages/ripple-ui-core/src/components/media-gallery/RplMediaGallery.cy.ts
- packages/ripple-ui-core/src/components/media-gallery/RplMediaGallery.vue
- Remove unused imports
- Add extra media gallery tests
> test(@dpc-sdp/ripple-ui-core): remove unused imports, add extra media gallery test

- packages/nuxt-ripple-cli/src/commands/init/_templates/layer/latest/package.json.t
- packages/ripple-test-utils/package.json
**Issue**:
- fix missing dist files
- 
- 
-
> Add missing dist files to test utils package

- packages/nuxt-ripple-cli/src/commands/init/_templates/site/latest/env.t
> fix(@dpc-sdp/nuxt-ripple-cli): :bug: fix baseurl and siteid vars undefined

- packages/nuxt-ripple/app.config.ts
- packages/ripple-tide-search/app.config.ts
- packages/ripple-tide-search/components/TideSearchPage.vue
- packages/ripple-tide-search/pages/search.vue
**Issue**: 
https://digital-vic.atlassian.net/browse/R20-1337
https://digital-vic.atlassian.net/browse/R20-1339
- Add global filters for current site 
- Add global filters for content types to display in results (Resolves [R20-1339])
- Add ability to set search content types via app.config
- 
- 
- 
[R20-1339]: https://digital-vic.atlassian.net/browse/R20-1339?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [R20-1337][R20-1339] Scope site search to site and content types

- packages/ripple-ui-core/src/components/primary-nav/components/quick-exit/RplPrimaryNavQuickExit.css
**Issue**: https://digital-vic.atlassian.net/browse/R20-1332
-  Fix quick exit positioning in build mode
> [R20-1332] fix quick exit positioning in build mode

- CHANGELOG.md
- lerna.json
- packages/eslint-config-ripple/package.json
- packages/nuxt-ripple-analytics/package.json
- packages/nuxt-ripple-cli/package.json
- packages/nuxt-ripple-preview/package.json
- packages/nuxt-ripple/package.json
- packages/ripple-storybook/package.json
- packages/ripple-test-utils/package.json
- packages/ripple-tide-api/package.json
- packages/ripple-tide-event/package.json
- packages/ripple-tide-grant/package.json
- packages/ripple-tide-landing-page/package.json
- packages/ripple-tide-media/package.json
- packages/ripple-tide-news/package.json
- packages/ripple-tide-publication/package.json
- packages/ripple-tide-search/package.json
- packages/ripple-tide-topic/package.json
- packages/ripple-ui-core/package.json
- packages/ripple-ui-forms/package.json
- packages/stylelint-config-ripple/package.json
> chore: release 2.1.1

- .github/workflows/publish-canary.yml
> chore: add git config in publish step

- packages/ripple-test-utils/step_definitions/common/mocks.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-926
- Use a wildcard glob for checking search engine URL instead of the env var
- 
- 
-
> [R20-926] Use wildcard for search url

- examples/nuxt-app/package.json
- packages/nuxt-ripple-cli/src/commands/init/_templates/layer/latest/package.json.t
- packages/nuxt-ripple-cli/src/commands/init/_templates/site/latest/package.json.t
- packages/ripple-test-utils/package.json
- packages/ripple-tide-api/package.json
- packages/ripple-tide-search/composables/useTideSearch.ts
- packages/ripple-ui-forms/package.json
- pnpm-lock.yaml
**Issue**: https://digital-vic.atlassian.net/browse/R20-1315
- Updated nuxt to 3.6.5 from 3.5.2
- Benefits of upgrading:
- Fixes R20-1315, flash of unstyled content on the error page
- Much faster start up time for `pnpm dev:nuxt` -  ~1min down to ~5secs
- 
-
> fix: upgrade nuxt to 3.6.5 to fix FOUC in 404 page

- packages/ripple-tide-search/components/TideSearchPage.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-1335
- 
- 
- 
-
> [R20-1335] - fix(@dpc-sdp/ripple-tide-search): fixed site search filter not clearing properly

- packages/nuxt-ripple-cli/src/commands/init/_templates/layer/latest/npmrc.t
> chore(@dpc-sdp/nuxt-ripple-cli): added github package registry to npmrc template

- packages/nuxt-ripple-cli/src/commands/init/_templates/site/latest/package.json.t
> chore: added topic package to site generator template

- examples/nuxt-app/test/features/landingpage/home.feature
- examples/nuxt-app/test/fixtures/landingpage/home.json
- packages/nuxt-ripple/components/TideDynamicComponents.vue
- packages/ripple-test-utils/step_definitions/components/category-grid.ts
- packages/ripple-tide-landing-page/components/global/TideLandingPage/CategoryGrid.vue
- packages/ripple-tide-landing-page/mapping/components/compact-cards/compact-cards-mapping.test.ts
- packages/ripple-tide-landing-page/mapping/components/compact-cards/compact-cards-mapping.ts
- packages/ripple-tide-landing-page/mapping/components/compact-cards/compact-cards.ts
**Issue**:
https://digital-vic.atlassian.net/browse/R20-1443
https://digital-vic.atlassian.net/browse/R20-1435
- Add custom spacing when page component has a title
- Fix custom urls, i.e. urls that come through as uri
> [R20-1443][R20-1435] custom heading gap, fix links

- packages/ripple-tide-search/components/TideSearchFilters.vue
- packages/ripple-tide-search/components/TideSearchPage.vue
> fix(@dpc-sdp/ripple-tide-search): fixed search filter row gap

- packages/nuxt-ripple-cli/src/commands/init/_templates/layer/latest/github/main.yml.t
**Issue**:
- Added GH Package registry auth token setup to CLI
- 
- 
-
> chore(@dpc-sdp/nuxt-ripple-cli): update github action

- packages/nuxt-ripple/components/TideBaseLayout.vue
- packages/nuxt-ripple/mapping/site/index.ts
- packages/ripple-tide-api/types.d.ts
- packages/ripple-ui-core/src/components/primary-nav/RplPrimaryNav.stories.mdx
- packages/ripple-ui-core/src/components/primary-nav/components/nav-bar/RplPrimaryNavBar.css
- packages/ripple-ui-core/src/components/primary-nav/components/nav-bar/RplPrimaryNavBar.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-1267
- Add support for new print logo cms field (used for secondary i.e, site logo)
> [R20-1267] add support for new print logo cms field

- packages/nuxt-ripple/nuxt.config.ts
otherwise it will get ignored in other sites and layers
**Issue**:
- 
- 
- 
-
> fix(@dpc-sdp/nuxt-ripple): added site url to nuxt-ripple nuxt.config

- examples/nuxt-app/test/features/search-listing/grants.feature
- packages/nuxt-ripple/plugins/app_hostname.ts
- packages/ripple-tide-search/composables/useSearchResult.ts
- packages/ripple-tide-search/pages/search.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-1340
- 
- 
- 
-
> feat(@dpc-sdp/ripple-tide-search): added domain to display for relative urls in search results

- packages/nuxt-ripple-cli/src/commands/init/_templates/layer/latest/cypress.config.mjs.t
- packages/nuxt-ripple-cli/src/commands/init/_templates/layer/latest/github/PULL_REQUEST_TEMPLATE.md.t
- packages/nuxt-ripple-cli/src/commands/init/_templates/layer/latest/package.json.t
> chore(@dpc-sdp/nuxt-ripple-cli): fixed incorrect file extension for PR template

- packages/nuxt-ripple-analytics/lib/index.ts
- packages/nuxt-ripple-analytics/lib/tracker.ts
- packages/ripple-ui-forms/src/components/RplFormInput/RplFormInput.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-1197
- prepend relative URLs with app origin for the dataLayer
- debounce input events, primarily for the number input and it's arrows
- add link to vertical nav event
> [R20-1197] 'normalize' urls and debounce input event

- packages/nuxt-ripple-cli/src/commands/init/_templates/layer/latest/gitignore.t
- packages/nuxt-ripple-cli/src/commands/init/_templates/layer/latest/jest.config.js.t
- packages/nuxt-ripple-cli/src/commands/init/_templates/layer/latest/package.json.t
- update jest config to fix unit tests in layers running nuxt 3.6+
- Add cypress to gitignore
- Update package.json scripts
> update cli templates

- packages/ripple-ui-core/src/components/primary-nav/components/quick-exit/RplPrimaryNavQuickExit.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-1465
- Use sentence case for title of Quick exit
- Note: the component title was set up as a prop, so it would be possible to content manage this if it was ever needed (would recommend against it though, it's ripe for abuse as a quasi-banner)
- 
-
> [R20-1465] Use sentence case for Quick exit

- examples/nuxt-app/test/features/site/theme.feature
- examples/nuxt-app/test/fixtures/site/disable-vic-logo.json
- packages/ripple-test-utils/step_definitions/common/site/theme.ts
- packages/ripple-tide-api/types.d.ts
- packages/ripple-ui-core/src/components/primary-nav/components/nav-bar/RplPrimaryNavBar.vue
…ary vic logo via flag
**Issue**:
- adds disablePrimaryLogo feature flag to remove primary vic.gov.au logo
- 
- Adds integration tests
-
> add ability to disable primary vic logo via flag

- packages/nuxt-ripple/components/TideContentRating.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-1275
- Use `RplTextLink` for style and focus treatment
- Need to figure out why prettier does that weird multiline block
- 
-
> [R20-1275] Use RplTextLink

- examples/nuxt-app/test/features/search-listing/events.feature
- examples/nuxt-app/test/fixtures/search-listing/events/page.json
- examples/nuxt-app/test/fixtures/search-listing/events/request.json
- examples/nuxt-app/test/fixtures/search-listing/events/response.json
- packages/ripple-test-utils/step_definitions/content-types/event.ts
- packages/ripple-tide-event/components/global/TideEventSearchResult.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-1344
- Add events search result card
> [R20-1344] add event search result card

- packages/ripple-ui-core/src/components/primary-nav/components/nav-bar/RplPrimaryNavBar.css
**Issue**:
- Removed extra padding that was causing an overflow at the top of the logo container
- 
- 
-
> Fix primary logo vertical alignment

- examples/nuxt-app/test/features/media/media.feature
- examples/nuxt-app/test/fixtures/media/36.json
- packages/ripple-test-utils/step_definitions/content-types/media.ts
**Issue**:
- Fix media test, youtube might change the URL so we don't need to check the 'exact' URL
> fix(nuxt-app): fix media test

- packages/ripple-tide-search/composables/useTideSearch.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-1359
- 
- 
- 
-
> fix(@dpc-sdp/ripple-tide-search): espace query text before adding to DSL query

- packages/ripple-tide-search/components/TideSearchFilters.vue
- packages/ripple-tide-search/composables/useTideSearch.ts
- Allow overriding column classes
- Stop array-ify all all values by default
- Don't push 'empty' values to the URL
> feat(@dpc-sdp/ripple-tide-search): column classes, array-ify, filter params

- packages/ripple-test-utils/step_definitions/common/site/theme.ts
- packages/ripple-ui-core/src/components/primary-nav/components/nav-bar/RplPrimaryNavBar.vue
> style: :rotating_light: fix linter warnings

- examples/nuxt-app/test/features/landingpage/openforms.feature
- examples/nuxt-app/test/fixtures/landingpage/openforms.json
- packages/ripple-test-utils/step_definitions/components/forms.ts
- packages/ripple-tide-landing-page/components/global/TideLandingPage/OpenForms.vue
- packages/ripple-tide-landing-page/mapping/components.ts
- packages/ripple-tide-landing-page/mapping/components/openforms/openforms-mapping.test.ts
- packages/ripple-tide-landing-page/mapping/components/openforms/openforms-mapping.ts
…pen forms
**Issue**:
- 
- 
- 
-
> Adds openforms support 

- packages/nuxt-ripple-cli/src/commands/init/_templates/layer/latest/github/publish.yml.t
- packages/nuxt-ripple-cli/src/commands/init/_templates/layer/latest/package.json.t
- packages/nuxt-ripple-cli/src/commands/init/_templates/site/latest/npmrc.t
- packages/nuxt-ripple-cli/src/commands/init/_templates/site/latest/package.json.t
> chore(@dpc-sdp/nuxt-ripple-cli): updated new layer cli with correct publish action

- packages/nuxt-ripple/plugins/social-meta.ts
- packages/ripple-tide-search/components/TideSearchPage.vue
**Issue**: [R20-1505](https://digital-vic.atlassian.net/browse/R20-1505)
- Added missing title prop in search page
- only add seo meta tags if page is defined
- 
- 
[R20-1505]: https://digital-vic.atlassian.net/browse/R20-1505?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [R20-1505] fix(nuxt-ripple): :bug: fix title undefined in search page

- packages/nuxt-ripple-analytics/lib/routeChange.ts
- packages/nuxt-ripple-analytics/plugins/analytics.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-1509
- Move measurement ids and production flag out of routeChange and before script setup
> [R20-1509] move measurement ids and production flag

- packages/ripple-tide-publication/server/api/tide/publication-index.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-1512
- fixes basic auth details not being sent to the publication menu endpoint
- 
- 
-
> fix(@dpc-sdp/ripple-tide-publication): matched page api by merging configs

- packages/nuxt-ripple/mapping/site/index.ts
- packages/nuxt-ripple/pages/sitemap.vue
- packages/ripple-ui-core/src/components/list/RplList.vue
- packages/ripple-ui-core/src/components/sitemap/RplSitemap.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-1515
- 
- 
- 
-
> feat(@dpc-sdp/nuxt-ripple): added table of contents to sitemap page

- examples/nuxt-app/test/features/landingpage/forms.feature
- packages/nuxt-ripple/components/TideContentRating.vue
- packages/ripple-tide-landing-page/mapping/components/webforms/webforms-mapping.ts
- packages/ripple-ui-forms/src/components/RplFormTextarea/RplFormTextarea.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-1426
- Remove counter from textareas
> [R20-1426] remove counter from textareas

- CHANGELOG.md
- lerna.json
- packages/eslint-config-ripple/package.json
- packages/nuxt-ripple-analytics/package.json
- packages/nuxt-ripple-cli/package.json
- packages/nuxt-ripple-preview/package.json
- packages/nuxt-ripple/package.json
- packages/ripple-storybook/package.json
- packages/ripple-test-utils/package.json
- packages/ripple-tide-api/package.json
- packages/ripple-tide-event/package.json
- packages/ripple-tide-grant/package.json
- packages/ripple-tide-landing-page/package.json
- packages/ripple-tide-media/package.json
- packages/ripple-tide-news/package.json
- packages/ripple-tide-publication/package.json
- packages/ripple-tide-search/package.json
- packages/ripple-tide-topic/package.json
- packages/ripple-ui-core/package.json
- packages/ripple-ui-forms/package.json
- packages/stylelint-config-ripple/package.json
> chore: :bookmark: release v2.2.0

- packages/nuxt-ripple/components/TideContentRating.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-1516
- conditionally render rating submit action so hitting enter on the radio button won't trigger a submit without a value
> [R20-1516] conditionally render rating submit action

- packages/nuxt-ripple-analytics/lib/routeChange.ts
- packages/nuxt-ripple-analytics/lib/tracker.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-1527
- change route `name` to `page_title` as per analytics request
> [R20-1527] change route name to page_title

- packages/ripple-ui-core/src/components/tabs/RplTabs.stories.mdx
- packages/ripple-ui-core/src/components/tabs/RplTabs.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-1168
- Added to enable work on asbestos image map migration
- 
- 
-
> [R20-1168] Add aria annotations on tabs

- packages/ripple-tide-search/composables/useTideSearch.ts
**Issue**:
- Added global filters to the aggregrations request so that you only get aggregations from the results you are searching
- 
- 
-
> fix(@dpc-sdp/ripple-tide-search): fixed global filters not being applied to aggregations query

- packages/nuxt-ripple/app.config.ts
- Adding the karenni (Kayah) font
> feat(@dpc-sdp/nuxt-ripple): add karenni font

- packages/ripple-test-utils/step_definitions/content-types/grant.ts
- packages/ripple-tide-grant/components/TideGrantMeta.vue
- packages/ripple-ui-core/src/components/result-listing/RplSearchResult.css
**Issue**: https://digital-vic.atlassian.net/browse/R20-1538
- Use description list to provide more context in grant meta
**Before and after**
> [R20-1538] use description list for grant meta

- CHANGELOG.md
- lerna.json
- packages/eslint-config-ripple/package.json
- packages/nuxt-ripple-analytics/package.json
- packages/nuxt-ripple-cli/package.json
- packages/nuxt-ripple-preview/package.json
- packages/nuxt-ripple/package.json
- packages/ripple-storybook/package.json
- packages/ripple-test-utils/package.json
- packages/ripple-tide-api/package.json
- packages/ripple-tide-event/package.json
- packages/ripple-tide-grant/package.json
- packages/ripple-tide-landing-page/package.json
- packages/ripple-tide-media/package.json
- packages/ripple-tide-news/package.json
- packages/ripple-tide-publication/package.json
- packages/ripple-tide-search/package.json
- packages/ripple-tide-topic/package.json
- packages/ripple-ui-core/package.json
- packages/ripple-ui-forms/package.json
- packages/stylelint-config-ripple/package.json
> chore: 🔖 release ripple 2.3.0

- packages/nuxt-ripple/composables/use-merge-section-tags.ts
- packages/nuxt-ripple/composables/use-tide-page.ts
- packages/nuxt-ripple/composables/use-tide-site.ts
- packages/nuxt-ripple/server/api/tide/site.ts
- packages/ripple-tide-api/src/services/tide-site.ts
> feat(@dpc-sdp/ripple-tide-api): merged site+alert cache tags with page cache tags

- CHANGELOG.md
- lerna.json
- packages/eslint-config-ripple/package.json
- packages/nuxt-ripple-analytics/package.json
- packages/nuxt-ripple-cli/package.json
- packages/nuxt-ripple-preview/package.json
- packages/nuxt-ripple/package.json
- packages/ripple-storybook/package.json
- packages/ripple-test-utils/package.json
- packages/ripple-tide-api/package.json
- packages/ripple-tide-event/package.json
- packages/ripple-tide-grant/package.json
- packages/ripple-tide-landing-page/package.json
- packages/ripple-tide-media/package.json
- packages/ripple-tide-news/package.json
- packages/ripple-tide-publication/package.json
- packages/ripple-tide-search/package.json
- packages/ripple-tide-topic/package.json
- packages/ripple-ui-core/package.json
- packages/ripple-ui-forms/package.json
- packages/stylelint-config-ripple/package.json
> chore: :bookmark: release 2.3.1

- examples/nuxt-app/test/support/step_definitions/index.ts
- packages/eslint-config-ripple/index.js
- packages/ripple-test-utils/step_definitions/components/custom-collection.ts
- packages/ripple-tide-landing-page/mapping/components/data-table/data-table-mapping.ts
- packages/ripple-tide-search/components/global/TideCustomCollection.vue
> test: :white_check_mark: fix linter issues

- packages/ripple-ui-core/src/styles/utilities/_typography.css
**Issue**: R20-1533
- Adds a CSS variable `--rpl-type-font-family-heading` to heading typography classes
- Falls back to the regular font
- 
-
> [R20-1533] Custom heading font

- packages/nuxt-ripple/composables/use-tide-page.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-1572
- Enable external redirects conditionally on redirect_type
- 
- Tested locally on v2.3.3 production env vic.gov.au, with internal and external links (https://www.vic.gov.au/grants and https://www.vic.gov.au/digitaljobs)
-
> [R20-1572] Enable external redirects

- packages/ripple-tide-publication/server/api/tide/publication-index.ts
…tion preview menu issue
**Issue**:
- Made publication menu API log error when it can not fetch the menu. For unpublished pages it should still render the page without the menu.
- 
- 
-
> [R20-1574] fix publication menu issue when unpublished

- packages/ripple-tide-publication/utils/processMenu.ts
> fix(@dpc-sdp/ripple-tide-publication): fixed duplication side nav links

- .github/workflows/studio.yml
- package.json
**Issue**:
- Update PNPM and prevent fixing version to fix docs site
- 
- 
-
> chore: :construction_worker: update pnpm

- docs/nuxt.config.ts
- docs/package.json
- pnpm-lock.yaml
> chore(docs): :heavy_plus_sign: add nuxt studio

- packages/nuxt-ripple/mapping/site/index.ts
**Issue**: https://digital-vic.atlassian.net/browse/SDPAP-8345
- Added mapping for newly added alternative footer logo control in BE
- 
- 
-
> [SDPAP-8345] Add mapping for new footer logo field

- packages/nuxt-ripple/composables/use-tide-page.ts
> [SDPAP-8409] fix redirects adding to history state

- packages/ripple-tide-landing-page/mapping/components/card-carousel/custom-mapping.ts
> [SDPSUP-5938] fix carousel links

- CHANGELOG.md
- lerna.json
- packages/eslint-config-ripple/package.json
- packages/nuxt-ripple-analytics/package.json
- packages/nuxt-ripple-cli/package.json
- packages/nuxt-ripple-preview/package.json
- packages/nuxt-ripple/package.json
- packages/ripple-storybook/package.json
- packages/ripple-test-utils/package.json
- packages/ripple-tide-api/package.json
- packages/ripple-tide-event/package.json
- packages/ripple-tide-grant/package.json
- packages/ripple-tide-landing-page/package.json
- packages/ripple-tide-media/package.json
- packages/ripple-tide-news/package.json
- packages/ripple-tide-publication/package.json
- packages/ripple-tide-search/package.json
- packages/ripple-tide-topic/package.json
- packages/ripple-ui-core/package.json
- packages/ripple-ui-forms/package.json
- packages/stylelint-config-ripple/package.json
> chore: :bookmark: release 2.4.0

- package.json
- packages/ripple-ui-forms/package.json
- pnpm-lock.yaml
> chore: updated babel / @babel/traverse

- packages/nuxt-ripple/composables/use-tide-page.ts
> [R20-1580] Ensure that redirect code runs even on (nuxt) cached pages

- CHANGELOG.md
- lerna.json
- packages/eslint-config-ripple/package.json
- packages/nuxt-ripple-analytics/package.json
- packages/nuxt-ripple-cli/package.json
- packages/nuxt-ripple-preview/package.json
- packages/nuxt-ripple/package.json
- packages/ripple-storybook/package.json
- packages/ripple-test-utils/package.json
- packages/ripple-tide-api/package.json
- packages/ripple-tide-event/package.json
- packages/ripple-tide-grant/package.json
- packages/ripple-tide-landing-page/package.json
- packages/ripple-tide-media/package.json
- packages/ripple-tide-news/package.json
- packages/ripple-tide-publication/package.json
- packages/ripple-tide-search/package.json
- packages/ripple-tide-topic/package.json
- packages/ripple-ui-core/package.json
- packages/ripple-ui-forms/package.json
- packages/stylelint-config-ripple/package.json
> chore: 🔖 release ripple 2.4.1

- CHANGELOG.md
- lerna.json
- packages/eslint-config-ripple/package.json
- packages/nuxt-ripple-analytics/package.json
- packages/nuxt-ripple-cli/package.json
- packages/nuxt-ripple-preview/package.json
- packages/nuxt-ripple/package.json
- packages/ripple-storybook/package.json
- packages/ripple-test-utils/package.json
- packages/ripple-tide-api/package.json
- packages/ripple-tide-event/package.json
- packages/ripple-tide-grant/package.json
- packages/ripple-tide-landing-page/package.json
- packages/ripple-tide-media/package.json
- packages/ripple-tide-news/package.json
- packages/ripple-tide-publication/package.json
- packages/ripple-tide-search/package.json
- packages/ripple-tide-topic/package.json
- packages/ripple-ui-core/package.json
- packages/ripple-ui-forms/package.json
- packages/stylelint-config-ripple/package.json
> chore: :bookmark: release 2.4.2

- README.md
> Update link to personal access token setup

- packages/nuxt-ripple/plugins/hide-alerts.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-1567
- Only add hide-alerts script on server render to prevent double render and redefinition error of const
-
- 
-
> [R20-1567] Supress double DISMISSED_ALERTS_COOKIE decl

- packages/ripple-tide-api/src/utils/markup-transpiler/default-plugins.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-1597
- 
- 
- 
-
> [R20-1597] Fixed embedded media sometimes not displaying correctly

- packages/ripple-tide-landing-page/components/global/TideLandingPage/WebForm.vue
> [R20-1625] Fixed content rating submissions on nested routes

- packages/ripple-ui-core/src/components/footer/RplFooter.vue
- packages/ripple-ui-core/src/components/primary-nav/RplPrimaryNav.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-800
- 
- 
- 
-
> [R20-800] Ensured landmarks (primary and footer navs) are unique by adding a label

- packages/ripple-tide-landing-page/components/global/TideLandingPage/WebForm.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-1620
- Parse form response to display upstream errors
- Solved for Ripple 1 in https://github.com/dpc-sdp/ripple/pull/1269
- 
-
> [R20-1620] Parse form response

- packages/ripple-tide-landing-page/mapping/components/card-carousel/custom-mapping.ts
for the card carousel
**Issue**: https://digital-vic.atlassian.net/browse/R20-1610
- 
- 
- 
-
> [R20-1610] - Stopped created date displaying for landing page cards

- packages/ripple-tide-event/components/global/TideEvent.vue
- packages/ripple-tide-event/mapping/index.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-1635
- 
- 
- 
-
> [R20-1635] Fixed website url using booking url

- packages/ripple-tide-landing-page/mapping/components/data-table/data-table-mapping.test.ts
- packages/ripple-tide-landing-page/mapping/components/data-table/data-table-mapping.ts
- packages/ripple-ui-core/src/components/data-table/RplDataTableRow.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-1634
- 
- 
- 
-
> [R20-1634] Allow html in data tables

- examples/nuxt-app/test/fixtures/landingpage/maps/vsba/custom-collection-config.json
- packages/ripple-tide-search/components/global/TideSearchListingResultsMap.vue
- packages/ripple-ui-core/src/components.ts
- packages/ripple-ui-maps/package.json
- packages/ripple-ui-maps/src/components/legend/RplMapLegend.css
- packages/ripple-ui-maps/src/components/legend/RplMapLegend.stories.mdx
- packages/ripple-ui-maps/src/components/legend/RplMapLegend.vue
- packages/ripple-ui-maps/src/components/legend/RplMapLegendItem.vue
- pnpm-lock.yaml
> feat(@dpc-sdp/ripple-ui-maps): added legend component

- CHANGELOG.md
- lerna.json
- packages/eslint-config-ripple/package.json
- packages/nuxt-ripple-analytics/package.json
- packages/nuxt-ripple-cli/package.json
- packages/nuxt-ripple-preview/package.json
- packages/nuxt-ripple/package.json
- packages/ripple-storybook/package.json
- packages/ripple-test-utils/package.json
- packages/ripple-tide-api/package.json
- packages/ripple-tide-event/package.json
- packages/ripple-tide-grant/package.json
- packages/ripple-tide-landing-page/package.json
- packages/ripple-tide-media/package.json
- packages/ripple-tide-news/package.json
- packages/ripple-tide-publication/package.json
- packages/ripple-tide-search/package.json
- packages/ripple-tide-topic/package.json
- packages/ripple-ui-core/package.json
- packages/ripple-ui-forms/package.json
- packages/stylelint-config-ripple/package.json
> chore: :bookmark: release 2.5.0

- .github/workflows/publish-canary.yml
> chore: remove reference site update step using circle

- examples/nuxt-app/test/features/maps/vsba.feature
- examples/nuxt-app/test/fixtures/map-table/vsba/localities.json
- packages/ripple-tide-search/components/global/TideSearchAddressLookup.vue
- packages/ripple-ui-maps/src/components/map/RplMap.vue
**Issue**: 
https://digital-vic.atlassian.net/browse/R20-1655
https://digital-vic.atlassian.net/browse/R20-1661
- 
- 
- 
-
> [R20-1655] Fixed back button behavior for maps and case sensitive suggestions

- packages/nuxt-ripple-analytics/plugins/analytics.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-1664
- Added endpoint `ripple_version` to `google_analytics`, defaults to '2.x' when app.config doesn't add package versions or when running in monorepo (i.e. 'workspace:*')
- 
- `window.dataLayer[0].google_analytics` in browser console
-
> [R20-1664] Expose ripple version in dataLayer

- packages/ripple-ui-core/src/components/search-bar/RplSearchBar.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-1672
- add name field to search bar events (i.e. input label)
> [R20-1672] add name field to search bar events

- packages/ripple-ui-core/src/components/accordion/RplAccordion.css
- packages/ripple-ui-core/src/components/contact-us/RplContactUs.css
- packages/ripple-ui-core/src/components/media-gallery/RplMediaGallery.css
- packages/ripple-ui-core/src/components/vertical-nav/RplVerticalNav.css
- packages/ripple-ui-core/src/styles/components/_embed.css
**Issue**: https://digital-vic.atlassian.net/browse/R20-910
- fix icon focus colours
> [R20-910] fix icon focus colours

- packages/ripple-ui-core/src/components/layout/RplLayoutBackToTop.css
- packages/ripple-ui-core/src/components/layout/RplLayoutBackToTop.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-581
- Fix media query
- Update back to top positioning to work when alerts are present
> fix(@dpc-sdp/ripple-ui-core): fix media query, update back to top positioning

- packages/ripple-tide-api/src/utils/markup-transpiler/default-plugins.ts
**Issue**: https://digital-vic.atlassian.net/browse/SDPAP-8741
- add check for ics files in markup transpiler
> [SDPAP-8741] add check for ics files in markup transpiler

- packages/ripple-tide-search/components/TideSearchListingPage.vue
- packages/ripple-tide-search/composables/useSearchUI.ts
- packages/ripple-tide-search/composables/useTideSearch.ts
- packages/ripple-ui-core/src/components/search-bar/RplSearchBar.css
- packages/ripple-ui-core/src/components/search-bar/RplSearchBar.stories.mdx
**Issue**: https://digital-vic.atlassian.net/browse/R20-579
- Add reversed stripping for the 'reverse' theme variant
- Normalize suggestion result size to 8 for search and search listings
- Only show suggestions when autocompleteMinimumCharacters has been met   
- Update search listing so autocomplete searches only occur when autocompleteMinimumCharacters is met, i.e. like the main search which doesn't send requests for 1 or two characters
> [R20-579] search bar feedback

- packages/nuxt-ripple/composables/use-merge-section-tags.ts
- packages/nuxt-ripple/composables/use-tide-page.ts
- packages/nuxt-ripple/composables/use-tide-site.ts
- packages/nuxt-ripple/plugins/ssr-url-params-fix.ts
**Issue**: https://digital-vic.atlassian.net/browse/SDPSUP-6216
- 
- 
- 
-
> [SDPSUP-6216] [R20-1581] prevented url params being stripped for cached pages

- CHANGELOG.md
- lerna.json
- packages/eslint-config-ripple/package.json
- packages/nuxt-ripple-analytics/package.json
- packages/nuxt-ripple-cli/package.json
- packages/nuxt-ripple-preview/package.json
- packages/nuxt-ripple/package.json
- packages/ripple-storybook/package.json
- packages/ripple-test-utils/package.json
- packages/ripple-tide-api/package.json
- packages/ripple-tide-event/package.json
- packages/ripple-tide-grant/package.json
- packages/ripple-tide-landing-page/package.json
- packages/ripple-tide-media/package.json
- packages/ripple-tide-news/package.json
- packages/ripple-tide-publication/package.json
- packages/ripple-tide-search/package.json
- packages/ripple-tide-topic/package.json
- packages/ripple-ui-core/package.json
- packages/ripple-ui-forms/package.json
- packages/ripple-ui-maps/package.json
- packages/stylelint-config-ripple/package.json
> chore: :bookmark: release v2.6.0

- packages/nuxt-ripple-analytics/plugins/analytics.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-1664
- Renamed ripple release to `release` and moved to dataLayer root
- 
- 
-
> [R20-1664] Move release to dataLayer root

- packages/ripple-tide-search/components/global/TideSearchFilterDependent.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-1701
- Lost this class at some point, apologies
> [R20-1701] add lost class to dependent filter

- packages/ripple-tide-search/components/global/TideSearchAddressLookup.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-1731
- 
- 
- 
-
> [R20-1731] Don't clear suggestions after selecting a suburb

- packages/ripple-tide-search/components/global/TideSearchAddressLookup.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-1729
- 
- 
- 
-
> [R20-1729] Improved suburb autocomplete suggestions

- examples/nuxt-app/test/features/search-listing/filters.feature
- examples/nuxt-app/test/fixtures/search-listing/filters/page.json
- examples/nuxt-app/test/fixtures/search-listing/filters/request-clear-filled.json
- examples/nuxt-app/test/fixtures/search-listing/filters/request-term-single.json
- packages/ripple-test-utils/step_definitions/content-types/listing.ts
- packages/ripple-tide-search/components/global/TideSearchFilterCheckbox.vue
- packages/ripple-ui-forms/src/components/RplFormLabel/RplFormLabel.css
**Issue**: https://digital-vic.atlassian.net/browse/R20-1703
- add checkbox support 
- update "Should update the URL when the filters are applied" to test URL updates
- minor label alignment update
> [R20-1703] add checkbox support

- packages/nuxt-ripple/composables/use-tide-page.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-1744
- wrap navigateTo with runWithContext to get redirects working again
> [R20-1744] wrap navigateTo with runWithContext

- packages/ripple-tide-search/composables/useTideSearch.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-1743
- 
- 
- 
-
> [R20-1743] Fixed search logic firing after user navigated to a new page

- packages/ripple-ui-core/src/components/search-bar/RplSearchBar.vue
> fix(@dpc-sdp/ripple-ui-core): return slug value

- CHANGELOG.md
- lerna.json
- packages/eslint-config-ripple/package.json
- packages/nuxt-ripple-analytics/package.json
- packages/nuxt-ripple-cli/package.json
- packages/nuxt-ripple-preview/package.json
- packages/nuxt-ripple/package.json
- packages/ripple-storybook/package.json
- packages/ripple-test-utils/package.json
- packages/ripple-tide-api/package.json
- packages/ripple-tide-event/package.json
- packages/ripple-tide-grant/package.json
- packages/ripple-tide-landing-page/package.json
- packages/ripple-tide-media/package.json
- packages/ripple-tide-news/package.json
- packages/ripple-tide-publication/package.json
- packages/ripple-tide-search/package.json
- packages/ripple-tide-topic/package.json
- packages/ripple-ui-core/package.json
- packages/ripple-ui-forms/package.json
- packages/ripple-ui-maps/package.json
- packages/stylelint-config-ripple/package.json
**chore: 🔖 release ripple 2.6.1**
> chore: 🔖 release ripple 2.6.1

- examples/nuxt-app/test/features/site/theme.feature
- examples/nuxt-app/test/fixtures/site/disable-vic-logo.json
- packages/ripple-test-utils/step_definitions/common/site/theme.ts
- packages/ripple-tide-api/types.d.ts
- packages/ripple-ui-core/src/components/footer/RplFooter.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-1694
- add flag for removing vic branding in footer
> [R20-1694] add flag for removing vic branding in footer

- examples/nuxt-app/components/global/TableExtraContentComponentExample.vue
- examples/nuxt-app/test/features/search-listing/table.feature
- examples/nuxt-app/test/fixtures/search-listing/table/page-extra-component.json
- examples/nuxt-app/test/fixtures/search-listing/table/page-extra-structured.json
- packages/ripple-test-utils/step_definitions/components/data-table.ts
- packages/ripple-tide-search/components/global/TideSearchResultsTable.vue
- packages/ripple-ui-core/src/components/data-table/RplDataTable.stories.mdx
- packages/ripple-ui-core/src/components/data-table/RplDataTableRow.vue
- packages/ripple-ui-core/src/components/data-table/fixtures/sample.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-1709
- add support for custom components in data table extra content
- adds support for extra content in search listings/custom collections
- add support for extra data table features in search listings, i.e. offset, header type etc
- removes some unused props like content and items
_Note: This PR doesn't alter the current data table API just extends it_
```json
{
"showExtraContent": true,
"caption": "Table with custom component for extra content",
"footer": "Some notes about the table",
"headingType": {
"horizontal": true,
"vertical": true
},
"columns": [
{ "label": "Organisation", "objectKey": "Organisation" },
{ "label": "Funded For", "objectKey": "Funded For" },
{ "label": "Funding Department", "objectKey": "Funding Department" …
```
> [R20-1709] add support for custom components in data table extra content

- packages/nuxt-ripple/mapping/utils/processSiteSocialLinks.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-1668
- Add au.linkedin.com to switch case; we could update this to work with all subdomains but given this is only for the sites contact us footer, the link would only be for au or nothing.
> [R20-1668] add icon support for au.linkedin.com

- examples/nuxt-app/test/features/maps/vsba.feature
> test: :white_check_mark: increase timeout

- packages/ripple-ui-core/src/components/search-bar/RplSearchBar.css
**Issue**: https://digital-vic.atlassian.net/browse/R20-579
- add suggestion active state
> [R20-579] add suggestion active state

- packages/ripple-ui-core/src/components/header/RplHeader.css
- packages/ripple-ui-core/src/components/header/RplHeader.vue
- packages/ripple-ui-core/src/components/header/RplHeaderActions.vue
- packages/ripple-ui-core/src/components/header/RplHeroHeader.stories.mdx
- packages/ripple-ui-core/src/components/header/RplHeroHeader.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-1759
- Previously if you had a background image and CTAs then the CTAs just wouldn't display, now if you have a background image and CTAs we display the CTAs as below.
- This new behavior means the demo content may need to be updated for the reference site. REF: https://digital-vic.atlassian.net/browse/R20-1759?focusedCommentId=323346
> [R20-1759] add background CTA 'variant'

- packages/ripple-ui-core/src/components/result-listing/RplResultListing.stories.mdx
**Issue**: https://digital-vic.atlassian.net/browse/R20-462
- update result story 'highlight' tag
> [R20-462] update result story 'highlight' tag

- packages/ripple-ui-core/src/components/search-bar/RplSearchBar.css
**Issue**: https://digital-vic.atlassian.net/browse/R20-328
- Menu variant input font sizing change
- Padding updates for input
- Remove angled border on input
> [R20-328] searchbar feedback

- packages/ripple-ui-maps/src/components/map/RplMap.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-1745
- 
- 
- 
-
> [R20-1745] Added title attribute when hovering over map pins

- packages/ripple-tide-search/components/global/TideCustomCollection.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-1733
- 
- 
- 
-
> [R20-1733] Hide sort options dropdown if there is only one option

- examples/nuxt-app/test/fixtures/landingpage/custom-collection/alt-form-theme-default.json
- examples/nuxt-app/test/fixtures/landingpage/custom-collection/alt-form-theme-reverse.json
- examples/nuxt-app/test/fixtures/landingpage/custom-collection/form-theme-default.json
- examples/nuxt-app/test/fixtures/landingpage/custom-collection/form-theme-reverse.json
- examples/nuxt-app/test/fixtures/search-listing/dependent-filters/page.json
- examples/nuxt-app/test/fixtures/search-listing/dependent-filters/request-empty.json
- packages/ripple-tide-search/components/global/TideSearchFilterDependent.vue
- packages/ripple-tide-search/composables/useTideSearch.ts
- Fix issue with elastic search filters, the mapping was returning null 
- Make spelling consistent, the original comment and the added props used different spelling
> Fix issue with elastic search filters

- packages/ripple-ui-core/src/components/header/RplHeader.css
**Issue**: https://digital-vic.atlassian.net/browse/R20-1790
- add new tokens
> [R20-1790] header cta with image updates

- packages/ripple-tide-search/components/global/TideSearchFilterDatePicker.vue
- packages/ripple-ui-forms/src/inputs/datePicker.ts
- add variant prop to datePicker
> fix(@dpc-sdp/ripple-ui-forms): add variant prop to datePicker

- examples/nuxt-app/test/fixtures/map-table/vsba/localities-all.json
- examples/nuxt-app/test/fixtures/map-table/vsba/localities-nyah.json
- packages/ripple-tide-search/components/global/TideSearchAddressLookup.vue
- packages/ripple-tide-search/utils/search.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-1733
- 
- 
- 
-
> [R20-1733] - Update location suggestion logic after result format change

- packages/nuxt-ripple/app.config.ts
- packages/ripple-tide-search/components/global/TideCustomCollection.vue
- packages/ripple-tide-search/components/global/TideSearchAddressLookup.vue
- packages/ripple-tide-search/composables/useTideSearch.ts
- packages/ripple-tide-search/types.ts
- packages/ripple-ui-maps/src/components/map/utils.ts
- packages/ripple-ui-maps/src/index.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-1733
Example hook that zooms into the closest pin to a suburb
- 
- 
- 
-
> [R20-1733] Add hook for customizing map zoom behaviour

- packages/ripple-ui-core/src/components/search-bar/RplSearchBarRefine.css
- packages/ripple-ui-forms/src/components/RplFormActions/RplFormActions.css
**Issue**:
https://digital-vic.atlassian.net/browse/R20-1749
https://digital-vic.atlassian.net/browse/R20-1748
- Update filter button states for refine search and clear search filters
- Fix the clear search filters icon colour on focus
> [R20-1749][R20-1748] update filter buttons

- examples/nuxt-app/test/features/search-listing/filters.feature
- examples/nuxt-app/test/fixtures/landingpage/custom-collection/alt-form-theme-default.json
- examples/nuxt-app/test/fixtures/landingpage/custom-collection/alt-form-theme-reverse.json
- examples/nuxt-app/test/fixtures/landingpage/custom-collection/form-theme-default.json
- examples/nuxt-app/test/fixtures/landingpage/custom-collection/form-theme-reverse.json
- examples/nuxt-app/test/fixtures/search-listing/dependent-filters/page-single.json
- examples/nuxt-app/test/fixtures/search-listing/dependent-filters/request-birds-grandchildren-single.json
- examples/nuxt-app/test/fixtures/search-listing/dependent-filters/request-birds-grandchildren.json
- examples/nuxt-app/test/fixtures/search-listing/dependent-filters/request-birds.json
- examples/nuxt-app/test/fixtures/search-listing/dependent-filters/request-mammals-birds.json
- examples/nuxt-app/test/fixtures/search-listing/dependent-filters/request-mammals-children.json
- examples/nuxt-app/test/fixtures/search-listing/dependent-filters/request-mammals.json
- packages/ripple-test-utils/step_definitions/content-types/listing.ts
- packages/ripple-tide-search/components/global/TideSearchFilterDependent.vue
- packages/ripple-tide-search/composables/useTideSearch.ts
- packages/ripple-tide-search/types.ts
- packages/ripple-ui-core/package.json
- packages/ripple-ui-core/src/styles/generated/_grid.css
- packages/ripple-ui-core/src/tokens/utils.ts
- packages/ripple-ui-core/src/tokens/utils/grid.ts
- packages/ripple-ui-core/src/tokens/utils/margin.ts
- packages/ripple-ui-core/src/tokens/utils/padding.ts
- Add support for any number of nested dependent filters
> feat: infinite dependent filters

- packages/nuxt-ripple-analytics/lib/index.ts
> feat(@dpc-sdp/nuxt-ripple-analytics): :sparkles: add index to rpl-card/navigate

- examples/nuxt-app/test/features/search-listing/filters.feature
- examples/nuxt-app/test/fixtures/search-listing/dependent-filters/page-mix.json
- packages/ripple-test-utils/step_definitions/content-types/listing.ts
- packages/ripple-tide-search/components/global/TideSearchFilterDependent.vue
- packages/ripple-tide-search/composables/useTideSearch.ts
- packages/ripple-tide-search/types.ts
- Allow multiple to be set per level
> feat(@dpc-sdp/ripple-tide-search): allow multiple to be set per level

- packages/ripple-test-utils/step_definitions/content-types/listing.ts
- packages/ripple-ui-forms/src/components/RplFormHelpText/RplFormHelpText.css
- packages/ripple-ui-forms/src/components/RplFormLabel/RplFormLabel.css
- packages/ripple-ui-forms/src/components/RplFormLabel/RplFormLabel.vue
- packages/ripple-ui-forms/src/components/RplFormValidationError/RplFormValidationError.css
**Issue**: https://digital-vic.atlassian.net/browse/R20-428
- label area feedback
> [R20-428] updates to label area spacing

- packages/ripple-tide-search/components/global/TideSearchAddressLookup.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-1831
- add label and placeholder props to address lookup component
> [R20-1831] add label and placeholder props to address lookup

- packages/ripple-ui-maps/src/components/map/RplMap.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-1818
- Close popup on new searches (@jeffdowdle let me know if you had something else in mind for this)
> [R20-1818] close popup on new searches

- packages/nuxt-ripple/components/TideContentRating.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-1836
- add pii false to content rating
> [R20-1836] add pii flag to content rating

- packages/ripple-ui-core/src/components/primary-nav/components/quick-exit/RplPrimaryNavQuickExit.vue
- Hide quick exit for print, doesn't serve any purpose there
> fix(@dpc-sdp/ripple-ui-core): hide quick exit for print

- docs/content/design-system/5.components/accordion.md
- docs/content/design-system/5.components/file.md
- packages/ripple-ui-core/src/components/accordion/RplAccordion.stories.mdx
- packages/ripple-ui-core/src/components/document/RplDocument.vue
**Issue**: Fixes #730 
- Added separate story for numbered accordion example (wasn't respecting param, I suspect it's a type issue), relinked docs page
- Removed 'updated date' from docs, since none of our examples or uses have this
- 
-
> fix(docs): :bug: fix docs issues

- CHANGELOG.md
- lerna.json
- packages/eslint-config-ripple/package.json
- packages/nuxt-ripple-analytics/package.json
- packages/nuxt-ripple-cli/package.json
- packages/nuxt-ripple-preview/package.json
- packages/nuxt-ripple/package.json
- packages/ripple-storybook/package.json
- packages/ripple-test-utils/package.json
- packages/ripple-tide-api/package.json
- packages/ripple-tide-event/package.json
- packages/ripple-tide-grant/package.json
- packages/ripple-tide-landing-page/package.json
- packages/ripple-tide-media/package.json
- packages/ripple-tide-news/package.json
- packages/ripple-tide-publication/package.json
- packages/ripple-tide-search/package.json
- packages/ripple-tide-topic/package.json
- packages/ripple-ui-core/package.json
- packages/ripple-ui-forms/package.json
- packages/ripple-ui-maps/package.json
- packages/stylelint-config-ripple/package.json
> Release Ripple 2.7.0

- packages/ripple-tide-search/components/global/TideCustomCollection.vue
- fix dependent filter reset for custom collection
> fix(@dpc-sdp/ripple-tide-search): fix dependent filter reset for custom collection

- packages/ripple-tide-landing-page/mapping/components/call-to-action/call-to-action.ts
- packages/ripple-ui-core/src/components/card/RplCallToActionCard.stories.mdx
- packages/ripple-ui-core/src/components/card/RplCallToActionCard.vue
- packages/ripple-ui-core/src/components/card/RplCard.css
This reverts commit dbb48c512ac93c25de771b7d137dc2f8106d6af1.
**Issue**: https://digital-vic.atlassian.net/browse/R20-1822
- The CTA cards that were just added are now to be removed 😞
> [R20-1822] remove cta cards

- packages/nuxt-ripple-cli/src/commands/init/_templates/site/latest/env.t
- remove trailing slash from example env
> fix(@dpc-sdp/nuxt-ripple-cli): remove trailing slash from example env

- packages/ripple-test-utils/step_definitions/common/mocks.ts
- packages/ripple-test-utils/step_definitions/components/maps.ts
- packages/ripple-test-utils/step_definitions/content-types/listing.ts
- packages/ripple-tide-search/components/global/TideCustomCollection.vue
- minor eslint cleanup, there's still a bunch of maps related warnings which we can look at after the big maps PR goes through.
> fix: minor eslint cleanup

- packages/nuxt-ripple/server/routes/sites/default/files/[...].ts
**Issue**: https://digital-vic.atlassian.net/browse/SRM-1302
- Proxy "relative" files
> [SRM-1302] proxy relative file paths

- examples/nuxt-app/components/global/VsbaMapPopupContent.vue
- examples/nuxt-app/mock-routes.json
- examples/nuxt-app/package.json
- packages/nuxt-ripple-cli/src/commands/favicon/index.ts
- packages/nuxt-ripple/utils/breadcrumbs.ts
- packages/ripple-tide-api/package.json
- packages/ripple-tide-api/src/helpers.ts
- packages/ripple-tide-landing-page/components/global/TideLandingPage/ContentCollection.vue
- packages/ripple-tide-search/components/TideSearchPage.vue
- packages/ripple-tide-search/composables/useSearchResult.ts
- packages/ripple-tide-search/pages/search.vue
- pnpm-lock.yaml
- tsconfig.json
**Issue**:
- Fixed error in client side code after this commit https://github.com/dpc-sdp/ripple-framework/pull/1084/files#diff-275b89f10d026bf7cc95f269ea4b37e1689c60305475170b409ad175f5781faeR1
- Ripple-tide-api exports code which expects a node environment, when imported into client bundle things like process are undefined.
- Cypress tests should pass 
- Run `pnpm -F nuxt-app dev` - check for errors in javascript console in browser
> fix undefined process error in client side code

- packages/ripple-test-utils/step_definitions/components/data-table.ts
- packages/ripple-ui-core/src/components/data-table/RplDataTable.css
- packages/ripple-ui-core/src/components/data-table/RplDataTable.cy.ts
- packages/ripple-ui-core/src/components/data-table/RplDataTable.vue
- packages/ripple-ui-core/src/components/data-table/RplDataTableRow.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-1902 
- Table styling tweaks
- Updated the breakpoints that the table responds to, this is different based on whether there is a sidebar
- 
-
> [R20-1902] - Updates to data table styling from design feedback

- examples/nuxt-app/package.json
> chore: remove mockserver from cypress test local run

- CHANGELOG.md
- lerna.json
- packages/eslint-config-ripple/package.json
- packages/nuxt-ripple-analytics/package.json
- packages/nuxt-ripple-cli/package.json
- packages/nuxt-ripple-preview/package.json
- packages/nuxt-ripple/package.json
- packages/ripple-storybook/package.json
- packages/ripple-test-utils/package.json
- packages/ripple-tide-api/package.json
- packages/ripple-tide-event/package.json
- packages/ripple-tide-grant/package.json
- packages/ripple-tide-landing-page/package.json
- packages/ripple-tide-media/package.json
- packages/ripple-tide-news/package.json
- packages/ripple-tide-publication/package.json
- packages/ripple-tide-search/package.json
- packages/ripple-tide-topic/package.json
- packages/ripple-ui-core/package.json
- packages/ripple-ui-forms/package.json
- packages/ripple-ui-maps/package.json
- packages/stylelint-config-ripple/package.json
> chore: 🔖 release ripple 2.8.0

- examples/nuxt-app/components/global/VsbaMapPopupContent.vue
- packages/nuxt-ripple/utils/breadcrumbs.ts
- packages/nuxt-ripple/utils/utils.ts
- packages/ripple-tide-landing-page/components/global/TideLandingPage/ContentCollection.vue
- packages/ripple-tide-search/components/TideSearchPage.vue
- packages/ripple-tide-search/composables/useSearchResult.ts
- packages/ripple-tide-search/pages/search.vue
> fix: :bug: move stripsite id fn to auto import util

- CHANGELOG.md
- lerna.json
- packages/eslint-config-ripple/package.json
- packages/nuxt-ripple-analytics/package.json
- packages/nuxt-ripple-cli/package.json
- packages/nuxt-ripple-preview/package.json
- packages/nuxt-ripple/package.json
- packages/ripple-storybook/package.json
- packages/ripple-test-utils/package.json
- packages/ripple-tide-api/package.json
- packages/ripple-tide-event/package.json
- packages/ripple-tide-grant/package.json
- packages/ripple-tide-landing-page/package.json
- packages/ripple-tide-media/package.json
- packages/ripple-tide-news/package.json
- packages/ripple-tide-publication/package.json
- packages/ripple-tide-search/package.json
- packages/ripple-tide-topic/package.json
- packages/ripple-ui-core/package.json
- packages/ripple-ui-forms/package.json
- packages/ripple-ui-maps/package.json
- packages/stylelint-config-ripple/package.json
> chore: 🔖 release ripple 2.8.1

- packages/ripple-test-utils/step_definitions/components/maps.ts
- packages/ripple-ui-core/src/components/tabs/RplTabs.css
- packages/ripple-ui-core/src/components/tabs/RplTabs.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-1875
- removed coupling with rpl-button component to avoid fighting with overrides
- 
- 
-
> [R20-1875] Updated tabs component based on design feedback

- packages/ripple-tide-search/composables/useSearchUI.ts
- packages/ripple-ui-core/src/components/search-bar/RplSearchBar.css
- packages/ripple-ui-core/src/components/search-bar/RplSearchBar.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-1868
- 
-
> [R20-1868] - Add clear button to search bar component

- packages/ripple-ui-maps/src/components/legend/RplMapLegend.css
- packages/ripple-ui-maps/src/components/legend/RplMapLegend.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-1881
- 
- 
- 
-
> [R20-1881] - Updated map key styling after design feedback

- packages/ripple-ui-forms/src/components/RplForm/RplForm.stories.mdx
**Issue**: https://digital-vic.atlassian.net/browse/R20-428
- Add p tags to forms story, this is to get around a CSS loading order issue present in the built version of storybook
> [R20-428] update form story help text

- packages/ripple-tide-search/components/global/TideSearchAddressLookup.vue
- packages/ripple-ui-core/src/components/search-bar/RplSearchBar.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-1868
- 
- 
- 
-
> fix(@dpc-sdp/ripple-ui-core): fixed search bar clear btn submitting form when not wanted

- CHANGELOG.md
- lerna.json
- packages/eslint-config-ripple/package.json
- packages/nuxt-ripple-analytics/package.json
- packages/nuxt-ripple-cli/package.json
- packages/nuxt-ripple-preview/package.json
- packages/nuxt-ripple/package.json
- packages/ripple-storybook/package.json
- packages/ripple-test-utils/package.json
- packages/ripple-tide-api/package.json
- packages/ripple-tide-event/package.json
- packages/ripple-tide-grant/package.json
- packages/ripple-tide-landing-page/package.json
- packages/ripple-tide-media/package.json
- packages/ripple-tide-news/package.json
- packages/ripple-tide-publication/package.json
- packages/ripple-tide-search/package.json
- packages/ripple-tide-topic/package.json
- packages/ripple-ui-core/package.json
- packages/ripple-ui-forms/package.json
- packages/ripple-ui-maps/package.json
- packages/stylelint-config-ripple/package.json
> chore: 🔖 release ripple 2.8.2

- packages/ripple-ui-core/src/components/data-table/RplDataTableRow.vue
- remove unused import to appease eslint
> fix(@dpc-sdp/ripple-ui-core): remove unused import to appease eslint

- .vscode/extensions.json
- packages/ripple-ui-core/package.json
- packages/ripple-ui-core/src/components/acknowledgement/RplAcknowledgement.vue
- packages/ripple-ui-core/src/vite.plugins.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-1973
- Refactored acknowledgement flag assets as data attribute (nuxt 3.11.2 default) and basic html elements to avoid breaking the URL (doesn't need anything from `RplImage`)
- 
- `pnpm -F nuxt-app build && pnpm -F nuxt-app preview` or v2.reference
-
> [R20-1973] Acknowledgement img fix

- packages/ripple-ui-core/src/components/layout/RplLayoutBackToTop.css
**Issue**: https://digital-vic.atlassian.net/browse/R20-1961
- 
- 
- 
-
> [R20-1961] - Fixed back to top button being clickable when hidden

- package.json
- packages/ripple-ui-maps/package.json
- pnpm-lock.yaml
**Issue**:
- updated nuxt/kit version to resolve engine warnings
- added resolutions packages with security warnings
- 
-
> build(@dpc-sdp/ripple-ui-maps): fix outdated kit version

- CHANGELOG.md
- lerna.json
- packages/eslint-config-ripple/package.json
- packages/nuxt-ripple-analytics/package.json
- packages/nuxt-ripple-cli/package.json
- packages/nuxt-ripple-preview/package.json
- packages/nuxt-ripple/package.json
- packages/ripple-storybook/package.json
- packages/ripple-test-utils/package.json
- packages/ripple-tide-api/package.json
- packages/ripple-tide-event/package.json
- packages/ripple-tide-grant/package.json
- packages/ripple-tide-landing-page/package.json
- packages/ripple-tide-media/package.json
- packages/ripple-tide-news/package.json
- packages/ripple-tide-publication/package.json
- packages/ripple-tide-search/package.json
- packages/ripple-tide-topic/package.json
- packages/ripple-ui-core/package.json
- packages/ripple-ui-forms/package.json
- packages/ripple-ui-maps/package.json
- packages/stylelint-config-ripple/package.json
> chore: 🔖 release ripple 2.9.0

- examples/nuxt-app/package.json
- examples/vue-app/package.json
- package.json
- packages/ripple-test-utils/package.json
- pnpm-lock.yaml
> chore: :arrow_up: remove conflicting version of wait-on

- packages/nuxt-ripple/components/TideSidebarSocialShare.vue
- Quick fix for console errors on all route changes with social share sidebar
> fix(@dpc-sdp/nuxt-ripple): fix console error on route change

- packages/ripple-tide-webform/mapping/webforms-mapping.ts
> fix(@dpc-sdp/ripple-tide-webform): :bug: use ts target

- packages/ripple-storybook/.storybook/preview.ts
- packages/ripple-ui-forms/src/components/RplForm/RplForm.stories.mdx
- packages/ripple-ui-forms/src/components/RplForm/RplForm.vue
- packages/ripple-ui-forms/src/components/RplFormActions/RplFormActions.vue
- packages/ripple-ui-forms/src/components/RplFormAlert/RplFormAlert.vue
- packages/ripple-ui-forms/src/components/RplFormContent/RplFormContent.vue
- packages/ripple-ui-forms/src/components/RplFormDropdown/RplFormDropdown.vue
- packages/ripple-ui-forms/src/components/RplFormHelpText/RplFormHelpText.vue
- packages/ripple-ui-forms/src/components/RplFormInput/RplFormInput.vue
- packages/ripple-ui-forms/src/components/RplFormNumber/RplFormNumber.vue
- packages/ripple-ui-forms/src/components/RplFormOptions/RplFormOption.vue
- packages/ripple-ui-forms/src/components/RplFormValidationError/RplFormValidationError.vue
- Remove ripple-ui-core/vue imports from form package
> feat(@dpc-sdp/ripple-ui-forms): remove ripple-ui-core/vue imports

- packages/ripple-ui-forms/src/components/RplFormNumber/RplFormNumber.stories.mdx
- packages/ripple-ui-forms/src/components/RplFormNumber/RplFormNumber.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-1949
- Add focusable classes to number input buttons
- Add `type` attr to button markup for accessibility
- Style fixes from feedback
- 
-
> [R20-1949] Style updates to number input

- README.md
- packages/ripple-ui-forms/README.md
> Fixed incorrect docs relating to forms and vue apps

- packages/ripple-ui-forms/src/components/RplFormNumber/RplFormNumber.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-1949
- Style adjustments
- 
- 
-
> [R20-1949] Number input feedback

- packages/ripple-ui-core/src/components.ts
- Cleanup component exports 
- Add missing exports
> chore(@dpc-sdp/ripple-ui-core): cleanup vue component exports

- examples/nuxt-app/test/features/grant/grant.feature
- examples/nuxt-app/test/fixtures/grant/tc-9a-grant-simple-test-date-range.json
- packages/ripple-test-utils/step_definitions/content-types/grant.ts
- packages/ripple-tide-grant/components/TideGrantOverview.vue
- packages/ripple-tide-grant/mapping/index.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-1942
- fix internal links on grant CTAs
> [R20-1942] fix internal links on grant CTAs

- packages/ripple-ui-maps/src/components/map/RplMap.vue
- packages/ripple-ui-maps/src/components/map/utils.ts
- packages/ripple-ui-maps/src/components/popup/RplMapPopUp.css
- packages/ripple-ui-maps/src/composables/useMapDeadSpace.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-1805
- 
- 
- 
-
> [R20-1805] Changed the design of the 'infobox' popup on small screens

- packages/ripple-tide-search/components/global/TideCustomCollection.vue
- packages/ripple-tide-search/components/global/TideSearchAddressLookup.vue
- packages/ripple-tide-search/components/global/TideSearchListingResultsMapSidepanel.vue
- packages/ripple-ui-maps/package.json
- packages/ripple-ui-maps/src/nuxt/index.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-1723
- Made ripple-ui-maps the same as ripple-ui-core in the way it exports the nuxt specific code
- Removed some imports and use nuxt's auto imports instead
- 
-
> [R20-1723] - Fixed maps when added to a site after nuxt update 

- CHANGELOG.md
- lerna.json
- packages/eslint-config-ripple/package.json
- packages/nuxt-ripple-analytics/package.json
- packages/nuxt-ripple-cli/package.json
- packages/nuxt-ripple-preview/package.json
- packages/nuxt-ripple/package.json
- packages/ripple-storybook/package.json
- packages/ripple-test-utils/package.json
- packages/ripple-tide-api/package.json
- packages/ripple-tide-event/package.json
- packages/ripple-tide-grant/package.json
- packages/ripple-tide-landing-page/package.json
- packages/ripple-tide-media/package.json
- packages/ripple-tide-news/package.json
- packages/ripple-tide-publication/package.json
- packages/ripple-tide-search/package.json
- packages/ripple-tide-topic/package.json
- packages/ripple-tide-webform/package.json
- packages/ripple-ui-core/package.json
- packages/ripple-ui-forms/package.json
- packages/ripple-ui-maps/package.json
- packages/stylelint-config-ripple/package.json
> chore: 🔖 release ripple 2.10.0

- examples/nuxt-app/app.config.ts
- packages/ripple-tide-search/components/global/TideCustomCollection.vue
- packages/ripple-tide-search/types.ts
> feat(@dpc-sdp/ripple-tide-search): allow search result mapping to be customised

- CHANGELOG.md
- lerna.json
- packages/eslint-config-ripple/package.json
- packages/nuxt-ripple-analytics/package.json
- packages/nuxt-ripple-cli/package.json
- packages/nuxt-ripple-preview/package.json
- packages/nuxt-ripple/package.json
- packages/ripple-storybook/package.json
- packages/ripple-test-utils/package.json
- packages/ripple-tide-api/package.json
- packages/ripple-tide-event/package.json
- packages/ripple-tide-grant/package.json
- packages/ripple-tide-landing-page/package.json
- packages/ripple-tide-media/package.json
- packages/ripple-tide-news/package.json
- packages/ripple-tide-publication/package.json
- packages/ripple-tide-search/package.json
- packages/ripple-tide-topic/package.json
- packages/ripple-tide-webform/package.json
- packages/ripple-ui-core/package.json
- packages/ripple-ui-forms/package.json
- packages/ripple-ui-maps/package.json
- packages/stylelint-config-ripple/package.json
> chore: 🔖 release ripple 2.10.1

- packages/ripple-tide-search/components/global/TideCustomCollection.vue
- packages/ripple-tide-search/components/global/TideSearchAddressLookup.vue
- packages/ripple-tide-search/composables/useTideSearch.ts
- packages/ripple-tide-search/types.ts
- packages/ripple-ui-maps/src/components/geolocation/RplMapGeolocateButton.css
- packages/ripple-ui-maps/src/components/geolocation/RplMapGeolocateButton.stories.mdx
- packages/ripple-ui-maps/src/components/geolocation/RplMapGeolocateButton.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-1725
- 
- 
- 
-
> [R20-1725] Geolocation button for maps

- packages/ripple-test-utils/step_definitions/content-types/listing.ts
- packages/ripple-ui-forms/src/components/RplFormDropdown/RplFormDropdown.stories.mdx
- packages/ripple-ui-forms/src/components/RplFormDropdown/RplFormDropdown.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-1856
- adds an option with the placeholder as the label, mimicking a native select input
- 
- 
-
> [R20-1856] - Allow single select dropdowns to be 'deselected'

- packages/ripple-ui-forms/src/components/RplForm/RplForm.stories.mdx
- packages/ripple-ui-forms/src/components/RplFormOptions/RplFormOption.css
**Issue**: https://digital-vic.atlassian.net/browse/R20-464
- Minor feedback items
> [R20-464] minor feedback items

- packages/ripple-ui-core/src/components/primary-nav/components/nav-bar/RplPrimaryNavBar.css
**Issue**: https://github.com/dpc-sdp/ripple-framework/issues/1112
- Fixes alignment on primary nav
- Also fixes 'line height' for items that wrap
> style(@dpc-sdp/ripple-ui-core): fix primary nav alignment

- packages/nuxt-ripple-cli/src/commands/init/_templates/site/latest/app.config.ts.t
- packages/nuxt-ripple-cli/src/commands/init/_templates/site/latest/env.t
- packages/nuxt-ripple-cli/src/commands/init/_templates/site/latest/nuxt.config.ts.t
- packages/nuxt-ripple-cli/src/commands/init/_templates/site/latest/nvmrc.t
- packages/nuxt-ripple-cli/src/commands/init/_templates/site/latest/package.json.t
**Issue**:
- Update CLI new site template 
- 
- 
-
> chore(@dpc-sdp/nuxt-ripple-cli): update new project template

- packages/ripple-ui-core/src/components/text-link/RplTextLink.css
**Issue**: https://digital-vic.atlassian.net/browse/R20-1987
- 
- 
- 
-
> [R20-1987] Fixed visited link colors not being original link color

- packages/ripple-tide-search/nuxt.config.ts
- packages/ripple-tide-search/package.json
- pnpm-lock.yaml
- Update search-ui packages, see issue for context: https://github.com/dpc-sdp/ripple-framework/issues/1205
> fix(@dpc-sdp/ripple-tide-search): update search-ui packages

- packages/ripple-tide-search/components/TideSearchSortOptions.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-2036
- Add new allow deselect prop to sort
> [R20-2036] add allow deselect prop to sort

- packages/nuxt-ripple/components/TideContentRating.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-699
-  Content rating feedback
> [R20-699] content rating feedback

- packages/ripple-ui-core/src/components/campaign-banner/RplPrimaryCampaign.stories.mdx
- packages/ripple-ui-core/src/components/campaign-banner/RplSecondaryCampaign.stories.mdx
**Issue**: https://digital-vic.atlassian.net/browse/R20-329
- story content update
> [R20-329] story content update

- packages/ripple-tide-landing-page/components/global/TideLandingPage/WebForm.vue
**Issue**:
- Remove RplFormAltert import to get success icon working again
> fix(@dpc-sdp/ripple-tide-landing-page): content rating success icon

- packages/ripple-ui-core/src/components/result-listing/RplSearchResult.css
- packages/ripple-ui-core/src/components/result-listing/RplSearchResult.vue
- packages/ripple-ui-core/src/components/text-link/RplTextLink.css
- packages/ripple-ui-core/src/styles/global.css
- packages/ripple-ui-core/src/styles/utilities/_visited.css
**Issue**: https://digital-vic.atlassian.net/browse/R20-1987
- 
- 
- 
-
> [R20-1987] Changed visited link style to a util class

- examples/nuxt-app/test/features/publication/publication.feature
- examples/nuxt-app/test/fixtures/publication/sample-print-all.json
- packages/ripple-test-utils/step_definitions/common/shared-elements.ts
- packages/ripple-test-utils/step_definitions/content-types/publication.ts
- packages/ripple-tide-publication/pages/[slug]/print-all.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-2042
- Fix print all pages, seems like these died at some point (maybe a nuxt update?) https://app.uat.vic-gov-au.sdp4.sdp.vic.gov.au/family-violence-and-sexual-assault-workforce-pulse-survey-report/
- Add no-index to print all pages
- Add some tests
> [R20-2042] fix print all pages, add no-index and some tests

- packages/ripple-tide-search/composables/useTideSearch.ts
> fix(@dpc-sdp/ripple-ui-core): set firstLoad in finally block

- packages/ripple-ui-core/src/styles/utilities/_lists.css
**Issue**: https://digital-vic.atlassian.net/browse/R20-1459
- Add support for Drupal list types
> [R20-1459] add support for list types

- packages/ripple-tide-api/src/utils/markup-transpiler/cheerio.test.ts
- packages/ripple-tide-api/src/utils/markup-transpiler/default-plugins.ts
- packages/ripple-ui-core/src/styles/utilities/_lists.css
**Issue**: https://digital-vic.atlassian.net/browse/R20-1459
- Padding update, remove circle support (design requirement for a11y)
> [R20-1459] padding update, remove circle support

- examples/nuxt-app/test/features/publication/publication.feature
- packages/ripple-test-utils/step_definitions/content-types/publication.ts
- packages/ripple-ui-core/src/components/content/RplContent.stories.mdx
- packages/ripple-ui-core/src/components/document/RplDocument.vue
- packages/ripple-ui-core/src/components/file/RplFile.vue
- packages/ripple-ui-core/src/components/result-listing/RplResultListing.stories.mdx
- packages/ripple-ui-core/src/components/result-listing/RplSearchResult.css
- packages/ripple-ui-core/src/components/result-listing/RplSearchResult.vue
- packages/ripple-ui-core/src/styles/components/_document.css
- packages/ripple-ui-core/src/styles/components/_file.css
**Issue**: https://digital-vic.atlassian.net/browse/R20-2057
- Adds the requested file 'variant' to search results
> [R20-2057] add requested file 'variant' to search results

- packages/ripple-ui-core/src/components/accordion/RplAccordion.cy.ts
- packages/ripple-ui-core/src/components/card-carousel/RplCardCarousel.cy.ts
- packages/ripple-ui-core/src/components/footer/RplFooter.cy.ts
- packages/ripple-ui-core/src/components/media-embed/RplMediaEmbed.cy.ts
- packages/ripple-ui-core/src/components/media-gallery/RplMediaGallery.cy.ts
- packages/ripple-ui-core/src/components/primary-nav/RplPrimaryNav.cy.ts
- packages/ripple-ui-core/src/components/search-bar/RplSearchBar.cy.ts
- packages/ripple-ui-core/src/components/tabs/RplTabs.cy.ts
- Update component tests to cover a few more features
> feat(@dpc-sdp/ripple-ui-core): update component tests to cover a few more features

- packages/ripple-tide-search/components/global/TideSearchListing/TideSearchListingTableUrl.vue
**Issue**: https://digital-vic.atlassian.net/browse/SDPAP-9392
- Fallback to value if no URL exists
> [SDPAP-9392] fallback to value if no URL exists

- packages/ripple-tide-news/components/TideNewsBody.vue
[R20-2092]
**Issue**:
- 
- 
- 
- 
[R20-2092]: https://digital-vic.atlassian.net/browse/R20-2092?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(@dpc-sdp/ripple-tide-news): :bug: added flag option to remove published time

- packages/ripple-tide-search/components/global/TideCustomCollection.vue
- add variant prop to locationQueryConfig component
> fix(@dpc-sdp/ripple-tide-search): add variant prop to locationQueryConfig component

- CHANGELOG.md
- lerna.json
- packages/eslint-config-ripple/package.json
- packages/nuxt-ripple-analytics/package.json
- packages/nuxt-ripple-cli/package.json
- packages/nuxt-ripple-preview/package.json
- packages/nuxt-ripple/package.json
- packages/ripple-storybook/package.json
- packages/ripple-test-utils/package.json
- packages/ripple-tide-api/package.json
- packages/ripple-tide-event/package.json
- packages/ripple-tide-grant/package.json
- packages/ripple-tide-landing-page/package.json
- packages/ripple-tide-media/package.json
- packages/ripple-tide-news/package.json
- packages/ripple-tide-publication/package.json
- packages/ripple-tide-search/package.json
- packages/ripple-tide-topic/package.json
- packages/ripple-tide-webform/package.json
- packages/ripple-ui-core/package.json
- packages/ripple-ui-forms/package.json
- packages/ripple-ui-maps/package.json
- packages/stylelint-config-ripple/package.json
> chore: 🔖 release ripple 2.12.0

- packages/nuxt-ripple-analytics/lib/index.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-730
- add fallback origin in dataLayer for relative URLs
> [R20-730] add fallback origin in dataLayer for relative URLs

- examples/nuxt-app/nuxt.config.ts
- examples/nuxt-app/package.json
- packages/ripple-sdp-core/LICENSE
- packages/ripple-sdp-core/README.md
- packages/ripple-sdp-core/nuxt.config.ts
- packages/ripple-sdp-core/package.json
- packages/ripple-sdp-core/tsconfig.json
- pnpm-lock.yaml
**Issue**:
- Add a new nuxt layer `ripple-sdp-core` that _only_ adds the tide content type layers for forward upgrade convenience
- That's all it does
- 3rd time lucky
- 
- Pre-release published on `2.0.0-alpha.481+bb0a519a9`, tested against reference
-
> feat: :sparkles: Combine tide layers into sdp-core package

- .github/workflows/publish-canary.yml
> chore: update canary action to publish on release branches

- docs/content/framework/4.core-modules.md
- update modules and links in the docs site
> chore(docs): update modules and links

- CHANGELOG.md
- lerna.json
- packages/eslint-config-ripple/package.json
- packages/nuxt-ripple-analytics/package.json
- packages/nuxt-ripple-cli/package.json
- packages/nuxt-ripple-preview/package.json
- packages/nuxt-ripple/package.json
- packages/ripple-sdp-core/package.json
- packages/ripple-storybook/package.json
- packages/ripple-test-utils/package.json
- packages/ripple-tide-api/package.json
- packages/ripple-tide-event/package.json
- packages/ripple-tide-grant/package.json
- packages/ripple-tide-landing-page/package.json
- packages/ripple-tide-media/package.json
- packages/ripple-tide-news/package.json
- packages/ripple-tide-publication/package.json
- packages/ripple-tide-search/package.json
- packages/ripple-tide-topic/package.json
- packages/ripple-tide-webform/package.json
- packages/ripple-ui-core/package.json
- packages/ripple-ui-forms/package.json
- packages/ripple-ui-maps/package.json
- packages/stylelint-config-ripple/package.json
> chore: 🔖 release ripple 2.14.0

- packages/ripple-tide-landing-page/mapping/components/generic-card-mapping.ts
- packages/ripple-tide-landing-page/mapping/components/promo-card/promo-card-mapping.test.ts
**Issue**: https://digital-vic.atlassian.net/browse/SRM-1503
- Fix hydration mismatch error on tide card content
> [SRM-1503] fix hydration mismatch error on tide card content

- packages/ripple-ui-core/src/styles/utilities/_lists.css
**Issue**: https://digital-vic.atlassian.net/browse/SDPSUP-7379
- Fix RTL lists bullet point
> [SDPSUP-7379] fix RTL lists bullet point

- packages/ripple-tide-search/composables/useTideSearch.ts
**Issue:** https://digital-vic.atlassian.net/browse/SD-264
- Pass location to customQueryConfig function
> [SD-264] pass location to customQueryConfig

- examples/nuxt-app/test/features/landingpage/page-components.feature
- examples/nuxt-app/test/fixtures/landingpage/home.json
- packages/ripple-tide-landing-page/components/global/TideLandingPage/PromoCard.vue
- packages/ripple-tide-landing-page/mapping/components/promo-card/promo-card-mapping.ts
**Issue**: https://digital-vic.atlassian.net/browse/SD-131
- Update to support the new CMS promo highlight option
> [SD-131] CMS promo highlight

- packages/ripple-tide-grant/components/TideGrantDocuments.vue
- packages/ripple-ui-core/src/components/document/RplDocument.vue
**Issue**: https://digital-vic.atlassian.net/browse/SD-274
- update download attribute
-  add space between grant downloads
> [SD-274] update download attribute, add space between grant downloads

- examples/nuxt-app/test/features/site/analytics.feature
- examples/nuxt-app/test/fixtures/landingpage/home.json
- packages/nuxt-ripple-analytics/lib/routeChange.ts
- packages/nuxt-ripple-analytics/lib/tracker.ts
**Issue**: https://digital-vic.atlassian.net/browse/SD-253
- Add content status to routeChange event
> [SD-253] add content status to routeChange

- examples/nuxt-app/test/features/landingpage/forms.feature
- examples/nuxt-app/test/features/search-listing/analytics.feature
- examples/nuxt-app/test/fixtures/landingpage/full-form.json
- packages/nuxt-ripple-analytics/lib/index.ts
- packages/ripple-test-utils/step_definitions/common/site/analytics.ts
- packages/ripple-test-utils/step_definitions/components/forms.ts
- packages/ripple-tide-search/components/global/TideSearchFilterCheckbox.vue
- packages/ripple-tide-search/components/global/TideSearchFilterCheckboxGroup.vue
- packages/ripple-tide-search/components/global/TideSearchFilterDependent.vue
- packages/ripple-tide-search/components/global/TideSearchFilterDropdown.vue
- packages/ripple-ui-forms/src/components/RplFormDropdown/RplFormDropdown.vue
- packages/ripple-ui-forms/src/components/RplFormNumber/RplFormNumber.vue
- packages/ripple-ui-forms/src/components/RplFormOptions/RplFormCheckboxGroup.vue
- packages/ripple-ui-forms/src/components/RplFormOptions/RplFormOption.vue
- packages/ripple-ui-forms/src/components/RplFormOptions/RplFormRadioGroup.vue
- packages/ripple-ui-forms/src/inputs/datePicker.ts
- packages/ripple-ui-forms/src/lib/sanitisePII.ts
**Issue**: https://digital-vic.atlassian.net/browse/SD-239
- add RplFormNumber tracker so events are sent
- set pii value for search listing filters
- use labels for dataLayer events instead of the the value
> [SD-239] use dropdown labels, update search listing pii, track number input

- packages/ripple-tide-search/components/global/TideCustomCollection.vue
**Issue**: https://digital-vic.atlassian.net/browse/SD-353
-  add full stop to the end of sentence
> [SD-353] add full stop to the end of sentence

- examples/nuxt-app/package.json
- package.json
- packages/nuxt-ripple-cli/src/commands/init/_templates/layer/latest/package.json.t
- packages/nuxt-ripple-cli/src/commands/init/_templates/site/latest/package.json.t
- packages/ripple-test-utils/package.json
- packages/ripple-test-utils/src/config/index.ts
- packages/ripple-tide-api/package.json
- packages/ripple-ui-core/package.json
- packages/ripple-ui-forms/package.json
- packages/ripple-ui-maps/package.json
- pnpm-lock.yaml
> Update Nuxt to 2.13.2

- packages/ripple-tide-publication/pages/[slug]/print-all.vue
**Issue**: https://digital-vic.atlassian.net/browse/SD-367
- 
- 
- 
-
> [SD-367] added back the publication print all page header

- packages/ripple-ui-maps/src/components/map/RplMap.vue
- packages/ripple-ui-maps/src/components/popup/RplMapPopUp.css
- packages/ripple-ui-maps/src/components/popup/RplMapPopUp.vue
**Issue**: https://digital-vic.atlassian.net/browse/SD-333 
Old:
New:
- 
-
> [SD-333] Change map popover styling to match designs

- packages/ripple-tide-api/src/utils/markup-transpiler/cheerio.test.ts
- packages/ripple-tide-api/src/utils/markup-transpiler/default-plugins.ts
**Issue**: https://digital-vic.atlassian.net/browse/SD-372 
- Add support for secure file display
> [SD-372 ] secure file display

- examples/nuxt-app/test/features/site/feature-flags.feature
- examples/nuxt-app/test/features/sitemap/sitemap.feature
- examples/nuxt-app/test/fixtures/site/shared-elements.json
- packages/ripple-test-utils/step_definitions/common/shared-elements.ts
- packages/ripple-ui-core/src/components/breadcrumbs/RplBreadcrumbs.cy.ts
- packages/ripple-ui-core/src/components/breadcrumbs/RplBreadcrumbs.vue
- packages/ripple-ui-maps/src/components/popup/RplMapPopUp.vue
**Issue**: https://digital-vic.atlassian.net/browse/SD-366
- Make font sizing consistent
- Check if links should collapse before collapsing
- Add component tests and feature flag test
> [SD-366] breadcrumb issues

- packages/ripple-tide-api/src/utils/mapping-utils.test.ts
- packages/ripple-tide-api/src/utils/mapping-utils.ts
- packages/ripple-tide-api/types.d.ts
- packages/ripple-tide-landing-page/mapping/components/card-carousel/base-mapping.ts
- packages/ripple-tide-landing-page/mapping/components/card-carousel/custom-mapping.ts
- packages/ripple-tide-landing-page/mapping/components/card-carousel/test-data.ts
**Issue**: https://digital-vic.atlassian.net/browse/SRM-1608
- More hydration warnings, this time from the carousel content
> [SRM-1608] more hydration warnings

- packages/ripple-tide-search/components/TideSearchListingPage.vue
> fix(@dpc-sdp/ripple-tide-search): fix issue with search listing dropdwn reactivity

- examples/nuxt-app/cypress.config.mjs
**Issue**:
- Should start identifying flaky tests properly
- 
- 
-
> Enable cypress retries

- examples/nuxt-app/layers/ripple-ui-forms-ext/__test__/fixtures/webform.json
- examples/nuxt-app/test/features/site/theme.feature
- packages/nuxt-ripple/mapping/base/index.ts
- packages/ripple-tide-api/types.d.ts
**Issue**: https://digital-vic.atlassian.net/browse/SD-495
- Remove site section theming
> [SD-495] remove site section theming

- packages/nuxt-ripple/server/api/tide/webform_submission/[formId].ts
**Issue**: https://digital-vic.atlassian.net/browse/SD-550
- 
- 
- 
-
> [SD-550] added manual import for server util to fix webform submit

- packages/ripple-ui-core/src/components/breadcrumbs/RplBreadcrumbs.css
**Issue**: https://digital-vic.atlassian.net/browse/SD-423
- Update styles
- 
- Storybook
-
> [SD-423] New breadcrumbs style feedback

- examples/nuxt-app/nuxt.config.ts
- Temporary fix to get HMR working, this can hopefully be removed in the future
> fix: temp fix for HMR

- packages/ripple-ui-forms/src/components/RplFormDropdown/RplFormDropdown.vue
**Issue**: https://digital-vic.atlassian.net/browse/SD-180
- fix to always set input focus
> [SD-180] always set input focus

- packages/nuxt-ripple/server/api/tide/webform_submission/[formId].ts
- packages/ripple-tide-webform/nuxt.config.ts
**Issue**: https://digital-vic.atlassian.net/browse/SD-570
- Only sends header when env vars are set to make sure it's backwards compatible
- 
- 
-
> [SD-570] - Send basic auth header for webform submit

- packages/ripple-ui-core/src/components/search-banner/RplSearchBanner.css
**Issue**: https://digital-vic.atlassian.net/browse/SD-652
- Adds extra space between text in input on desktop
> [SD-652] search banner feedback

- packages/ripple-ui-core/src/components/progress/RplProgress.css
- packages/ripple-ui-core/src/components/progress/RplProgress.cy.ts
- packages/ripple-ui-core/src/components/progress/RplProgress.stories.mdx
- packages/ripple-ui-core/src/components/progress/RplProgress.vue
**Issue**: https://digital-vic.atlassian.net/browse/SD-576
- Added RplProgress component
- 
- 
-
> [SD-576] - Added RplProgress UI component

- packages/ripple-tide-landing-page/components/global/TideLandingPage/WebForm.vue
- packages/ripple-ui-forms/src/inputs/checkbox.ts
- packages/ripple-ui-forms/src/inputs/checkboxGroup.ts
- packages/ripple-ui-forms/src/inputs/date.ts
- packages/ripple-ui-forms/src/inputs/datePicker.ts
- packages/ripple-ui-forms/src/inputs/dateRange.ts
- packages/ripple-ui-forms/src/inputs/dropdown.ts
- packages/ripple-ui-forms/src/inputs/email.ts
- packages/ripple-ui-forms/src/inputs/hidden.ts
- packages/ripple-ui-forms/src/inputs/input-utils.ts
- packages/ripple-ui-forms/src/inputs/number.ts
- packages/ripple-ui-forms/src/inputs/optionButtons.ts
- packages/ripple-ui-forms/src/inputs/radioGroup.ts
- packages/ripple-ui-forms/src/inputs/tel.ts
- packages/ripple-ui-forms/src/inputs/text.ts
- packages/ripple-ui-forms/src/inputs/textarea.ts
- packages/ripple-ui-forms/src/inputs/url.ts
**Issue**: https://digital-vic.atlassian.net/browse/DDS-2091
- 
- 
- 
-
> [DDS-209] Improve memory usage of forms

- packages/ripple-ui-maps/src/components/cluster/RplMapCluster.vue
> chore: remove unneeded key

- examples/nuxt-app/test/features/landingpage/custom-collection.feature
- examples/nuxt-app/test/features/search-listing/analytics.feature
- examples/nuxt-app/test/fixtures/landingpage/custom-collection/page.json
- examples/nuxt-app/test/fixtures/search-listing/filters/page-simple.json
- examples/nuxt-app/test/fixtures/search-listing/filters/response-large.json
- packages/ripple-tide-search/components/global/TideCustomCollection.vue
**Issue**: https://digital-vic.atlassian.net/browse/SD-544
- Add custom collection results event
- And make event label also consider location inputs
> [SD-544] custom collection results event

- packages/ripple-ui-core/src/components/related-links/RplRelatedLinks.vue
- packages/ripple-ui-core/src/components/social-share/RplSocialShare.css
- packages/ripple-ui-core/src/components/social-share/RplSocialShare.vue
**Issue**:
https://digital-vic.atlassian.net/browse/SD-692
https://digital-vic.atlassian.net/browse/SD-693
- Make related links heading a H3
- Make social share items a list
> [SD-692][SD-693] WCAG feedback

- packages/ripple-ui-core/src/styles/components/_blockquote.css
**Issue**: https://digital-vic.atlassian.net/browse/SD-691
- Use `--rpl-clr-link` token to improve contrast in graphical element
- 
- 
-
> [SD-691] Improve contrast on blockquote (WCAG)

- packages/ripple-tide-publication/components/global/TidePublication.vue
- packages/ripple-tide-publication/components/global/TidePublicationPage.vue
- packages/ripple-tide-publication/mapping/publication-page.ts
- packages/ripple-tide-publication/mapping/publication.ts
- packages/ripple-tide-publication/server/plugins/publication.ts
**Issue**:
- https://digital-vic.atlassian.net/browse/SD-624
- https://digital-vic.atlassian.net/browse/SD-628
- Added topics and tags to each template, with mapping and includes
- Added required dynamic component mapping to plugin
- 
-
> [SD-624][SD-628] Publication uplift

- packages/nuxt-ripple/app.config.ts
- packages/nuxt-ripple/assets/css/languages.css
**Issue**: https://digital-vic.atlassian.net/browse/SD-711
- Added Burmese to highlight header CSS fix (used in Arabic)
- Added Dinka font settings to map to Noto Sans (has better symbol support than VIC)
- 
-
> [SD-711] Fix two separate font issues

- packages/ripple-tide-search/components/global/TideSearchAddressLookup.vue
- packages/ripple-tide-search/components/global/TideSearchLocationAutocomplete.vue
- packages/ripple-ui-maps/src/components/map/RplMap.vue
**Issue**:
https://digital-vic.atlassian.net/browse/SD-721
https://digital-vic.atlassian.net/browse/SD-715
- Restore address lockup animation
- Fix centering issue that was caused by clicking home with a sidepanel open
> [SD-721][SD-715] map zoom animation, home centering

- packages/ripple-ui-core/src/components/button/RplButton.vue
- packages/ripple-ui-core/src/components/footer/RplFooter.vue
- packages/ripple-ui-core/src/components/layout/RplLayoutBackToTop.vue
**Issue**: https://digital-vic.atlassian.net/browse/SD-731
- Added `aria-hidden="true"` to logo
- Changed screen-hidden text in link to `aria-label`
- Added `aria-label` to back-to-top link
- 
-
> [SD-731] Aria improvements to footer logo

- examples/nuxt-app/test/features/search-listing/content.feature
- examples/nuxt-app/test/fixtures/search-listing/content/page.json
- packages/ripple-test-utils/step_definitions/content-types/landing-page.ts
- packages/ripple-test-utils/step_definitions/content-types/listing.ts
- packages/ripple-tide-search/components/TideSearchListingPage.vue
- packages/ripple-tide-search/mapping/index.ts
**Issue**: https://digital-vic.atlassian.net/browse/SD-724
- Add corner graphic support to search listings
> [SD-724] Add corner graphic support to search listings

- packages/ripple-ui-core/src/components/progress/RplProgress.css
- packages/ripple-ui-core/src/components/progress/RplProgress.vue
- Add button type so it doesn't submit by default
- Update breakpoint
- Reverse before and after so the progress line isn't pulled behind the background
> style: progress component tweaks

- packages/ripple-ui-core/src/components/stats-grid/RplStatsGrid.css
**Issue**: https://digital-vic.atlassian.net/browse/SD-695
- Need to reset default margin on `dd` (RTL picked up in automated tests shows a default margin-right)
- 
- 
-
> [SD-695] Fix regression from markup change

- examples/nuxt-app/package.json
- examples/vue-app/package.json
- package.json
- packages/ripple-test-utils/package.json
- packages/ripple-ui-core/src/components/primary-nav/RplPrimaryNav.cy.ts
- packages/ripple-ui-core/src/components/primary-nav/components/mega-menu/RplPrimaryNavMegaMenu.vue
- packages/ripple-ui-core/src/components/primary-nav/components/mega-menu/RplPrimaryNavMegaMenuAction.vue
- packages/ripple-ui-core/src/components/primary-nav/fixtures/sample.ts
- packages/ripple-ui-core/tsconfig.json
- packages/ripple-ui-core/vite.config.ts
- pnpm-lock.yaml
**Issue**: https://digital-vic.atlassian.net/browse/SD-701
- Listen for `rpl-primary-nav/toggleMenuItem` and scroll to top of megamenu - works on both desktop and mobile
- 
- Added some extra fixtures to demonstrate long menu behaviour
- Storybook
> [SD-701] Scroll to top on menu transition

- packages/ripple-tide-webform/server/api/tide/webform.ts
**Issue**: https://digital-vic.atlassian.net/browse/SD-794
- Fix form submission (when using term select)
FE: https://app.pr-1188.vic-gov-au.sdp4.sdp.vic.gov.au/submit-your-grant
BE: develop.content
> [SD-794] fix form submission (when using term select)

- packages/ripple-tide-search/components/global/TideCustomCollection.vue
- packages/ripple-tide-search/components/global/TideSearchListingResultsMap.vue
- packages/ripple-tide-search/composables/useTideSearch.ts
- packages/ripple-tide-search/types.ts
- packages/ripple-ui-core/src/components/button/RplButton.css
- packages/ripple-ui-core/src/components/button/RplButton.vue
- packages/ripple-ui-core/src/styles/utilities/_focus.css
- packages/ripple-ui-maps/src/components/layer-list/RplMapLayerList.css
- packages/ripple-ui-maps/src/components/layer-list/RplMapLayerList.cy.ts
- packages/ripple-ui-maps/src/components/layer-list/RplMapLayerList.stories.mdx
- packages/ripple-ui-maps/src/components/layer-list/RplMapLayerList.vue
- packages/ripple-ui-maps/src/components/map/RplMap.stories.mdx
- packages/ripple-ui-maps/src/components/map/RplMap.vue
- packages/ripple-ui-maps/src/components/map/utils.ts
- packages/ripple-ui-maps/src/components/popup/RplMapPopUp.css
- packages/ripple-ui-maps/src/components/popup/RplMapPopUp.vue
- packages/ripple-ui-maps/src/types.ts
**Issue**: https://digital-vic.atlassian.net/browse/SD-670
https://github.com/user-attachments/assets/ca362faa-0f69-43fd-bedc-beb59bc59f93
- Added a new component to support an interactive list of layers in maps
- Added layers props to RplMap
- Added a new variant to the popup component called 'layerlist' as they this component shares alot of styles and logic with the popups
- Added tests and stories
- Updated focus state styling to add `rpl-u-focusable-within` functionaliy to the 'outline' focus state, this was needed for the layer list images
- Adjusted the 'elevated' button style so that it could be used for the layer list
- Added ability to disable the elastic search calls for maps that don't use pins
- Integrated map layer list into the custom collection json blob
- 
-
> [SD-670] - Added RplMapLayerList UI component

- packages/ripple-ui-forms/src/components/RplFormNumber/RplFormNumber.vue
**Issue**: https://digital-vic.atlassian.net/browse/SD-729
- Conditionally added fieldset when button mode is in use
- Added descriptive audio labels for increase/decrease buttons that announce when min/max has been reached
- Storybook
-
> [SD-729] Number fieldset and descriptive labels

- packages/ripple-ui-core/src/lib/helpers.test.ts
- packages/ripple-ui-core/src/lib/helpers.ts
**Issue**: https://digital-vic.atlassian.net/browse/SD-817
- Add check to ensure date is valid before formatting, this is to avoid the site blowing up if an invalid date is supplied
> [SD-817] check that date is valid before formatting

- packages/ripple-tide-landing-page/mapping/index.ts
- packages/ripple-tide-publication/mapping/publication-page.ts
- packages/ripple-tide-publication/mapping/publication.ts
**Issue**: https://digital-vic.atlassian.net/browse/SD-617
- Corner graphic fields were mapped as per landing page, but the includes were missing
- 
- 
-
> [SD-617] Add missing header includes

- examples/nuxt-app/layers/map-features/components/global/test/TestMapResultsLink.vue
- examples/nuxt-app/test/features/maps/maps.feature
- examples/nuxt-app/test/features/site/search.feature
- examples/nuxt-app/test/fixtures/maps/basic-page.json
- packages/nuxt-ripple-analytics/lib/index.ts
- packages/ripple-test-utils/step_definitions/components/maps.ts
- packages/ripple-tide-search/components/TideSearchListingPage.vue
- packages/ripple-tide-search/components/TideSearchPage.vue
- packages/ripple-tide-search/components/TideSearchResultLink.vue
- packages/ripple-tide-search/components/global/TideCustomCollection.vue
- packages/ripple-tide-search/components/global/TideSearchListing/TideSearchListingTableLink.vue
- packages/ripple-ui-core/src/components/layout/RplPageComponent.vue
- packages/ripple-ui-core/src/composables/useEventContext.ts
- packages/ripple-ui-core/src/composables/useSlotContent.ts
- packages/ripple-ui-core/src/index.ts
**Issue**:
https://digital-vic.atlassian.net/browse/SD-545
https://digital-vic.atlassian.net/browse/SD-546
https://digital-vic.atlassian.net/browse/SD-254
- 
- 
- 
-
> [SD-545, SD-546, SD-254]  Improved analytics for search and maps

- .github/workflows/components.yml
- packages/ripple-storybook/package.json
- pnpm-lock.yaml
> Fix storybook test-runner CI error

- .github/workflows/publish.yml
> chore: set cli lib version after bumping

- packages/ripple-tide-landing-page/mapping/components/link-list/link-list-mapping.test.ts
- packages/ripple-tide-landing-page/mapping/components/link-list/link-list-mapping.ts
- packages/ripple-ui-core/src/components/link-list/RplLinkList.css
**Issue**: https://digital-vic.atlassian.net/browse/SD-866
- 
- 
- 
-
> [SD-866] - Link list UI feedback and mapping change

- packages/ripple-tide-search/composables/useLegacySuggestions.ts
- packages/ripple-tide-search/utils/rplAddressSuggestionsFn.ts
**Issue**: https://digital-vic.atlassian.net/browse/SD-872
- Adds match_phrase_prefix to location queries;
- Because this is using app search we need to use `.stem` on the phrase query https://www.elastic.co/guide/en/app-search/8.18/elasticsearch-engines-text-subfields-support-conventions.html
- Also the reported example was search for "Glen Waverley"; when searching for  "Glen W*" no results appeared, the default `max_expansions` is 50 and in this case that isn't enough to reach "Waverley", so `max_expansions` needs to be increased.
Test URLs:
- https://app.pr-496.vicpol-vic-gov-au.sdp4.sdp.vic.gov.au/police-station-location
- https://app.pr-1207.vic-gov-au.sdp4.sdp.vic.gov.au/know-your-council
- https://app.pr-1207.vic-gov-au.sdp4.sdp.vic.gov.au/find-road-safety-camera
*Updated vs …
> [SD-872] add match_phrase_prefix to location suggestion query

- packages/ripple-tide-api/src/utils/markup-transpiler/cheerio.test.ts
- packages/ripple-tide-api/src/utils/markup-transpiler/default-plugins.ts
- packages/ripple-ui-core/src/components/data-table/RplDataTable.cy.ts
- packages/ripple-ui-core/src/components/data-table/RplDataTable.vue
- packages/ripple-ui-core/src/components/data-table/RplDataTableRow.vue
- packages/ripple-ui-core/src/components/data-table/fixtures/sample.ts
**Issue**: https://digital-vic.atlassian.net/browse/SD-791
- Add scope attribute to tables
*Basic text*
*Data tables*
*Search listings*
> [SD-791] add scope attribute to tables

- packages/ripple-ui-maps/package.json
- pnpm-lock.yaml
**Issue**: https://digital-vic.atlassian.net/browse/SD-894
- Updates vue3-openlayers, ol, ol-ext and ol-contextmenu
- 
- 
-
> [SD-894] update vue3-openlayers and ol libraries

- packages/ripple-ui-core/src/components/primary-nav/components/nav-bar/RplPrimaryNavBar.vue
- Revert commit from PR #1505 (we're going to treat `<RplImg />` as essentially `<img>`)
> chore: revert RplImage tag change

- packages/ripple-test-utils/step_definitions/components/maps.ts
- packages/ripple-tide-search/components/global/TideCustomCollection.vue
- packages/ripple-tide-search/components/global/TideSearchListingResultsMap.vue
- packages/ripple-ui-maps/src/components/map/RplMap.css
- packages/ripple-ui-maps/src/components/map/RplMap.vue
**Issue**: https://digital-vic.atlassian.net/browse/SD-702
- Make map 'focusable'
- Add tab label
- And map role label and description
> [SD-702] a11y updates for maps

- packages/ripple-ui-core/src/components/primary-nav/RplPrimaryNav.css
**Issue**: https://digital-vic.atlassian.net/browse/SD-740
- 
- 
- 
-
> [SD-740] Fix focused element obscured by sticky primary nav 

- packages/ripple-ui-forms/src/components/RplFormReview/RplFormReview.css
- packages/ripple-ui-forms/src/components/RplFormReview/RplFormReview.vue
**Issue**: https://digital-vic.atlassian.net/browse/SD-915
- Update review component spacing and sizing
> [SD-915] update review component 

- packages/ripple-ui-core/src/components/progress/RplProgress.css
**Issue**: https://digital-vic.atlassian.net/browse/SD-918
- Add progress hover and active states
> [SD-918] add progress hover and active states

- examples/nuxt-app/test/features/landingpage/multistep-forms.feature
- packages/ripple-ui-forms/src/components/RplFormStep/RplFormStep.css
- packages/ripple-ui-forms/src/components/RplFormStep/RplFormStep.vue
- packages/ripple-ui-forms/src/components/RplFormSteps/RplFormSteps.css
**Issue**: https://digital-vic.atlassian.net/browse/SD-916
- Minor multistep css tweaks
> [SD-916] minor multistep css tweaks

- packages/ripple-ui-core/src/components/progress/RplProgress.css
- packages/ripple-ui-forms/src/components/RplForm/RplForm.css
- packages/ripple-ui-forms/src/components/RplFormReview/RplFormReview.css
- packages/ripple-ui-forms/src/components/RplFormStep/RplFormStep.css
- packages/ripple-ui-forms/src/components/RplFormStep/RplFormStep.vue
**Issue**: https://digital-vic.atlassian.net/browse/SD-916
- Minor multistep design updates
- Fix RplForm field spacing
> [SD-916] minor multistep design updates

- packages/ripple-ui-core/src/components/data-table/RplDataTable.css
- packages/ripple-ui-core/src/styles/components/_table.css
**Issue**: https://digital-vic.atlassian.net/browse/SD-921
- Data table feedback
> [SD-921] data table feedback

- packages/ripple-tide-search/mapping/index.ts
- packages/ripple-ui-core/src/components/data-table/RplDataTable.css
- packages/ripple-ui-forms/src/components/RplFormReview/RplFormReview.css
**Issue**: 
https://digital-vic.atlassian.net/browse/SD-915
https://digital-vic.atlassian.net/browse/SD-921
- Fix lint warning and spacing
> [SD-915][SD-921] component feedback

- packages/ripple-tide-api/src/utils/markup-transpiler/cheerio.test.ts
- packages/ripple-tide-api/src/utils/markup-transpiler/default-plugins.ts
**Issue**: https://digital-vic.atlassian.net/browse/SD-957
- Update image plugin to check for existing query string, just so we don't end up with URLs with two question marks i.e. 
`/public/Bendigo-Hospital.jpg?itok=pWg6A?width=720`
> [SD-957] update image src to check for existing query string

- packages/ripple-ui-core/src/components/primary-nav/components/nav-bar/RplPrimaryNavBar.vue
**Issue**: https://digital-vic.atlassian.net/browse/SD-951
- Add sizes to nav logos so srcset is generated correctly
> [SD-951] add sizes to nav logos

- examples/nuxt-app/test/fixtures/search-listing/filters/page-fallback-values.json
- examples/nuxt-app/test/fixtures/search-listing/filters/request-fallback-values.json
- packages/ripple-tide-search/composables/useTideSearch.ts
**Issue**: https://digital-vic.atlassian.net/browse/SD-991
- Update fallback value check to take into account more complex fields like date range i.e. objects
> [SD-991] update fallback value check

- packages/ripple-tide-search/composables/useTideSearch.ts
- packages/ripple-tide-search/mapping/__test__/data/expected-listing-data-ui-auto-site.ts
- packages/ripple-tide-search/mapping/__test__/data/index.ts
- packages/ripple-tide-search/mapping/__test__/data/test-listing-data-ui-auto-site.ts
- packages/ripple-tide-search/mapping/__test__/getProcessedSearchListingConfig.test.ts
- packages/ripple-tide-search/mapping/utils/index.ts
- packages/ripple-tide-search/types.ts
…o search listings
**Issue**: https://digital-vic.atlassian.net/browse/SD-900
- 
- 
- 
-
> [SD-900] Automatically filter search listing by current site

- packages/ripple-tide-api/package.json
- packages/ripple-ui-core/package.json
- packages/ripple-ui-forms/package.json
- packages/ripple-ui-maps/package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
**Issue**:
- Unify nuxt namespace deps in catalog
- 
- 
-
> chore: :wrench: move nuxt/kit and nuxt/schema to catalog

- packages/ripple-tide-webform/composables/use-webform-submit.ts
**Issue**:
- Adds form submission hooks to be able to modify the form submission before posting. 
- 
- See https://github.com/dpc-sdp/vicpol-vic-gov-au/pull/503
-
> [SPE-341] Adds form submission hooks

- packages/ripple-ui-forms/package.json
- packages/ripple-ui-forms/vite.config.ts
- pnpm-lock.yaml
**Issue**: https://digital-vic.atlassian.net/browse/SD-1068
- Moved from devDeps to deps
- Added to `rollupOptions.external` in vite config
- 
-
> [SD-1068] Fix external datepicker import

- packages/ripple-tide-landing-page/mapping/components/media-gallery/media-gallery-mapping.ts
- packages/ripple-ui-core/src/components/media-embed/RplMediaEmbed.stories.ts
- packages/ripple-ui-core/src/components/media-embed/RplMediaEmbed.vue
- packages/ripple-ui-core/src/components/media-embed/constants.ts
- packages/ripple-ui-core/src/components/media-gallery/RplMediaGallery.css
- packages/ripple-ui-core/src/components/media-gallery/RplMediaGallery.stories.ts
- packages/ripple-ui-core/src/components/media-gallery/RplMediaGallery.vue
- packages/ripple-ui-core/src/styles/components/_embed.css
**Issue**: https://digital-vic.atlassian.net/browse/SD-1018
- Update design of Media Embed and Image Gallery components to include the new 'with background' version
> [SD-1018] Update design of Media Embed and Image Gallery components

- examples/nuxt-app/test/features/site/feature-flags.feature
- examples/nuxt-app/test/features/site/shared-elements.feature
- examples/nuxt-app/test/fixtures/site/primary-nav-wrap.json
- packages/nuxt-ripple/components/TideBaseLayout.vue
- packages/nuxt-ripple/components/TidePrimaryNav.vue
- packages/ripple-test-utils/step_definitions/common/navigation.ts
- packages/ripple-test-utils/step_definitions/common/shared-elements.ts
- packages/ripple-tide-api/types.d.ts
- packages/ripple-ui-core/src/components/primary-nav/RplPrimaryNav.css
- packages/ripple-ui-core/src/components/primary-nav/RplPrimaryNav.stories.ts
**Issue**: https://digital-vic.atlassian.net/browse/SD-1146
- Add feature flag to enable primary nav login button
> [SD-1146] add feature flag for primary nav login
