- _templates/content-type/new/cy.feature.t
- _templates/content-type/new/cy.ts.t
- _templates/content-type/new/fixture.json.t
- _templates/content-type/new/index.ts.t
- _templates/content-type/new/index.vue.t
- _templates/content-type/new/nuxt.ts.t
- _templates/content-type/new/package.json.t
- _templates/content-type/new/stories.mdx.t
- _templates/content-type/new/tide-header.vue.t
- _templates/content-type/new/types.d.ts.t
- examples/nuxt-app/test/features/site/theme.feature
- Add storybook, layout, sample wrapper component to hygen templates for creating a new content type
These updates build out a working SFC in the content type module, and demonstrate the patterns for:
- Mapping fields to props
- Defining prop interfaces
- Wrapping components
And you get a nice shiny page to start with, the only manual step is adding the module in config on the nuxt app.
**UPDATE**
- Sidebar components default to `false` in mapping (can't be guaranteed that the data exists)
- Scaffold for cypress tests, cucumber and fixture added to hygen templates
> Add to content type templates

- examples/nuxt-app/nuxt.config.ts
- packages/ripple-tide-api/src/mapping/site.ts
- packages/ripple-tide-api/src/nuxt.ts
- packages/ripple-tide-api/src/nuxt/components/Page.vue
- packages/ripple-tide-api/src/services/lib/site-menu.ts
**Issue**:
- Moved default mapping to ripple-tide-api - want to minimise the config in client sites. I think this will eventually go into ripple-tide-core module
- BREAKING! - Moved CONTENT_API_SERVER to NUXT_PUBLIC_TIDE_CONTENT_API_BASE_URL so it can be set via public runtimeConfig. This allows the ability to change backends without rebuilding the app, only need to restart pods
- Same SITEID, becomes configurable via NUXT_PUBLIC_TIDE_CONTENT_API_SITE env var
- Menus should populate in nuxt-app
- Setting NUXT_PUBLIC_TIDE_CONTENT_API_BASE_URL in .env should update Tide server
> Wire up Primary nav menu and footer menus

- .circleci/config.yml
**Issue**:
- Adds step in CI to update reference site after successful publish to NPM
- 
- Can't be tested in PR
- On merge to develop - update-v2 pipeline should kick off https://app.circleci.com/pipelines/github/dpc-sdp/reference-sdp-vic-gov-au/119/workflows/8a0484bc-4f11-49a9-a7b5-1e8020fe1618
> ci: add step to update reference site after publish to npm

- packages/ripple-tide-api/src/nuxt/components/BaseLayout.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-142
- add margin to topic tags (same margin as updated date)
> [R20-142] add margin to topic tags

- packages/ripple-tide-api/src/nuxt/components/BaseLayout.vue
- packages/ripple-tide-api/src/nuxt/components/ErrorPage.vue
- packages/ripple-ui-core/src/components/error-message/error-message.css
- packages/ripple-ui-core/src/components/layout/layout.css
- packages/ripple-ui-core/src/components/layout/layout.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-295
- Fix graphic position
- A v-if for topics wrapper
- Use non concatenated format for error css, update spacing values
- Add main container wrapper (as discussed)
- Use hasSidebar in aside v-if aside
> feat(@dpc-sdp/ripple-ui-core): Graphic fix, empty slot checks

- packages/ripple-tide-api/package.json
> fix: remove nuxt.js export from ripple-tide-api

- package.json
- lerna clears out all `dist` before building, but seems like it was trying to build `ripple-storybook` before `ripple-ui-core` was built. It doesn't need to happen here anyway, the static build is only needed for testing and chromatic, and is included in those steps.
- `pnpm build`
> build: :wrench: ignore storybook build in build-all

- packages/nuxt-ripple/components/TideBaseLayout.vue
- packages/nuxt-ripple/package.json
- packages/ripple-tide-landing-page/components/global/TideLandingPage/ContentCollection.vue
- pnpm-lock.yaml
**Issue**: https://digital-vic.atlassian.net/browse/R20-357
- use alwaysSearchOnInitialLoad instead of mounted for consistency with search
- drop-in more modern ts version of deepmerge
> [R20-519] use alwaysSearchOnInitialLoad instead of mounted

- packages/ripple-ui-core/src/components/timeline/RplTimeline.css
- packages/ripple-ui-core/src/components/timeline/RplTimeline.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-566
- Allow for a single timeline element to be displayed
> fix(@dpc-sdp/ripple-ui-core): allow a single timeline element

- packages/ripple-ui-core/src/components/media-embed/RplMediaEmbed.vue
- packages/ripple-ui-core/src/components/media-gallery/RplMediaGallery.vue
- packages/ripple-ui-core/src/components/modal/RplModal.css
- packages/ripple-ui-core/src/components/modal/RplModal.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-586
-  fix modal height for mobile (support wasn't quite good enough dvh)
- and gallery image sizing for safari
> [R20-586] fix modal height for mobile and gallery size for safari

- docs/components/app/AppNavbar.vue
- examples/nuxt-app/test/features/landingpage/forms.feature
- examples/nuxt-app/test/features/landingpage/home.feature
- packages/nuxt-ripple/components/TideContentPage.vue
- packages/nuxt-ripple/components/TideContentRating.vue
- packages/nuxt-ripple/components/global/RplLink.vue
- packages/ripple-storybook/.storybook/preview.js
- packages/ripple-ui-core/src/components.ts
- packages/ripple-ui-core/src/components/card/RplPromoCard.vue
- packages/ripple-ui-core/src/components/chip/RplChip.vue
- packages/ripple-ui-core/src/components/footer/RplFooter.vue
- packages/ripple-ui-core/src/components/link/RplLink.vue
- packages/ripple-ui-core/src/components/modal/RplModal.vue
- packages/ripple-ui-core/src/components/primary-nav/RplPrimaryNav.vue
- packages/ripple-ui-core/src/components/primary-nav/components/mega-menu/RplPrimaryNavMegaMenuAction.vue
- packages/ripple-ui-core/src/components/primary-nav/components/mega-menu/RplPrimaryNavMegaMenuList.vue
- packages/ripple-ui-core/src/components/primary-nav/components/nav-bar/RplPrimaryNavBar.vue
- packages/ripple-ui-core/src/components/text-link/RplTextLink.vue
- packages/ripple-ui-core/src/components/vertical-nav/RplVerticalNavLink.vue
- packages/ripple-ui-core/src/composables/useAccessibleContainer.ts
**Issue**: R20-759
- Added RplLink as a placeholder that can be replaced with NuxtLink etc.
- Used RplLink wherever a plain anchor tag was used
- Fixed 404 page not appearing on client side navigation
- Fixed some event listeners and classes not being cleaned up properly on client side navigation
- 
-
> [R20-759] Stopped all links are forcing a full refresh instead of using client side navigation

- packages/ripple-tide-api/src/utils/markup-transpiler/default-plugins.ts
- packages/ripple-ui-core/src/components/media-embed/RplMediaEmbed.vue
> [R20-776] fix(@dpc-sdp/ripple-ui-core): changed 'view transcript' to open in same window

- packages/nuxt-ripple/app.vue
- packages/nuxt-ripple/components/TideBaseLayout.vue
- packages/nuxt-ripple/utils/hideAlertsOnLoadScript.ts
**Issue**:
- The script wasn't getting included in the reference site because it was providing its own `app.vue`
- Moved to TideBaseLayout
- Removed global flag from guid regex causing every second alert not to be hidden
- 
-
> fix(nuxt-ripple): moved alert script to base layout and fixed regex issue

- docs/components/content/DocsImageExample.vue
- docs/content/design-system/Kitchen sink.md
used for making static images look like component examples
**Issue**:
- 
- 
- 
-
> feat(docs): added DocsImageExample to docs site

- packages/nuxt-ripple/composables/use-tide-page.ts
**Issue**:
- Setting `pageData.value = null` was actually updating the cache, which meant that when we called `useFetch` again, nuxt was not calling the API again, but instead served up what it thought was the cached value (which was null, which caused the page to be blank
- This happened intermittently because it was only happening when the nuxt cache was older than 5 minutes
- The crashes will stop happening once you get a cache miss in section, and therefore a new _fetched timestamp in the nuxt cache. After 5 minutes the crashes start again.
- 
-
> fix(@dpc-sdp/nuxt-ripple): fixed intermittent crash caused by nuxt cache reactivity set to null

- packages/ripple-ui-core/src/components/expandable/RplExpandable.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-811
- Make sure expanded content is always visible, i.e. when screen size changes or device is rotated and when inner elements break outside of the expanded container.
> [R20-811] make sure expanded content is visible

- packages/ripple-tide-api/src/utils/mapping-utils.ts
- packages/ripple-tide-landing-page/components/global/TideLandingPage/PromoCard.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-846
- Use highlight for promo cards when no image is supplied
> [R20-846] use highlight for promo cards

- examples/nuxt-app/app.config.ts
- packages/nuxt-ripple/components/TideBaseLayout.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-737
- Theme vars were using `body` but token vars are on `:root`
- It actually needs to be on both, or there's a visible flash on "un-themed" content while the page loads
- nuxt-app
- Will need to update the app config on reference to confirm
> [R20-737] Use same namespace for theme vars

- packages/ripple-ui-core/src/components/primary-nav/RplPrimaryNav.vue
- packages/ripple-ui-core/src/components/primary-nav/components/mega-menu/RplPrimaryNavMegaMenu.vue
- packages/ripple-ui-core/src/components/primary-nav/components/mega-menu/RplPrimaryNavMegaMenuAction.vue
- packages/ripple-ui-core/src/components/primary-nav/components/mega-menu/RplPrimaryNavMegaMenuHomeButton.vue
- packages/ripple-ui-core/src/components/primary-nav/components/mega-menu/RplPrimaryNavMegaMenuList.vue
- packages/ripple-ui-core/src/components/primary-nav/components/nav-bar/RplPrimaryNavBar.vue
- packages/ripple-ui-core/src/components/primary-nav/components/nav-bar/RplPrimaryNavBarAction.vue
- packages/ripple-ui-core/src/components/primary-nav/components/quick-exit/RplPrimaryNavQuickExit.vue
- packages/ripple-ui-core/src/components/primary-nav/constants.ts
- packages/ripple-ui-core/src/components/primary-nav/fixtures/sample.ts
- packages/ripple-ui-core/src/composables/usePrimaryNavFocus.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-855
- Add basic tab support to our primary nav
Our primary nav isn't nested at all so we don't get tabbing for free, we may want to restructure the nav in the future so the markup is nested.
> [R20-855] add tab support for primary nav

- packages/ripple-tide-api/src/utils/markup-transpiler/default-plugins.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-911
- Update cheerio plugin to specify image where there are multiple in the same markup block
- 
- 
-
> [R20-911] Use selected image if there are multiple in rpl-content

- examples/nuxt-app/app.config.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-737
- Just noting it here, as this will be needed in new site themes as well (copied from jira):
> It looks like when we override values for theming, the inherited properties are not passed on eg.
>
>```--rpl-clr-type-light: var(--rpl-clr-light);```
>
> If we change `--rpl-clr-light` then `--rpl-clr-type-light` doesn’t automatically get the new value. This isn’t a big deal, it can just be redefined in the theme, we just need to remember to do it (document / add to default config).
- Updated in nuxt-app
- 
-
> [R20-737] Redefine token-set props in theme

- packages/ripple-ui-core/src/components/primary-nav/components/mega-menu/RplPrimaryNavMegaMenuList.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-932
- Display level 4 nav items that have children as links rather than menu buttons
- 
- 
-
> fix(@dpc-sdp/ripple-ui-core): fixed level 4 nav links with children not being clickable

- packages/nuxt-ripple/server/api/tide/webform_submission/[...].ts
- packages/nuxt-ripple/server/routes/sitemap.xml.ts
- packages/ripple-tide-landing-page/components/global/TideLandingPage/SearchBanner.vue
- packages/ripple-tide-search/components/TideSearchPage.vue
- packages/ripple-tide-search/server/api/tide/search/[...].ts
- Just getting rid of some linter warnings about unused imports
> chore(@dpc-sdp/nuxt-ripple): clean up linter warnings

- packages/ripple-tide-event/components/TideEventOverview.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-960
- Only show event details that have content
> fix(@dpc-sdp/ripple-tide-event): only show details with descriptions

- packages/ripple-tide-api/types.d.ts
- packages/ripple-ui-core/src/components/card/RplPromoCard.vue
> [R20-943] - Added hidePromoCardStripe feature flag to toggle promo card rainbow

- packages/ripple-ui-core/src/styles/components/_table.css
**Issue**:https://digital-vic.atlassian.net/browse/R20-953
- The designs for tables have smaller text than the rest of the wysiwyg content
- 
- 
-
> fix(@dpc-sdp/ripple-ui-core): fixed table font size for paragraphs and lists

- packages/ripple-ui-core/src/components/vertical-nav/RplVerticalNav.vue
- packages/ripple-ui-core/src/components/vertical-nav/RplVerticalNavChildList.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-952
- 
- 
- 
-
> [R20-952] RplVerticalNav - fixed parents of active item being highlighted

- packages/nuxt-ripple/components/TideBaseLayout.vue
- packages/nuxt-ripple/components/TideBreadcrumbs.vue
- packages/ripple-tide-publication/components/global/TidePublication.vue
- packages/ripple-tide-publication/components/global/TidePublicationPage.vue
- packages/ripple-tide-publication/pages/[...slug]/print-all.vue
- packages/ripple-ui-core/src/components/breadcrumbs/RplBreadcrumbs.css
- packages/ripple-ui-core/src/components/breadcrumbs/RplBreadcrumbs.vue
- packages/ripple-ui-core/src/components/primary-nav/RplPrimaryNav.css
- packages/ripple-ui-core/src/components/primary-nav/RplPrimaryNav.vue
- packages/ripple-ui-core/src/components/primary-nav/components/quick-exit/RplPrimaryNavQuickExit.css
- packages/ripple-ui-core/src/components/primary-nav/components/quick-exit/RplPrimaryNavQuickExit.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-775
- Add persistant quick exit to nav, in the same vein as the header taking a prop to say if it's behind a breakcrumbs this adds a prop to breadcrumbs to say it's it's beside a quick exit.
> [R20-775] persistant quick exit

- packages/ripple-tide-landing-page/components/global/TideLandingPage/MediaEmbed.vue
- packages/ripple-tide-landing-page/mapping/components/complex-image/complex-image-mapping.test.ts
- packages/ripple-tide-landing-page/mapping/components/complex-image/complex-image-mapping.ts
- packages/ripple-ui-core/src/components/media-embed/RplMediaEmbed.vue
- packages/ripple-ui-core/src/styles/components/_embed.css
**Issue**: https://digital-vic.atlassian.net/browse/R20-842
- Add support for labels in the media embed component (to match existing ripple 1 support)
- Fix icon alignment and 'button' display
> [R20-842] complex image labels

- packages/ripple-tide-api/src/utils/normaliseImageUrl.ts
> fix(@dpc-sdp/ripple-tide-api): fixed normaliseImageUrl crashing app if run without env vars

- packages/nuxt-ripple/composables/use-tide-page.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-292
- On reference site, cookies don't get automatically passed through to the backend when the page is server rendered
- See here for a similar issue https://github.com/nuxt/nuxt/issues/13096
- 
-
> fix(nuxt-ripple): ensure access token is passed through to API on SSR

- packages/ripple-tide-landing-page/mapping/components/webforms/webforms-mapping.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-839
- Allow typing past max values, this brings the experience inline with other validation methods. 
Minlength did nothing anyway as we're using novaldate, and max just blocked user interaction with no explanation as to why.
> [R20-839] remove native min-max from mapping

- docs/components/app/AppLayout.vue
- docs/layouts/home.vue
- packages/ripple-ui-core/src/components/alert/RplAlert.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-1063
- 
- 
- 
-
> docs(docs): added alert directing users to old storybook

- packages/ripple-tide-api/src/index.ts
- packages/ripple-tide-api/src/utils/createHandler.ts
- packages/ripple-tide-publication/server/api/tide/publication-index.ts
- Attempting to cleanup server build warnings
This does remove the warnings that relate to `createHandler`, but the `useNitroApp` warnings still remain https://github.com/nuxt/nuxt/issues/18789
> [R20-1050] cleanup warnings on server build

- packages/nuxt-ripple/components/TideContentPage.vue
- The pascal case function we use converts `det_150_content` to `Det_150Content` by default, but we need it to be `Det150Content`
> fix(@dpc-sdp/nuxt-ripple): correctly case content types with numbers

- packages/ripple-tide-api/src/services/tide-page.ts
- packages/ripple-tide-landing-page/components/global/TideLandingPage/ContentCollection.vue
- packages/ripple-tide-landing-page/mapping/components/content-collection/content-collection-mapping.test.ts
- packages/ripple-tide-landing-page/mapping/components/content-collection/content-collection-mapping.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-1234
- Include current site ID in search filters, fix filter type
> [R20-1234] include current site ID in search filters

- packages/nuxt-ripple/mapping/site/index.ts
- packages/nuxt-ripple/types.d.ts
- packages/ripple-tide-landing-page/components/global/TideLandingPage.vue
- packages/ripple-tide-landing-page/components/global/TideLandingPage/HeroHeader.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-1274
- Add site wide corner graphics
> [R20-1274] site wide corner graphics

- examples/nuxt-app/test/fixtures/search-listing/aggregations/request.json
- examples/nuxt-app/test/fixtures/search-listing/table/request.json
- packages/ripple-test-utils/step_definitions/common/mocks.ts
- packages/ripple-test-utils/step_definitions/content-types/listing.ts
- packages/ripple-tide-grant/components/global/TideGrantSearchResult.vue
- packages/ripple-tide-landing-page/mapping/hero-header/hero-header-mapping.ts
- packages/ripple-tide-search/components/TideSearchListingPage.vue
- packages/ripple-tide-search/components/global/TideSearchResult.vue
- packages/ripple-tide-search/components/global/TideSearchResultCard.vue
- packages/ripple-tide-search/components/global/TideSearchResultsGrid.vue
- packages/ripple-tide-search/components/global/TideSearchResultsList.vue
- packages/ripple-tide-search/components/global/TideTideSearchListing.vue
- packages/ripple-tide-search/composables/useSearchResult.ts
- packages/ripple-tide-search/composables/useTideSearch.ts
- packages/ripple-tide-search/mapping/index.ts
- packages/ripple-tide-search/types.ts
- packages/ripple-tide-search/utils/search.ts
**Issue**:
- changed elastic aggregations to only fetch once on mount, to avoid weird behaviour when apply filters/searching
- removed outdated todo
- moved summary and image fields into useSearchResult composable for better reuse between result components
- added truncation for summary field - 150 characters as specced
- fixed intro text not showing for search listing
- 
-
> [R20-935] Honour roll listing support

- packages/nuxt-ripple/composables/use-tide-language.ts
- Add optional chaining to page.meta as sometimes it won't exist
> feat(@dpc-sdp/nuxt-ripple): fix error when page meta isn't set

- packages/ripple-ui-core/src/styles/components/_img.css
**Issue**: https://digital-vic.atlassian.net/browse/R20-1307
- Stop images within wysiwygs being 100% wide by default
> [R20-1307] wysiwyg image widths

- packages/ripple-ui-core/src/components/content/RplContent.css
**Issue**: https://digital-vic.atlassian.net/browse/R20-1341
- To match Ripple 1 we now allow media elements and tables to span full width, instead of being capped to the max-content-width of 615px
> [R20-1341] allow media and tables to span full width

- packages/ripple-ui-forms/src/components/RplForm/RplForm.css
**Issue**: https://digital-vic.atlassian.net/browse/R20-1222
- Add min-width to fieldsets, this fixes overflowing dropdowns
> [R20-1222] fix for overflowing dropdown content

- packages/ripple-ui-core/src/components/header/RplHeader.vue
- packages/ripple-ui-core/src/components/header/RplHeroHeader.vue
- packages/ripple-ui-core/src/components/header/RplIntroHeader.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-1425
- Make header content 10 cols when no 'sidebar' exists
> [R20-1425] allow wider header content 

- packages/nuxt-ripple-analytics/lib/tracker.ts
Send value's to the dataLayer as undefined if not in use, previously we just sent the 'in-use' values i.e. if a search page wasn't using filters we wouldn't include the filters key. However this is causing issues see JF comment below for context.
_"Because of how GTM reads from the dataLayer, if it does not find a property in the most recent dataLayer event, it will look for it going back through the array (basically it flattens all the items into a single model it reads from)  but this causes issues where values from previous DL events end up in the current GA4 event - which we don’t want. So whenever one of the params is not being used, could you please still include it but set its value to undefined (the native undefined, not a string) ."_
> fix(@dpc-sdp/nuxt-ripple-analytics): send all values to dataLayer

- packages/nuxt-ripple/components/TideSidebarSocialShare.vue
- packages/nuxt-ripple/composables/use-tide-page-meta.ts
- packages/ripple-ui-core/src/components/social-share/RplSocialShare.stories.mdx
- packages/ripple-ui-core/src/components/social-share/RplSocialShare.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-1322
- `RplSocialShare` is now just presentational, it will use whatever url is provided
- Set origin and path at caller, already set in `nuxt-ripple` (url is hard coded in storybook story)
- 
-
> [R20-1322] Move social share url concern to caller

- packages/nuxt-ripple-analytics/plugins/analytics.ts
- packages/ripple-tide-api/types.d.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-1445
- Allow setting a custom GTM container per site via the CMS
> [R20-1445] add per site GTM support

- packages/nuxt-ripple/app.vue
- packages/nuxt-ripple/components/TideLoadingIndicator.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-1463
- Nuxt recently made a change (https://github.com/nuxt/nuxt/pull/21656) that meant the loading indicator no-longer works for us, so this adds our own TideLoadingIndicator
> [R20-1463] add custom loading indicator

- packages/ripple-tide-publication/components/TidePublicationChapterCard.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-1480
- Publication index nav cards are marked up as a `ul`, so use an `li` for the card element
- 
- 
-
> [R20-1480] Use li for card element

- examples/nuxt-app/test/features/site/theme.feature
- examples/nuxt-app/test/fixtures/site/disable-vic-logo.json
- packages/ripple-test-utils/step_definitions/common/site/theme.ts
- packages/ripple-ui-core/src/components/primary-nav/components/nav-bar/RplPrimaryNavBar.vue
**Issue**:
- 
- Fix divider showing when vic logo disabled
- 
-
> fix(@dpc-sdp/ripple-ui-core): fix divider displaying when no cobrand

- packages/nuxt-ripple/nuxt.config.ts
**Issue**:
- Ensure that global css is loaded in correct order in build mode
- Workaround as per https://github.com/nuxt/nuxt/issues/21784
- `/tav2-navigation-multiple-internal-links-landing-page-fixture` from demo_content
-
> fix(nuxt-ripple): :bug: fix css load order on build

- examples/nuxt-app/test/features/landingpage/home.feature
- examples/nuxt-app/test/features/landingpage/sidebar.feature
- examples/nuxt-app/test/fixtures/landingpage/sub.json
- packages/nuxt-ripple/components/TideSidebarContactUs.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-1311
- Add whitelist of known BE options to `TideSidebarContactUs` icons, with default of `icon-browser`
- Move sidebar out to its own feature in cypress
- 
-
> [R20-1311] Whitelist contact icons

- packages/nuxt-ripple-analytics/lib/routeChange.ts
- packages/nuxt-ripple-analytics/plugins/analytics.ts
- packages/nuxt-ripple/nuxt.config.ts
- Set isProduction flag as part of runtime config
_See production=true in client side analytics events (when LAGOON_ENVIRONMENT_TYPE===production)_
> fix faulty isProduction check

- packages/ripple-ui-core/src/components/primary-nav/components/nav-bar/RplPrimaryNavBar.vue
**Issue**:
- If print logo is defined in BE, display the primary logo for print (this will be a default in cases where the logo is dark-on-light)
- 
- 
-
> RplPrimaryNavBar: use src if printSrc is not supplied

- packages/nuxt-ripple-analytics/lib/routeChange.ts
- packages/nuxt-ripple-analytics/lib/tracker.ts
- packages/nuxt-ripple-analytics/plugins/analytics.ts
- packages/nuxt-ripple/error.vue
- packages/nuxt-ripple/types.d.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-1511
-  Use new tide hook for dataLayer events so DL event includes 404 pages
> [R20-1511] add dataLayer event for error pages

- packages/ripple-ui-core/src/components/search-bar/RplSearchBar.css
- packages/ripple-ui-core/src/components/search-bar/RplSearchBar.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-1329
- added optional no results message for search bar suggestions. This allows it to display a message where there is a term entered but no suggestions. Needed for Know your council 
- 
- 
-
> [R20-1329] add optional noresults message to search bar

- packages/ripple-ui-core/src/components/content/RplContent.stories.mdx
- Add max width to scrollable table story
> fix(@dpc-sdp/ripple-ui-core): add max width to scrollable table story

- packages/ripple-ui-core/src/components/result-listing/RplResultListing.stories.mdx
- packages/ripple-ui-core/src/components/result-listing/RplSearchResult.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-1165
- In buying for vic search listing, the 'updated' date is actually the published date.
- 
- 
-
> feat(@dpc-sdp/ripple-ui-core): made search result date label customisable

- packages/ripple-tide-landing-page/mapping/components/webforms/webform-validation.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-1426
- Infer counter type as API doesn't always return it
The Drupal API doesn't return default values, this means when a text field has the counter type under form validation set to 'characters' the frontend doesn't actually get informed of that, so validation doesn't work as one might expect. This probably needs a more in depth review, but this small update at least results in a more expected behavior for now. 
- _No counter type is returned when counter type is set to characters_
- _Here's the before and after of this update_
> [R20-1426] infer counter type

- .github/workflows/publish.yml
- package.json
**Issue**:
- Make NPM publish step come from GH Release instead of merge to main
- 
- 
-
> chore: :rocket: change publish process to be on release

- packages/ripple-ui-core/src/components/result-listing/RplSearchResult.css
- packages/ripple-ui-core/src/components/result-listing/RplSearchResult.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-1440
A couple of issue were brought up on the above ticket (and in discussion), with the desired outcome to be as follows:
- The mouse pointer should only be shown when hovering over the actual link which is the title (and the text shouldn't be clickable). This would avoid the confusion caused when focusing a result item, then hovering another result and not seeing the wrong URL preview shown 
This change addresses that issue i.e now the title and URL are the only elements that are clickable; having said that I'm not sold this, technically all our cards have the same 'issue'.
> [R20-1440] make only title and url 'links'

- docs/content/design-system/5.components/card.md
- docs/content/framework/1.index.md
- docs/content/framework/2.key-concepts/4.content-types.md
- docs/content/framework/3.guides/1.migrating.md
- docs/nuxt.config.ts
**Issue**:
- Changed the theme for card highlight that we use in docs site, vic.gov.au doesn't use the highlight and content people got confused.
- 
- Check docs site
-
> docs(docs): :memo: use different theme for card highlight as vic gov is wrong

- packages/ripple-ui-core/README.md
- packages/ripple-ui-core/src/components/icon/RplIcon.vue
- packages/ripple-ui-core/src/nuxt/index.ts
- packages/ripple-ui-core/src/nuxt/lib/icons.ts
- packages/ripple-ui-core/src/nuxt/runtime/plugin.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-1383
Allow for sites and layers to supply custom icons that can by used with `<RplIcon>`.
The default icon path is set `iconPath: 'assets/icons'`, so any icons added within `assets/icons` within layers or the main app can then be used as per normal `<RplIcon name="my-custom-icon" />`. You can also override core icons just by popping an icon with the same name in the `assets/icons` folder.
> [R20-1383] allow supplying custom rpl icons

- packages/nuxt-ripple/plugins/social-meta.ts
**Issue**:
- Exclude `rel="canonical"` from metatag overrides (the BE API is passing through an incorrect value by default)
- 
- 
-
> fix(nuxt-ripple): :bug: exclude metatag canonical

- packages/ripple-ui-core/src/components/description-list/RplDescriptionList.css
- packages/ripple-ui-core/src/components/description-list/RplDescriptionList.stories.mdx
- packages/ripple-ui-core/src/components/description-list/RplDescriptionList.vue
- packages/ripple-ui-core/src/components/description-list/RplDescriptionListItem.vue
- packages/ripple-ui-core/src/components/description-list/constants.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-1531
- adds support for icons in description lists
> [R20-1531] add support for icons in description lists

- packages/ripple-tide-search/components/TideSearchListingPage.vue
- packages/ripple-tide-search/components/TideSearchPage.vue
- packages/ripple-ui-core/src/components/search-bar/RplSearchBarRefine.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-1528
- 
- 
- 
-
> fix(@dpc-sdp/ripple-tide-search): added missing aria-expanded to search filter toggle

- examples/nuxt-app/test/fixtures/landingpage/custom-collection.json
- packages/ripple-tide-search/components/TideSearchAboveResults.vue
- packages/ripple-tide-search/components/TideSearchListingPage.vue
- packages/ripple-tide-search/components/TideSearchPagination.vue
- packages/ripple-tide-search/components/TideSearchResultsLoadingState.vue
- packages/ripple-tide-search/components/TideSearchSortOptions.vue
- packages/ripple-tide-search/components/global/TideCustomCollection.vue
- packages/ripple-tide-search/components/global/TideSearchResultsTable.vue
- packages/ripple-tide-search/mapping/components/custom-collection/custom-collection-mapping.ts
**Issue**:
- added sort dropdown to custom collection
- added loading state for custom collection
- tidied up error display for both search listing and custom collection
- fixed custom collection scroll to top bug
- 
-
> feat(@dpc-sdp/ripple-tide-search): added sort dropdown to custom collection

- packages/ripple-tide-api/src/services/lib/site-menu.ts
- packages/ripple-tide-api/src/services/tide-api-base.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-1522
- increase menu query depth so breadcrumbs work on deeply nested pages
- added `?` to menu URL generation as I noticed when testing this against legalaid (develop) some deeply nested items don't actually have a URL
> [R20-1522] increase menu depth for breadcrumbs

- packages/nuxt-ripple/composables/use-tide-page.ts
- packages/nuxt-ripple/server/api/tide/page.ts
- packages/ripple-tide-api/src/services/__test__/tide-api-base.test.ts
- packages/ripple-tide-api/src/services/http-client.ts
- packages/ripple-tide-api/src/services/tide-api-base.ts
- packages/ripple-tide-api/src/services/tide-page.ts
- packages/ripple-tide-api/src/services/tide-site.ts
- packages/ripple-tide-publication/server/api/tide/publication-index.ts
**Issue**:
- Refactored the base api `get()` method to not swallow up the request headers, instead it now returns an object with: 
```
{
data: <the response previously returned>,
headers: <request headers which used to be lost>
}
```
- Refactored anywhere the `get()` method was called to handle the updated return value
- Set the `section-cache-tags` response header for the page api handler 
- Set the `section-cache-tags` response header for the server rendered page
- 
-
> Set section-cache-tags respone header for pages

- packages/ripple-tide-landing-page/mapping/index.ts
- packages/ripple-tide-search/components/TideSearchListingPage.vue
- packages/ripple-tide-search/mapping/index.ts
- packages/ripple-tide-search/package.json
- pnpm-lock.yaml
**Issue**: https://digital-vic.atlassian.net/browse/R20-1544
- Exported secondary campaign mapping, includes, interface from `ripple-tide-landing-page`
- Added secondary campaign mapping, includes, interface to `ripple-tide-search` search listing
- Used https://nginx-php.pr-333.content-reference-sdp-vic-gov-au.sdp4.sdp.vic.gov.au/ to set up a test listing (the search engine env didn't work on local, but the rest of the search listing template renders)
-
> [R20-1544] Add secondary campaign to search listing

- examples/nuxt-app/test/features/publication-page/publication-page.feature
- examples/nuxt-app/test/fixtures/publication-page/sample-publication-page.json
- packages/ripple-test-utils/step_definitions/content-types/publication.ts
- packages/ripple-tide-publication/mapping/publication-page.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-1553
- Changed props at mapping to use page title in description, and force "Next/Previous" for title
- Added integration test
- Cypress
-
> [R20-1553] Change page link props at mapping

- packages/nuxt-ripple/composables/use-tide-language.ts
**Issue**:
- After the custom font change, the language css selector was no longer specific enough to override the fonts
- 
- 
-
> fix(@dpc-sdp/nuxt-ripple): ensured that language specific fonts override all other fonts

- packages/ripple-ui-core/src/components/header/RplHeaderLinks.css
- packages/ripple-ui-core/src/components/header/RplHeroHeader.stories.mdx
**Issue**: https://digital-vic.atlassian.net/browse/R20-1565
- Add negative offset to prevent hanging icon
- Update storybook to use current (faulty) production data
- 
-
> [R20-1565] Prevent hanging icon in header journey links

- packages/ripple-ui-core/src/styles/utilities/_typography.css
- packages/ripple-ui-core/stories/typography.stories.mdx
**Issue**: https://digital-vic.atlassian.net/jira/software/c/projects/R20/issues/R20-1579
- Revert #824
- Add separate util class `.rpl-u-hyphenate` to retain functionality
- Storybook
- Nuxt-app
> [R20-1579] Revert hyphenation to titles

- packages/ripple-ui-core/src/components/header/RplHeaderActions.vue
> [R20-1586] add check for secondary link in header with CTA

- packages/nuxt-ripple/mapping/site/alerts/site-alerts-mapping.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-1585
- The site API call is returning incomplete alert nodes if they are associated via primary site ID, but _not_ site ID
- Our API firehose `_src` clearly shows these nodes, but linking direct to the BE API source does not
- For now, just filtering out any incomplete alert node to prevent the site from exploding (it really shouldn't), but will need to figure out why we're seeing those records in the first place
- 
-
> [R20-1585] Filter out alerts with missing type relation

- packages/ripple-tide-landing-page/components/global/TideLandingPage/CardCarousel.vue
- packages/ripple-tide-landing-page/mapping/components/card-carousel/card-carousel-mapping.ts
- packages/ripple-ui-core/src/components/card-carousel/RplCardCarousel.vue
…ms in carousel
**Issue**:
- Added check for items in TideLandingPAgeCardCarousel to not display title if there are no items
- Added conditional in RplCardCarousel in computed property to prevent fatal error
- 
-
> [R20-1593] handle no items in card carousel

- packages/ripple-ui-core/src/components/timeline/RplTimeline.stories.mdx
- packages/ripple-ui-core/src/components/timeline/RplTimeline.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-1591
- Added `.rpl-content` to description container in RplTimeline, updated storybook
- 
- Storybook
-
> [R20-1591] Add rpl-content on timeline container

- packages/ripple-ui-core/src/components/search-bar/RplSearchBar.vue
**Issue**:
- Added new key to pass through entire complex option object, for further processing on consumer side (use case: using metadata to modify target URL from suggestion data)
- Also reverted back to `tabindex="-1"` to re-enable keyboard navigation (we are already managing keyboard events)
- 
-
> [R20-1196] Pass entire complex option through as payload

- packages/ripple-tide-landing-page/components/global/TideLandingPage/CardSharedMeta.vue
- packages/ripple-tide-landing-page/components/global/TideLandingPage/PromoCard.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-1630
- Check for metadata values before displaying meta container
- Also check for presence of topic before rendering el
- 
-
> [R20-1630] Only display promocard meta if values exist

- packages/ripple-tide-api/src/utils/markup-transpiler/default-plugins.ts
Old
New
**Issue**: https://digital-vic.atlassian.net/browse/R20-1644
- 
- 
- 
-
> [R20-1644] added missing scroll wrapper for wysiwg tables

- examples/nuxt-app/test/features/search-listing/news.feature
- examples/nuxt-app/test/fixtures/search-listing/news/page.json
- examples/nuxt-app/test/fixtures/search-listing/news/response.json
- packages/ripple-tide-landing-page/components/global/TideLandingPage/CardSharedMeta.vue
- packages/ripple-tide-search/components/global/TideSearchResultCard.vue
- packages/ripple-ui-core/src/styles/utilities/_typography.css
**Issue**: https://digital-vic.atlassian.net/browse/R20-1604
- Add publish date to `TideSearchResultCard` by default where `field_news_date` exists
- Added sample fixture
- Cypress
-
> [R20-1604] Add date to news card

- examples/nuxt-app/app.config.ts
- examples/nuxt-app/test/fixtures/map-table/vsba/custom-collection-config.json
- examples/nuxt-app/test/fixtures/map-table/vsba/page.json
- packages/ripple-tide-search/components/global/TideCustomCollection.vue
- packages/ripple-tide-search/components/global/TideSearchListingResultsMap.vue
**Issue**:
- Instead of using the seperate fields for lat and long, we use the single geo_point field. This is required to support vicpol map and should be the pattern going forward for all maps.
- 
- Need to update custom collection config in develop.content.vic for the school buildings test fixture. See https://github.com/dpc-sdp/ripple-framework/pull/965/files#diff-f32ccc387334966d5bdc68becc99b0ee9816feddecb6fda0d0520824a1fc8e0aL29 for example
-
> Use single field for maps location data

- packages/nuxt-ripple-analytics/lib/index.ts
- packages/nuxt-ripple-analytics/lib/tracker.ts
- packages/ripple-ui-forms/src/components/RplForm/RplForm.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-1665
- Update form submission event, so instead of a single form submission event we now have two events (from the dataLayers point of view); form submit, for every time a submission attempt takes place and form complete that fires after a successfully submission.
- Submit a form with invalid/incomplete data, then again with valid/complete data and check the `window.dataLayer` variable in the console. REF: https://www.v2.reference.sdp.vic.gov.au/test-form
> [R20-1665] update form submission events

- packages/ripple-tide-search/mapping/utils/index.ts
resolves R20-1692
**Issue**:
- 
- 
- 
-
> [R20-1692] fix(@dpc-sdp/ripple-tide-search): :bug: fix dropdown option sort order from taxonomy weight

- examples/nuxt-app/test/features/landingpage/sidebar.feature
- examples/nuxt-app/test/fixtures/landingpage/sub-faulty.json
- packages/nuxt-ripple/components/TideSidebarRelatedLinks.vue
- packages/ripple-test-utils/step_definitions/content-types/landing-page.ts
**Issue**:
- The BE can sometimes return related links that have no title or URL, these should be filtered out to prevent the component render and associated "Related links" heading
- e.g. this is from a vicpol news page: 
Appears on page like this:
- Cypress test added with faulty fixture
-
> fix(nuxt-ripple): :bug: filter incomplete related links

- packages/ripple-ui-maps/src/components/map/RplMap.vue
- packages/ripple-ui-maps/src/composables/useMapControls.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-1730
- 
- 
- 
-
> [R20-1730] Fixed icon not changing when exiting fullscreen map via keyboard

- packages/ripple-ui-core/src/vite.plugins.ts
- Looks like an update to SVGO https://github.com/svg/svgo/pull/1879 has fixed a long standing issue where unused defs weren't removed properly. This just means in SVG0 `3.2.0` our sprint sheet gets  wiped and all `<defs>` in the file removed.
> fix(@dpc-sdp/ripple-ui-core): fix svg sprite breaking in svgo 3.2.0

- packages/ripple-ui-core/src/styles/components/_table.css
**Issue**: https://digital-vic.atlassian.net/browse/R20-1699
- Make tables full width; the ticket mentions removing the background from the table but that impacts our JS-less scroll indicators. Making the table full width resolves the tickets issue and arguably looks better.
> [R20-1699] make tables full width

- packages/ripple-ui-core/src/components/card/RplCard.css
**Issue**: https://digital-vic.atlassian.net/browse/R20-1546
- Update promo card content margin as per feedback: "Spacing should be consistent across all promo cards across all breakpoints. Token that should be used is rpl-sp-3 (12px) promo cards ONLY"
> [R20-1546] update promo card content margin

- examples/nuxt-app/test/features/search-listing/filters.feature
- examples/nuxt-app/test/features/search-listing/pagination.feature
- packages/ripple-test-utils/step_definitions/content-types/listing.ts
- packages/ripple-tide-search/composables/useTideSearch.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-1719
- This update stops a search taking place even when the filters haven't changed 
- This also means we're resetting filters back to the initial URL now (i.e. no query params)
- Go to any current search listing (https://www.vic.gov.au/family-violence-recommendations/) and click clear filters, this fires off a search even though nothing has changed (from a users point of view). Contrast that to this PR and you should see the same action won't trigger an unneeded search.
> [R20-1719]: stop search firing when clearing filters without change

- packages/ripple-ui-core/src/components/data-table/RplDataTable.css
**Issue**: https://digital-vic.atlassian.net/browse/R20-1699
- Remove unused vars and padding from data table
The main RplTable background was being set to nothing for data tables, @waitingallday do you happen to remember what these lines were for? https://github.com/dpc-sdp/ripple-framework/pull/382/files#diff-cf57cdb1728ef5fce7d68c7a7403c06915828b7e023defdfa2500efda55bc23dR70
> [R20-1699] remove unused vars and padding from data table

- examples/nuxt-app/test/features/data-table/custom-collection.feature
- examples/nuxt-app/test/fixtures/landingpage/custom-collection/alt-form-theme-default.json
- examples/nuxt-app/test/fixtures/landingpage/custom-collection/alt-form-theme-reverse.json
- examples/nuxt-app/test/fixtures/landingpage/custom-collection/form-theme-default.json
- examples/nuxt-app/test/fixtures/landingpage/custom-collection/form-theme-reverse.json
- examples/nuxt-app/test/fixtures/search-listing/table/page-extra-component.json
- examples/nuxt-app/test/fixtures/search-listing/table/page-extra-structured.json
- examples/nuxt-app/test/fixtures/search-listing/table/page.json
- packages/nuxt-ripple/components/TideDynamicComponents.vue
- packages/ripple-test-utils/step_definitions/components/custom-collection.ts
- packages/ripple-tide-landing-page/components/global/TideLandingPage.vue
- packages/ripple-tide-search/components/TideSearchListingPage.vue
- packages/ripple-tide-search/components/TideSearchResultsCount.vue
- packages/ripple-tide-search/components/global/TideCustomCollection.vue
- packages/ripple-tide-search/components/global/TideSearchFilterDependent.vue
- packages/ripple-tide-search/components/global/TideTideSearchListing.vue
- packages/ripple-tide-search/types.ts
- packages/ripple-ui-forms/src/inputs/checkbox.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-1736
- Update results key for interoperability between search listing and custom collections 
- Update collection 'theming' 
- Minor spacing fix on collection search
- Currently the form 'theme' is partially hard coded and partially based off of whether a map is present, this update just wraps form theme into a single `formTheme` option. This does mean `formTheme` will need to be added to existing map forms, going by confluence we only have one so far and it not live, so this update seems fine from that point of view.
**Spacing issue:**
**Default pages - default form theme:**
**Alt pages - default form theme:**
**Default and alt pages - reverse form theme:**
> [R20-1736] update results key for interop, collection 'theme' improvements

- examples/nuxt-app/components/global/TableExtraContentComponentExample.vue
- examples/nuxt-app/test/features/search-listing/table.feature
- examples/nuxt-app/test/fixtures/search-listing/table/page-extra-component.json
- packages/ripple-ui-core/src/components/data-table/RplDataTableRow.vue
-  Allow props to be passed to the main extraContent component, this will be especially useful for manage labels via config.
> feat(@dpc-sdp/ripple-ui-core): allow props to be passed to the main extraContent component

- packages/ripple-ui-core/src/components/card/RplCard.css
**Issue**: https://digital-vic.atlassian.net/browse/R20-1546
- We recently updated the promo card margin as per: _"Spacing should be consistent across all promo cards across all breakpoints. Token that should be used is rpl-sp-3 (12px) promo cards ONLY"_, turns out the avatar cards are promo cards in the design system so we just need to update avatar cards as well.
> [R20-1546] update avatar content margin

- packages/ripple-tide-api/types.d.ts
- packages/ripple-tide-grant/mapping/index.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-1780
- use getBodyFromField for grant accordion content
> [R20-1780] use getBodyFromField for grant accordion content

- examples/nuxt-app/test/features/search-listing/filters.feature
- examples/nuxt-app/test/fixtures/search-listing/filters/filters-open.json
- packages/ripple-test-utils/step_definitions/content-types/listing.ts
- packages/ripple-tide-search/components/TideSearchListingPage.vue
- packages/ripple-tide-search/components/global/TideTideSearchListing.vue
- packages/ripple-tide-search/types.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-1767
- Added flag in search listing config to display filter panel on page load - `"showFiltersOnLoad": true`
- 
- Cypress
-
> [R20-1767]Flag to display filters on page load

- packages/ripple-tide-search/composables/useTideSearch.ts
- packages/ripple-tide-search/types.ts
- packages/ripple-ui-maps/src/components/map/RplMap.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-1733
- Added `defaultTab` option to searchListingConfig, can be set to 'map' or 'listing
- If not provided, it defaults to 'map' if there is a map tab, or 'listing' if there is no map tab
- Ensured that the 'infobox' popup still shows up in fullscreen mode
- 
-
> [R20-1733] Added ability to configure default tab in custom collection and fixed fullscreen view

- packages/ripple-ui-forms/src/components/RplForm/RplForm.stories.mdx
- packages/ripple-ui-forms/src/components/RplFormNumber/RplFormNumber.stories.mdx
- packages/ripple-ui-forms/src/components/RplFormNumber/RplFormNumber.vue
- packages/ripple-ui-forms/src/index.ts
- packages/ripple-ui-forms/src/inputs/input-utils.ts
- packages/ripple-ui-forms/src/inputs/number.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-1712
- Refactor existing number input in `rpl-ui-forms` to include +/- buttons
- Set up as a `RplFormElement` to support schema usage
- Browser number control will be used by default, add `mode="alt"` to enable +/- buttons
- Storybook
-
> [R20-1712] Number input with buttons

- examples/nuxt-app/test/features/news/news.feature
- examples/nuxt-app/test/features/site/theme.feature
- examples/nuxt-app/test/fixtures/news/disable-detail-labels.json
- examples/nuxt-app/test/fixtures/news/feature-flags.json
- examples/nuxt-app/test/fixtures/site/disable-updated-date.json
- packages/nuxt-ripple/components/TideBaseLayout.vue
- packages/nuxt-ripple/composables/use-feature-flags.ts
- packages/ripple-test-utils/step_definitions/common/shared-elements.ts
- packages/ripple-test-utils/step_definitions/content-types/news.ts
- packages/ripple-tide-api/types.d.ts
- packages/ripple-tide-news/app.config.ts
- packages/ripple-tide-news/components/TideNewsBody.vue
- packages/ripple-ui-core/src/components/description-list/RplDescriptionList.css
- packages/ripple-ui-core/src/components/description-list/RplDescriptionList.vue
- packages/ripple-ui-core/src/components/description-list/RplDescriptionListItem.vue
- packages/ripple-ui-core/src/components/description-list/constants.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-1803
- Add flag to control the display of updated date, news detail labels and news featured image aspect ratio
> [R20-1803] add new featureFlags

- packages/ripple-tide-search/components/TideSearchListingPage.vue
- packages/ripple-tide-search/types.ts
- packages/ripple-ui-core/src/components/expandable/RplExpandable.vue
- packages/ripple-ui-core/src/composables/useComputedSpeed.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-1767
- Moved `showFiltersOnLoad` into `searchListingConfig`
- Added initial open state state CSS to `RplExpandable` to allow overflow where needeed
- A bunch of tslint
- 
-
> [R20-1767] Move key, add initial state for `RplExpandable`

- packages/ripple-tide-search/components/TideSearchPage.vue
- packages/ripple-tide-search/components/global/TideSearchNoResults.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-1740
- Pass current keyword through to `noResults` when refetching after initial load (currently uses initial page load `useRoute().query` which never updates)
- 
- 
-
> [R20-1740] Update keyword in `noResults` component

- examples/nuxt-app/test/features/site/shared-elements.feature
- packages/ripple-test-utils/step_definitions/common/shared-elements.ts
- packages/ripple-ui-core/src/components/footer/RplNavSection.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-1807
- the repeated section link is now only for within accordions and the section title itself links on desktop i.e. when not within an accordion
> [R20-1807] repeating link moves to title on desktop

- packages/ripple-tide-landing-page/components/global/TideLandingPage/ContentCollection.vue
- packages/ripple-tide-search/components/TideSearchPage.vue
- packages/ripple-tide-search/composables/useSearchUI.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-1615
- Don't show no-results message before searching, this applies to the main search page and content collections
> [R20-1615] don't show no-results message before searching

- packages/ripple-tide-search/components/global/TideSearchListingResultsMap.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-1828
- I don't believe this has been used yet, so I'm just making the props for the popupTitle and popupContent components the same, i.e. they're both take a `feature` props now instead of one being `feature` and the other being `selectedFeature`
> [R20-1828] make popup section props the same

- packages/ripple-tide-landing-page/mapping/components/call-to-action/call-to-action.ts
- packages/ripple-ui-core/src/components/card/RplCallToActionCard.stories.mdx
- packages/ripple-ui-core/src/components/card/RplCallToActionCard.vue
- packages/ripple-ui-core/src/components/card/RplCard.css
**Issue**: https://digital-vic.atlassian.net/browse/R20-1822
- add a "stacked" version of the cta card
> [R20-1822] add a "stacked" version of the cta card

- packages/ripple-tide-landing-page/components/global/TideLandingPage/ContentCollection.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-1825
- Bring content collection inline with search/search listings/topics etc, by this I mean display the full URL instead or the relative one in the search result.
> [R20-1825] bring content collection inline with search etc.

- packages/ripple-tide-search/components/global/TideCustomCollection.vue
- packages/ripple-ui-maps/src/components/map/RplMap.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-1818
- Rejig closing map popups to be explicit, this means more events triggering the popups to close but better feedback. i.e. they close straight away.
> [R20-1818] explicitly close popups

- packages/ripple-tide-search/components/TideSearchListingPage.vue
**Issue**: https://digital-vic.atlassian.net/browse/SRM-1284
- Use TideSecondaryCampaign so secondary banner works
> [SRM-1284] use tide version of secondary campaign

- packages/ripple-ui-core/src/components/expandable/RplExpandable.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-1834
- Add styles only for initially open sections so content doesn't overflow on first open
- This still works for the search listings that start with the filters open
> [R20-1834] add styles only for initially open sections

- packages/ripple-tide-search/components/global/TideCustomCollection.vue
- packages/ripple-tide-search/components/global/TideTideSearchListing.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-1813
- make custom collection expanded config the same as search listings
- remove unused showFiltersOnLoad prop from search listing
> [R20-1813] make custom collection expanded config the same as search listings

- packages/ripple-tide-api/src/utils/markup-transpiler/index.ts
- packages/ripple-tide-api/types.d.ts
- Markup plugins current only run if you supply more than 1, however you should be able to use a single plugin if you want
> fix(@dpc-sdp/ripple-tide-api): allow the use of a single markup plugin

- packages/ripple-tide-api/src/services/__test__/tide-api-base.test.ts
- packages/ripple-tide-api/src/services/__test__/tide-config.ts
- packages/ripple-tide-api/src/services/__test__/tide-page.test.ts
- packages/ripple-tide-api/src/services/__test__/tide-site.test.ts
- packages/ripple-tide-api/src/services/tide-page.ts
- packages/ripple-tide-api/src/services/tide-site.ts
- This adds support for merging site mapping and content type mapping, for the motivation see: https://github.com/dpc-sdp/ripple-framework/issues/1098 with this change sites wanting to add extra mapping for the site or content types can do so, without having to remember to import the core types and then spread them with their own, making it a nicer/easier experience. 
Note: I had a look and VLA is the only site currently extending site mapping and it's still in development so we can easily switch it over.
> feat(@dpc-sdp/ripple-tide-api): allow the merging of page and site mapping

- packages/ripple-ui-forms/src/components/RplForm/RplForm.stories.mdx
**Issue**: https://digital-vic.atlassian.net/browse/R20-428
- update CSS loading order for forms story, so it matches a real site
> [R20-428] update CSS loading order for storybook

- examples/nuxt-app/components/global/test/TestMapSidepanelItem.vue
- packages/ripple-tide-search/components/global/TideSearchAddressLookup.vue
- packages/ripple-ui-core/src/components/data-table/RplDataTable.vue
- packages/ripple-ui-maps/src/components/map/RplMap.vue
**Issue**:
- defineProps and defineEmits are compiler macros that dont need an explicit import. 
- https://vuejs.org/api/sfc-script-setup.html#defineprops-defineemits
```
WARN  [@vue/compiler-sfc] defineProps is a compiler macro and no longer needs to be imported.                                                                                                            
WARN  [@vue/compiler-sfc] defineEmits is a compiler macro and no longer needs to be imported.                                                                                                           
```
Should not get these errors in terminal after running dev command
> fix redundant imports for defineProps compiler macros

- examples/nuxt-app/test/features/site/feature-flags.feature
- examples/nuxt-app/test/fixtures/site/reference.json
- packages/nuxt-ripple/components/TideBaseLayout.vue
- packages/ripple-test-utils/step_definitions/common/mocks.ts
- packages/ripple-test-utils/step_definitions/common/navigation.ts
- packages/ripple-test-utils/step_definitions/common/shared-elements.ts
- packages/ripple-tide-api/types.d.ts
- packages/ripple-ui-core/src/components/primary-nav/RplPrimaryNav.vue
- packages/ripple-ui-core/src/components/primary-nav/components/nav-bar/RplPrimaryNavBar.vue
- packages/ripple-ui-core/src/components/primary-nav/components/search-form/RplPrimaryNavSearchForm.vue
- packages/ripple-ui-core/src/components/tabs/RplTabs.cy.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-1953
-  Add searchUrl prop for primary nav search form (with corresponding feature flag)
- Fix tabs component test
> [R20-1953] add searchUrl prop for primary nav

- packages/ripple-ui-core/src/components/layout/RplLayoutBackToTop.css
**Issue**: https://digital-vic.atlassian.net/browse/R20-1961
- Just noticed a recent change meant nothing behind the back to top button container could be interacted with, this meant the content rating form was unusable.
> fix(@dpc-sdp/ripple-ui-core): make only button clickable

- examples/nuxt-app/test/features/search-listing/aggregations.feature
- packages/ripple-tide-search/components/TideSearchListingPage.vue
- packages/ripple-tide-search/composables/useTideSearch.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-1981
- Fix the search listing dropdowns that use elasticsearch, ref: https://www.v2.www.vic.gov.au/family-violence-recommendations
- Also updated the `min_doc_count` param so 'empty' results are only returned when using `dynamicAggregations`, this essentially reverts the default behavior back to how it was, i.e elastic aggregation only return items with docs
> [R20-1981] fix search listing dropdowns

- packages/nuxt-ripple/mapping/base/topic-tags/topic-tags-mapping.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-1989
- Make sure topics/tags only show if they have a name
Seems like Drupal can return an "invalid" tags, so now we just make sure the topic/tag has a name.
**Before**
**After**
> [R20-1989] make sure topic/tags have a name

- packages/ripple-tide-search/app.config.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-1923
- Add search listings to site search
- Search for a search listing
> [R20-1923] add search listings to site search

- examples/nuxt-app/pages/_layout.vue
- packages/nuxt-ripple/components/TideSidebarSocialShare.vue
**Issue**:
- If `props.network` is not present, pass `undefined` to fallback to component's default networks (matching previous behaviour)
-
- 
-
> fix(@dpc-sdp/nuxt-ripple): :bug: fallback to default if unspecified

- packages/ripple-tide-search/components/global/TideCustomCollection.vue
**Issue**: https://github.com/dpc-sdp/ripple-framework/issues/1104
- 
- 
- 
-
> feat(@dpc-sdp/ripple-tide-search): fix issue with search dropdown option reactivity

- .github/workflows/nuxt.yml
- examples/nuxt-app/package.json
- examples/nuxt-app/test/features/site/search.feature
- examples/nuxt-app/test/fixtures/site/search-request.json
- examples/nuxt-app/test/fixtures/site/search-response.json
- packages/ripple-test-utils/step_definitions/common/mocks.ts
- packages/ripple-tide-search/components/TideSearchPage.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-713
- Fix filter spacing  
- Add refine tally
- Add some search tests
> [R20-713] fix spacing, add refine tally

- packages/ripple-tide-api/src/utils/markup-transpiler/cheerio.test.ts
- packages/ripple-tide-api/src/utils/markup-transpiler/default-plugins.ts
- packages/ripple-ui-core/src/components/content/RplContent.stories.mdx
- packages/ripple-ui-core/src/components/content/fixtures/testcontent.html
- packages/ripple-ui-core/src/components/data-table/RplDataTable.vue
- packages/ripple-ui-core/src/styles/utilities/_focus.css
**Issue**: https://digital-vic.atlassian.net/browse/R20-1978
- add focus state for scrolling tables, needed a new class using focus-visible so the table isn't outline when click around
> [R20-1978] focus state for scrolling tables

- packages/ripple-tide-search/components/TideSearchListingPage.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-1519
- Hid updated date on search listings and topic/tag listing pages
- Kept it as a prop for future options
- 
-
> [R20-1519] Hide page updated date for topic/tag/search listing pages

- packages/ripple-ui-core/src/components/alert/RplAlert.css
- packages/ripple-ui-core/src/components/footer/RplFooter.css
- packages/ripple-ui-core/src/components/header/RplHeaderLinks.css
- packages/ripple-ui-core/src/components/result-listing/RplSearchResult.css
- packages/ripple-ui-core/src/components/text-link/RplTextLink.css
- packages/ripple-ui-forms/src/components/RplFormAlert/RplFormAlert.css
as requested
**Issue**: https://digital-vic.atlassian.net/browse/R20-1987
- 
- 
- 
-
> [R20-1987] Removed visited styling from all links, reapply only to search results

- packages/ripple-tide-search/components/global/TideCustomCollection.vue
- packages/ripple-tide-search/types.ts
- packages/ripple-ui-maps/src/components/geolocation/RplMapGeolocateButton.css
- packages/ripple-ui-maps/src/components/geolocation/RplMapGeolocateButton.vue
**Issues**: 
- https://digital-vic.atlassian.net/browse/R20-2028
- https://digital-vic.atlassian.net/browse/R20-2019
- 
- 
- 
-
> [R20-2028, R20-2019] Geolocate button messages and labels

- packages/ripple-ui-forms/src/components/RplFormOptions/RplFormCheckboxGroup.css
- packages/ripple-ui-forms/src/components/RplFormOptions/RplFormCheckboxGroup.vue
- packages/ripple-ui-forms/src/components/RplFormOptions/RplFormOption.css
- packages/ripple-ui-forms/src/components/RplFormOptions/RplFormOption.vue
- packages/ripple-ui-forms/src/components/RplFormOptions/RplFormRadioGroup.css
- packages/ripple-ui-forms/src/components/RplFormOptions/RplFormRadioGroup.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-464
- Make checkboxes and radio buttons meet touch target size as per design doc
> [R20-464] radio and checkbox touch targets

- examples/nuxt-app/test/features/search-listing/grants.feature
- examples/nuxt-app/test/fixtures/search-listing/grants/response.json
- packages/ripple-tide-grant/components/global/TideGrantSearchResult.vue
- packages/ripple-tide-search/composables/useSearchResult.ts
**Issue**: https://digital-vic.atlassian.net/browse/SDPAP-9395
_Decided to bring this one back after all, I was thinking of addressing it in the site search updates but as grants don't link directly to external sites in site search right now anyway this change if fine to just address search listings. There's no other listings expecting the generic `field_node_link` field to come back as the default URL? I couldn't see any._
- Remove "global" `field_node_link` check so results always link to result page itself, this will mean events link correctly to the event page
- Update grant result to check for external links so it continues to behave as expected
> [SDPAP-9395] move external link check to grant result card

- examples/nuxt-app/test/features/search-listing/result-items.feature
- examples/nuxt-app/test/fixtures/search-listing/result-items/page.json
- examples/nuxt-app/test/fixtures/search-listing/result-items/response.json
- packages/ripple-test-utils/step_definitions/content-types/listing.ts
- packages/ripple-tide-search/components/global/TideCustomCollection.vue
- packages/ripple-tide-search/components/global/TideSearchResultCard.vue
- packages/ripple-tide-search/components/global/TideTideSearchListing.vue
- packages/ripple-tide-search/types.ts
- Add support for multiple result item types, the search listing API/JSON looks like this would be supported, plus why not support it.
As an example say you wanted something like a News & Events listing, the example config below is now supported.
```
"resultsConfig": {
"layout": {
"component": "TideSearchResultsList"
},
"item": {
"news": {
"component": "TideNewsSearchResult"
},
"event": {
"component": "TideEventSearchResult"
}
}
}
```
> feat(@dpc-sdp/ripple-tide-search): allow multiple result items types

- packages/ripple-ui-core/src/styles/components/_embed.css
**Issue**: https://digital-vic.atlassian.net/browse/R20-402
- Design feedback for media embeds
> [R20-402] design feedback for media embeds

- packages/ripple-tide-search/components/TideSearchPage.vue
- packages/ripple-ui-core/src/components/primary-nav/RplPrimaryNav.vue
- packages/ripple-ui-core/src/components/primary-nav/components/search-form/RplPrimaryNavSearchForm.vue
…
**Issue**: https://digital-vic.atlassian.net/browse/R20-1451
- Search UI errors if the query is longer than 128 characters, so I set a max length on the input so the user won't get this error when copy pasting a lot of text
- 
- 
-
> [R20-1451] - Set a max length on site search bar to match search ui max length

- packages/ripple-ui-core/src/components/pagination/RplPagination.css
**Issue**: https://digital-vic.atlassian.net/browse/R20-2016
- 
- 
- 
-
> [R20-2016] Added underlines to pagination page links (design feedback)

- package.json
- patches/@vitejs__plugin-vue@5.0.4.patch
- pnpm-lock.yaml
**Issue**: https://digital-vic.atlassian.net/browse/R20-1977
- Used the suggested solution here to patch the Vue Vite plugin https://github.com/vitejs/vite-plugin-vue/issues/397
- I tested locally and CSS now updates on save without a restart, and the rest of the project seems to work as before.
- 
-
> [R20-1977] - Patch vite-plugin-vue to fix CSS files not triggering HMR

- packages/ripple-ui-core/src/components/media-embed/RplMediaEmbed.vue
- packages/ripple-ui-core/src/styles/components/_embed.css
- packages/ripple-ui-core/src/styles/utilities/_aspect.css
**Issue**: https://digital-vic.atlassian.net/browse/R20-402
- Add new portrait aspect ratio for media embed, the confluence doc had the wrong aspect ratio i.e. 4/3 when it should have been 3/4
> [R20-402] add new portrait aspect ratio for media embed

- packages/ripple-tide-landing-page/components/global/TideLandingPage/PrimaryCampaignBanner.vue
- packages/ripple-ui-core/src/components/campaign-banner/RplCampaignBanner.css
- packages/ripple-ui-core/src/components/campaign-banner/RplCampaignBanner.vue
- packages/ripple-ui-core/src/components/campaign-banner/RplPrimaryCampaign.stories.mdx
- packages/ripple-ui-core/src/components/campaign-banner/RplPrimaryCampaign.vue
- packages/ripple-ui-core/src/components/campaign-banner/RplSecondaryCampaign.stories.mdx
- packages/ripple-ui-core/src/components/campaign-banner/RplSecondaryCampaign.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-329
- The original implementation used flex box, but things didn't quite fit 'the grid' exactly, and the CSS wasn't super maintainable, so for CSS simplicity and design accuracy this removes all that in favor of our grid classes.
> [R20-329] campaign feedback

- packages/ripple-ui-forms/src/components/RplFormDropdown/RplFormDropdown.css
- Stop over-scrolling on drop-downs so users don't end up inadvertently scrolling down the page.
> style(@dpc-sdp/ripple-ui-forms): stop overscrolling on dropdowns

- packages/ripple-ui-forms/src/components/RplFormDropdown/RplFormDropdown.cy.ts
- packages/ripple-ui-forms/src/components/RplFormDropdown/RplFormDropdown.stories.mdx
- packages/ripple-ui-forms/src/components/RplFormDropdown/RplFormDropdown.vue
- packages/ripple-ui-forms/src/components/RplFormDropdown/fixtures/sample.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-2035
- Add basic keyboard/search support to dropdowns, this mimics native behavior. i.e.
- Using a single key cycles through options, so hitting "a" multiple times (with delay) will cycle through all options starting with "A"
- Quickly typing multiple characters will jump to any matching options, for example typing "avo" will jump to "Avocado"
> [R20-2035] add basic keyboard/search support to dropdowns

- packages/ripple-tide-search/components/TideSearchSortOptions.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-2040
- Fix sort options aria label, `for` doesn't work for non labelable elements like our custom dropdown
**Before**
**After**
> [R20-2040] sort options aria label

- packages/ripple-ui-core/src/components/primary-nav/RplPrimaryNav.css
**Issue**: https://digital-vic.atlassian.net/browse/R20-2041
The latest version of safari on ios was triggering a scroll when the search field was focused, this in turned triggered our menu to be hidden as that's what it does, it hides when the page is scrolled down. 
This issue only effected sites using the quick exit as having the quick exit in the menu pushes down the search input down just enough for safari to decided it needs to move up the page so the user can see/access the input field better.
> [R20-2041] always ensure expanded menu is visible

- packages/nuxt-ripple/app.config.ts
- packages/nuxt-ripple/composables/use-tide-language.ts
**Issue**: https://digital-vic.atlassian.net/browse/SDPAP-9439
- Support quick type adjustments for language fonts (I'm not completely sold on this approach).
> [SDPAP-9439] support quick type adjustments for language fonts

- examples/nuxt-app/test/features/search-listing/filters.feature
- examples/nuxt-app/test/fixtures/search-listing/dependent-filters/page-mix.json
- examples/nuxt-app/test/fixtures/search-listing/dependent-filters/page-single.json
- examples/nuxt-app/test/fixtures/search-listing/dependent-filters/page.json
- packages/ripple-test-utils/step_definitions/content-types/listing.ts
- packages/ripple-tide-search/components/TideSearchListingPage.vue
- packages/ripple-tide-search/components/global/TideCustomCollection.vue
Jira: https://digital-vic.atlassian.net/browse/R20-2046
- Hide refine search when filters are already open
> [R20-2046] hide refine search when filters are already open

- package.json
- patches/parse5-htmlparser2-tree-adapter@7.0.0.patch
- patches/parse5@7.1.2.patch
- pnpm-lock.yaml
**Issue**: https://digital-vic.atlassian.net/browse/R20-1976
- Sourcemaps were disabled in a commit earlier this year but parse5 hasn't seen a release since 2022 - patching out refs until it's updated
- 
- 
-
> [R20-1976] Patch sourcemap refs out of parse5

- packages/nuxt-ripple/server/api/tide/page.ts
**Issue**:
https://github.com/dpc-sdp/ripple-framework/issues/1178
- remove trailing slash before requesting to page API
- 
- create a redirect in BE
- access it on FE with trailing slash and without it.
- both should be working.
> fix(@dpc-sdp/nuxt-ripple): removes trailing slash on api request

- examples/nuxt-app/test/features/search-listing/suggestions.feature
- examples/nuxt-app/test/features/site/search.feature
- packages/ripple-test-utils/step_definitions/content-types/listing.ts
- packages/ripple-tide-search/components/TideSearchListingPage.vue
- packages/ripple-tide-search/components/global/TideCustomCollection.vue
- packages/ripple-tide-search/components/global/TideSearchAddressLookup.vue
**Issue**: https://digital-vic.atlassian.net/browse/R20-1451
- 
- 
- 
-
> [R20-1451] Added missing debouncing to suggestions and limit to 128 chars

- packages/ripple-ui-core/src/components/layout/RplLayout.css
**Issue**: https://digital-vic.atlassian.net/browse/R20-2027
- Some accessibility tools allow inverting a page, however without the bg being explicitly set this doesn't work well.
> [R20-2027] set default layout background colour

- examples/nuxt-app/test/features/landingpage/custom-collection.feature
- examples/nuxt-app/test/features/search-listing/filters.feature
- examples/nuxt-app/test/fixtures/landingpage/custom-collection/alt-form-theme-default.json
- examples/nuxt-app/test/fixtures/landingpage/custom-collection/alt-form-theme-reverse.json
- examples/nuxt-app/test/fixtures/landingpage/custom-collection/form-theme-default.json
- examples/nuxt-app/test/fixtures/landingpage/custom-collection/form-theme-reverse.json
- examples/nuxt-app/test/fixtures/search-listing/filters/page.json
- examples/nuxt-app/test/fixtures/search-listing/filters/request-clear-filled.json
- examples/nuxt-app/test/fixtures/search-listing/filters/request-term-array.json
- examples/nuxt-app/test/fixtures/search-listing/filters/request-term-single.json
- packages/ripple-test-utils/step_definitions/components/custom-collection.ts
- packages/ripple-test-utils/step_definitions/content-types/listing.ts
- packages/ripple-tide-search/components/global/TideSearchFilterCheckboxGroup.vue
- packages/ripple-tide-search/composables/useTideSearch.ts
- packages/ripple-tide-webform/mapping/webforms-mapping.ts
- packages/ripple-ui-forms/src/components/RplFormOptions/RplFormCheckboxGroup.css
- packages/ripple-ui-forms/src/components/RplFormOptions/RplFormCheckboxGroup.stories.mdx
- packages/ripple-ui-forms/src/components/RplFormOptions/RplFormCheckboxGroup.vue
- packages/ripple-ui-forms/src/components/RplFormOptions/RplFormRadioGroup.css
- packages/ripple-ui-forms/src/inputs/checkboxGroup.ts
**Issue**: https://digital-vic.atlassian.net/browse/SDPAP-9392
- Add support for inline checkboxes (much like our existing inline radios)
- Support 'Side by side' mode i.e. `inline` for radios and checkboxes in webforms
- Add checkbox group support to search listings
> [SDPAP-9392] support for inline checkboxes

- examples/nuxt-app/test/features/maps/maps.feature
- packages/ripple-test-utils/step_definitions/content-types/listing.ts
- packages/ripple-ui-forms/cypress/support/component.ts
- packages/ripple-ui-forms/cypress/support/components/RplFauxForm.vue
- packages/ripple-ui-forms/package.json
- packages/ripple-ui-forms/src/components/RplFormDropdown/MultiValueLabel.css
- packages/ripple-ui-forms/src/components/RplFormDropdown/MultiValueLabel.vue
- packages/ripple-ui-forms/src/components/RplFormDropdown/RplFormDropdown.cy.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-1433
- Improve accuracy of more count for dropdowns, this mostly just ensures it doesn't display `+1 more` when there's actually 2 and bit hidden.
https://github.com/dpc-sdp/ripple-framework/assets/287178/38fc4aab-f0a8-4d23-8933-7be769869e1f
https://github.com/dpc-sdp/ripple-framework/assets/287178/6d64893e-5509-43dd-bfc2-3cb70bd18e59
> [R20-1433] improve accuracy of more count for dropdowns

- packages/nuxt-ripple/assets/css/languages.css
**Issue**: https://digital-vic.atlassian.net/browse/SDPAP-9439
- Tweak ar line height
> [SDPAP-9439] tweak ar line height

- examples/nuxt-app/test/features/news/news.feature
- examples/nuxt-app/test/features/publication/publication.feature
- examples/nuxt-app/test/fixtures/publication/sample-publication.json
- packages/ripple-test-utils/step_definitions/content-types/listing.ts
- packages/ripple-test-utils/step_definitions/content-types/publication.ts
- packages/ripple-tide-news/components/TideNewsBody.vue
- packages/ripple-tide-publication/components/TidePublicationBody.vue
- packages/ripple-tide-publication/components/TidePublicationChapters.vue
**Issues**:
https://digital-vic.atlassian.net/browse/R20-1602
https://digital-vic.atlassian.net/browse/R20-1608
- Update published by label, i.e. news and publications now say 'Published by' instead of 'Department' and 'Author'
> [R20-1602][R20-1608] published by label

- CHANGELOG.md
- lerna.json
- packages/eslint-config-ripple/package.json
- packages/nuxt-ripple-analytics/package.json
- packages/nuxt-ripple-cli/package.json
- packages/nuxt-ripple-preview/package.json
- packages/nuxt-ripple/package.json
- packages/ripple-storybook/package.json
- packages/ripple-test-utils/package.json
- packages/ripple-tide-api/package.json
- packages/ripple-tide-event/package.json
- packages/ripple-tide-grant/package.json
- packages/ripple-tide-landing-page/package.json
- packages/ripple-tide-media/package.json
- packages/ripple-tide-news/package.json
- packages/ripple-tide-publication/package.json
- packages/ripple-tide-search/package.json
- packages/ripple-tide-topic/package.json
- packages/ripple-tide-webform/package.json
- packages/ripple-ui-core/package.json
- packages/ripple-ui-forms/package.json
- packages/ripple-ui-maps/package.json
- packages/stylelint-config-ripple/package.json
> chore: 🔖 release ripple 2.11.0

- examples/nuxt-app/test/features/search-listing/table.feature
- examples/nuxt-app/test/fixtures/search-listing/table/page-extra-structured.json
- packages/ripple-tide-search/components/global/TideSearchListing/TideSearchListingTableUrl.vue
**Issue**: https://digital-vic.atlassian.net/browse/SDPAP-9392
- allow specifying the URL text key, i..e allow for the display text to use a different value than the URL itself
> feat(@dpc-sdp/ripple-tide-search): allow specifying the url text key

- examples/nuxt-app/app.config.ts
- examples/nuxt-app/test/features/maps/suggestions.feature
- examples/nuxt-app/test/fixtures/maps/arcgis-address-candidates.json
- examples/nuxt-app/test/fixtures/maps/basic-page.json
- examples/nuxt-app/test/fixtures/maps/example-suburbs-response.json
- packages/ripple-test-utils/step_definitions/components/maps.ts
- packages/ripple-test-utils/step_definitions/content-types/listing.ts
- packages/ripple-tide-search/app.config.ts
- packages/ripple-tide-search/components/global/TideSearchAddressLookup.vue
- packages/ripple-tide-search/composables/useAppConfigFunction.ts
- packages/ripple-tide-search/composables/useLegacySuggestions.ts
- packages/ripple-tide-search/types.ts
- packages/ripple-tide-search/utils/getAddressFromArcGISMagicKey.ts
- packages/ripple-tide-search/utils/rplAddressSuggestionsFn.ts
**Issue**: https://digital-vic.atlassian.net/browse/SDPAP-9454
- Adds the ability to completely customise location suggestions by specifiying an app config function that returns the suggestions. Allows for arguments to be passed to the function.
```
locationQueryConfig: {
component: "TideSearchAddressLookup",
props: {
suggestionsConfig: {
function: string // function name
args: Record<string, any>
}
}
}
```
- Adds backwards compatability for the existing default suggestions, if no function is provided, the old behaviour will be used.
- Adds a built in function available to use for address search called `rplAddressSuggestionsFn`
- 
-
> [SDPAP-9454] - Added address search and refactored search suggestions

- packages/nuxt-ripple-cli/src/commands/init/_templates/layer/latest/github/publish.yml.t
- Update action versions
- Allow for publishing layer pre-release versions using GitHubs pre-release checkbox
- Updated `--allow-same-version` to bring it inline with what's actually used in the layers/ripple-lib-starter repo
- Also updated ripple-lib-starter: https://github.com/dpc-sdp/ripple-lib-starter/pull/26
> feat(@dpc-sdp/nuxt-ripple-cli): update action versions, allow layer pre-releases

- packages/nuxt-ripple/app.config.ts
- packages/ripple-tide-search/components/TideSearchResultTableCell.vue
- packages/ripple-tide-search/components/TideSearchResultTableHeading.vue
- packages/ripple-tide-search/components/global/TideCustomCollection.vue
- packages/ripple-ui-core/src/components/description-list/constants.ts
- packages/ripple-ui-maps/src/components/map/RplMap.vue
- packages/ripple-ui-maps/src/components/map/utils.ts
**Issue**: https://digital-vic.atlassian.net/browse/R20-2053
- default map pin color to primary site color instead of red
- fixed description list missing types
- added helper components for laying out result tables
- pass map deadspace to map results hook so that they can zoom correctly
- fixed centreMap util when it's given a custom zoom level
- 
-
> [R20-2053] Map improvements to support R20-2053

- packages/ripple-tide-api/src/utils/markup-transpiler/cheerio.test.ts
- packages/ripple-tide-api/src/utils/markup-transpiler/default-plugins.ts
- packages/ripple-ui-core/src/styles/components/_table.css
- packages/ripple-ui-core/src/styles/utilities/_typography.css
**Issues**: 
https://digital-vic.atlassian.net/browse/R20-2065
https://digital-vic.atlassian.net/browse/R20-2066
- Align RTL page tables to the right by default
- Allow for setting alignment of tables via CMS tools
> [R20-2065][R20-2066] aligned table content

- packages/nuxt-ripple/components/TideBaseLayout.vue
- packages/ripple-test-utils/step_definitions/components/maps.ts
- packages/ripple-tide-grant/components/global/TideGrantSearchResult.vue
- packages/ripple-tide-landing-page/components/global/TideLandingPage/Accordion.vue
- packages/ripple-tide-search/components/TideSearchListingPage.vue
- packages/ripple-tide-search/components/TideSearchPage.vue
- packages/ripple-tide-search/utils/rplAddressSuggestionsFn.ts
- packages/ripple-ui-core/src/components/slider/RplSlider.vue
- packages/ripple-ui-forms/src/components/RplForm/RplForm.vue
- Cleanup some console/linter warnings
> chore: cleanup some console/linter warnings

- examples/nuxt-app/test/features/search-listing/list.feature
- examples/nuxt-app/test/fixtures/search-listing/list/response.json
- packages/ripple-tide-search/composables/useSearchResult.ts
**Issue**
https://digital-vic.atlassian.net/browse/SD-83
https://digital-vic.atlassian.net/browse/SD-81
- add support for new field: `field_redirect_website`, we used to have a check here for `field_node_link` but that field was used for different purposes. The new field will always redirect the site.
> [SD-83] external redirects

- packages/ripple-tide-search/utils/rplAddressSuggestionsFn.ts
**Issue**:
- Made the max number of suburb and address suggestions customisable
- It seems like different maps will have different values, so this makes it easy to change without a deployment,
- Example config:
```
"locationQueryConfig": {
"component": "TideSearchAddressLookup",
"props": {
"controlMapZooming": false,
"label": "Search by suburb or postcode",
"placeholder": "Enter suburb or postcode",
"suggestionsConfig": {
"function": "rplAddressSuggestionsFn",
"args": {
"maxSuburbSuggestions": 5,
"maxAddressSuggestions": 10
}
}
...
```
-
> feat(@dpc-sdp/ripple-tide-search): allow address search function to be customised via JSON

- examples/nuxt-app/test/features/maps/geolocate.feature
- packages/ripple-test-utils/step_definitions/components/maps.ts
- packages/ripple-tide-search/components/global/TideCustomCollection.vue
**Issue**: Raised from testing https://digital-vic.atlassian.net/browse/SD-75
- Made sure the error message displayed when a user denies location permissions don't stick around after searching or clearing the search.
- 
- 
-
> [SD-75] Clear geolocation button errors on search or reset

- packages/ripple-tide-api/src/services/tide-page.ts
**Issue**: https://digital-vic.atlassian.net/browse/SD-127
- Changed getTaxonomy to utilise the existing 'getEntityList' function, which already handles pagination of the drupal API
- 
- See ticket
-
> [SD-127] fixed getTaxonomy only getting first 50 pages

- examples/nuxt-app/test/features/site/theme.feature
- examples/nuxt-app/test/fixtures/site/primary-nav-nowrap.json
- examples/nuxt-app/test/fixtures/site/primary-nav-wrap.json
- packages/ripple-test-utils/step_definitions/common/shared-elements.ts
- packages/ripple-tide-api/types.d.ts
- packages/ripple-ui-core/src/components/primary-nav/components/nav-bar/RplPrimaryNavBar.css
- packages/ripple-ui-core/src/components/primary-nav/components/nav-bar/RplPrimaryNavBar.vue
**Issue**: https://digital-vic.atlassian.net/browse/SD-170
- Added the feature flag `primaryNavNowrap`, to selectively add a class for preventing long primary nav link titles from wrapping to multiple lines.
- 
- Cypress
-
> [SD-170] Single line primary nav

- jest.config.js
- packages/nuxt-ripple/server/plugins/prefetch.ts
- packages/ripple-tide-api/package.json
- packages/ripple-tide-api/src/utils/markup-transpiler/index.ts
- pnpm-lock.yaml
**Issue**: https://digital-vic.atlassian.net/browse/SD-195
- Cheerio imports updated to direct method, as default export is no longer supported.
- 
- Install deps, build `ripple-tide-api`, build `nuxt-app` and run:
```
pnpm i && pnpm -F nuxt-app build && pnpm -F nuxt-app preview
```
> [SD-195] Cheerio default export has been removed

- packages/ripple-ui-core/src/lib/helpers.ts
**Issue**: https://digital-vic.atlassian.net/browse/SRM-1505
-  Add default timeZone for formatDate so it matches the other date formatter and avoids rare hydration missmatch warnings
> [SRM-1505] add default timeZone for formatDate

- packages/ripple-tide-landing-page/mapping/components/card-carousel/card-carousel-mapping.test.ts
- packages/ripple-tide-landing-page/mapping/components/card-carousel/custom-mapping.ts
- packages/ripple-tide-landing-page/mapping/components/card-carousel/test-data.ts
**Issue**: https://digital-vic.atlassian.net/browse/SD-203
-  Fix external links on carousel events
> [SD-203] fix external links on carousel events

- examples/nuxt-app/test/features/landingpage/custom-collection.feature
- packages/ripple-test-utils/step_definitions/components/custom-collection.ts
- packages/ripple-tide-search/components/global/TideCustomCollection.vue
- packages/ripple-tide-search/types.ts
**Issue**: https://digital-vic.atlassian.net/browse/SD-103
- to support a new requirement to completely override the custom collection listing view
- option is called hideResultsCount, defaults to false to keep backwards compatibility
- Added cypress test
-
> [SD-103] Added option to hide results count on custom collections

- examples/nuxt-app/test/features/maps/maps.feature
- examples/nuxt-app/test/support/step_definitions/index.ts
- packages/ripple-test-utils/package.json
- packages/ripple-test-utils/step_definitions/components/maps.ts
- packages/ripple-ui-maps/src/components/map/RplMap.vue
- packages/ripple-ui-maps/src/composables/useMapControls.ts
- pnpm-lock.yaml
**Issue**: https://digital-vic.atlassian.net/browse/SD-144
- The close button (i.e. cross icon) wasn't displaying when the map goes full screen
- Also `requestFullscreen` is, to quote MDN "Only available on iPad, not on iPhone.", so now we don't display the full screen button if it won't work i.e. on iPhones.
- Ripple `2.14.0` (current behaviour) https://www.develop.police.vic.gov.au/police-station-location?activeTab=map
- Branch with this update https://app.pr-482.vicpol-vic-gov-au.sdp4.sdp.vic.gov.au/police-station-location?activeTab=map
> [SD-144] fix map fullscreen button

- packages/nuxt-ripple-cli/src/commands/init/_templates/site/latest/package.json.t
- packages/ripple-tide-search/package.json
- pnpm-lock.yaml
**Issue**:
- ES dependencies are being pinned in all projects due to change in export upstream. I'd like to be able to remove this at the project level
- build project without pinned es version, needs to be installed into other project as workspace imports dont have the same issue
-
> chore: pin es dependency versions

- examples/nuxt-app/test/features/publication/publication.feature
- packages/nuxt-ripple-analytics/lib/index.ts
- packages/ripple-test-utils/step_definitions/common/site/analytics.ts
- packages/ripple-tide-publication/components/TidePublicationPageActions.vue
**Issue**: https://digital-vic.atlassian.net/browse/SD-161
- Adds a new print event
> [SD-161] add new print event

- packages/ripple-tide-search/components/global/TideSearchAddressLookup.vue
- packages/ripple-tide-search/utils/rplAddressSuggestionsFn.ts
**Issue**: https://digital-vic.atlassian.net/browse/SD-102
- Added support for LGAs to the rplAddressSuggestionsFunction
- LGA suggestions will appear at the top of the suggestions when the `maxLGASuggestions` is greater than 0.
- ![Screenshot 2024-08-28 at 8 35 45 AM](https://github.com/user-attachments/assets/1ef1e451-e63d-4d96-a8f9-792922794653)
- ![Screenshot 2024-08-28 at 8 35 54 AM](https://github.com/user-attachments/assets/fdd7940f-498f-4148-9907-2e9b8a745a00)
- Added OOTB support for adding a 'tag' next to a suggestion, if a suggestion has the `tag` attribute it will display next to the suggestion label:
- ![Screenshot 2024-08-28 at 8 38 40 AM](https://github.com/user-attachments/assets/42d7e4fa-76c2-4afa-8163-1275a32215f2)
- ![Screenshot 2024-08-28 at 8 38 …
> [SD-102] Added additional features needed for KYC map migration

- packages/ripple-tide-landing-page/mapping/components.ts
- packages/ripple-tide-landing-page/mapping/components/from-library/from-library-mapping.ts
- packages/ripple-tide-landing-page/types.ts
**Issue**: https://digital-vic.atlassian.net/browse/SD-198
- Cherry picked Bryce's POC over from his fork to publish an alpha for integration testing 
- Added a whitelist in types to give some control over which paragraphs have the reusable include added (the API response is fairly resilient, but just wanted to avoid running up too many includes in cases where it clearly isn't needed/used)
- Need to run against a BE with reusable paragraphs enabled, e.g. https://nginx-php.pr-1691.content-vic.sdp4.sdp.vic.gov.au/
-
> [SD-198] Reusable paragraphs

- packages/ripple-ui-core/src/components/data-table/RplDataTable.stories.mdx
- packages/ripple-ui-core/src/components/data-table/RplDataTable.vue
- packages/ripple-ui-core/src/components/data-table/RplDataTableRow.vue
- packages/ripple-ui-core/src/components/data-table/fixtures/sample.ts
**Issue**: https://digital-vic.atlassian.net/browse/SD-187
- Added column config prop `isLabelHTML` and support for rendering HTML in table headings
- Storybook https://624ac117357335003a84dac3-xefzoplsdg.chromatic.com/?path=/story/core-containers-data-table--html-headings
-
> [SD-187] Data table html header labels

- examples/nuxt-app/test/features/site/analytics.feature
- packages/nuxt-ripple-analytics/lib/routeChange.ts
- packages/nuxt-ripple-analytics/plugins/analytics.ts
- packages/ripple-test-utils/step_definitions/common/site/analytics.ts
**Issue**: https://digital-vic.atlassian.net/browse/SD-250
- Fixes intermittent issue with the routeChange event not always having the latest route information
> [SD-250] route breadcrumbs improvement

- packages/ripple-ui-core/src/components/vertical-nav/RplVerticalNavList.vue
- packages/ripple-ui-core/src/components/vertical-nav/RplVerticalNavToggle.vue
**Issue**: https://digital-vic.atlassian.net/browse/SD-291
- Add aria label to vertical nav toggles
- Remove un-needed tabindex
> [SD-291] add aria label to vertical nav toggles

- examples/nuxt-app/test/features/maps/maps.feature
- packages/ripple-test-utils/step_definitions/components/maps.ts
- packages/ripple-tide-search/components/global/TideSearchListingResultsMap.vue
- Use prop value for map height
> feat: use prop value for map height

- packages/ripple-tide-api/src/utils/mapping-utils.test.ts
- packages/ripple-tide-api/src/utils/mapping-utils.ts
**Issue**: https://github.com/dpc-sdp/ripple-framework/issues/1321
- Removes  unwanted `internal:` from URLs
> fix: removes unwanted internal: from URLs

- packages/ripple-ui-core/src/components/tabs/RplTabs.stories.mdx
- Just updates the tabs story so tabs can be clicked/interacted with in the story, like the olden days https://www.ripple.sdp.vic.gov.au/storybook/?path=/story/core-navigation-tabs--default-story
> fix: update tabs story so tabs can be clicked

- examples/nuxt-app/test/features/landingpage/forms-analytics.feature
- examples/nuxt-app/test/fixtures/landingpage/full-form.json
- packages/nuxt-ripple-analytics/lib/index.ts
- packages/ripple-test-utils/step_definitions/components/forms.ts
- packages/ripple-ui-forms/src/components/RplForm/RplForm.vue
**Issue**: https://digital-vic.atlassian.net/browse/SD-257
- Added 'form start' analytics event
- 
- Added Cypress test
-
> [SD-257] - Added 'form start' analytics event

- examples/nuxt-app/test/features/site/analytics.feature
- packages/nuxt-ripple-analytics/lib/index.ts
- packages/ripple-test-utils/step_definitions/common/navigation.ts
- packages/ripple-test-utils/step_definitions/common/site/analytics.ts
- packages/ripple-ui-core/src/components/layout/RplLayoutBackToTop.vue
**Issue**: https://digital-vic.atlassian.net/browse/SD-252
- Adds back to top event
> [SD-252] Back to top event

- packages/nuxt-ripple-analytics/lib/index.ts
- packages/ripple-ui-forms/src/components/RplForm/RplForm.vue
- packages/ripple-ui-forms/src/components/RplFormActions/RplFormActions.vue
Relies on the form start event PR, keeping in draft until that's merged
**Issue**: https://digital-vic.atlassian.net/jira/software/c/projects/SD/boards/360?selectedIssue=SD-256
- 
- 
- 
-
> [SD-256] - Added form abandon event

- .github/workflows/publish.yml
**Issue**:
modifies publish on release workflow to do the following
- If the release is not marked pre-prod 
- Runs package version update and changelog creation scripts using the name of the release as the version number
- Commits the result
- Publishes to GPR
- If the release is marked as pre-prod
- publishes to alpha dist tag using git sha version identifier
- Does not commit
- Not sure how to test this prior to merging - I think we may need to YOLO it
-
> chore: :wrench: update publish config to handle draft releases

- packages/nuxt-ripple/mapping/site/index.ts
- packages/ripple-tide-api/src/utils/mapping-utils.test.ts
- packages/ripple-tide-api/src/utils/mapping-utils.ts
- packages/ripple-tide-landing-page/mapping/components/generic-card-mapping.ts
- packages/ripple-tide-landing-page/mapping/hero-header/__test__/test-data.ts
- packages/ripple-tide-landing-page/mapping/hero-header/hero-header-mapping.ts
**Issue**: https://digital-vic.atlassian.net/browse/SRM-1608
- Add a function to remove 'new lines' added via the CMS, these 'new lines' aren't shown on the frontend and cause hydration mismatch errors.
> [SRM-1608] add function to remove new lines

- examples/nuxt-app/test/features/site/shared-elements.feature
- packages/nuxt-ripple/mapping/base/index.ts
- packages/ripple-test-utils/step_definitions/common/shared-elements.ts
- packages/ripple-tide-api/src/utils/mapping-utils.test.ts
- packages/ripple-tide-api/src/utils/mapping-utils.ts
**Issue**: https://digital-vic.atlassian.net/browse/SD-329
- Allow quick exit to be overridden per site section
> [SD-329] per site section quick exit

- packages/nuxt-ripple/mapping/base/sidebar-site-section-nav/sidebar-site-section-nav-mapping.ts
> [SD-430] :bug: handle missing menus better

- packages/nuxt-ripple/nuxt.config.ts
> perf(nuxt-ripple): :wrench: suppress compatibility_date

- packages/ripple-tide-search/components/global/TideSearchAddressLookup.vue
**Issue**: https://digital-vic.atlassian.net/browse/SD-409
- Added `bboxZoomPadding` to address lookup component so that it can be customised per map
- Kept the default value as is to keep backwards compat 
- 
-
> [SD-409] - Made padding for zooming into bbox configurable per map

- packages/ripple-ui-maps/src/components/map/RplMap.vue
**Issue**: https://digital-vic.atlassian.net/browse/SD-481
- Map markers where not using themed colour on actual sites https://www.earlylearning.vic.gov.au/find-centre
- Also we now use rpl-clr-link as the pin colour instead of rpl-clr-primary
> [SD-481] map markers not using themed colour on sites

- packages/ripple-tide-search/nuxt.config.ts
**Issue**: https://digital-vic.atlassian.net/browse/SD-456
We updated `@elastic/search-ui` a while back (https://github.com/dpc-sdp/ripple-framework/pull/1207) which removed the need for these aliases, but we've since reverted back to the previous versions (https://github.com/dpc-sdp/ripple-framework/pull/1300), this just re-adds the aliases so site search works in layers and sites in dev mode once again.
> [SD-456] re-add elastic aliases

- examples/nuxt-app/test/features/maps/maps.feature
- examples/nuxt-app/test/features/maps/vsba.feature
- packages/ripple-test-utils/step_definitions/components/maps.ts
- packages/ripple-tide-search/components/global/TideSearchAddressLookup.vue
**Issue**: https://digital-vic.atlassian.net/browse/SD-466
- Consolidated the two watchers that were handling first load
- Listen for 'rendercomplete' event on map to ensure map is rendered before zooming
- 
-
> [SD-466] - Made logic for centering map on load more reliable

- packages/ripple-ui-core/src/lib/helpers.test.ts
- packages/ripple-ui-core/src/lib/helpers.ts
**Issue**:
- Fixes #947 
- 
- Added unit tests for `formatDate` and `distanceAsPercentage`
-
> Improve formatDate, add more unit tests

- examples/nuxt-app/test/features/landingpage/custom-collection.feature
- examples/nuxt-app/test/features/search-listing/suggestions.feature
- examples/nuxt-app/test/fixtures/landingpage/custom-collection/request-suggestions.json
- examples/nuxt-app/test/fixtures/landingpage/custom-collection/response-suggestions.json
- examples/nuxt-app/test/fixtures/search-listing/suggestions/page-no-suggestions.json
- examples/nuxt-app/test/fixtures/search-listing/suggestions/page-suggestions-override.json
- examples/nuxt-app/test/fixtures/search-listing/suggestions/page-suggestions.json
- packages/ripple-test-utils/step_definitions/components/custom-collection.ts
- packages/ripple-test-utils/step_definitions/content-types/listing.ts
- packages/ripple-tide-search/components/TideSearchListingPage.vue
- packages/ripple-tide-search/components/global/TideCustomCollection.vue
- packages/ripple-tide-search/types.ts
**Issue**: https://digital-vic.atlassian.net/browse/SD-435
- Disabled search suggestions by default (for search listings and custom collections)
- Remove "legacy" autocomplete props
- Make custom collections interoperable with search listings (as far as autocomplete suggestions go)
> [SD-435] disable suggestions by default

- examples/nuxt-app/test/features/search-listing/filters.feature
- packages/ripple-test-utils/step_definitions/components/custom-collection.ts
- packages/ripple-test-utils/step_definitions/content-types/listing.ts
- packages/ripple-tide-search/components/TideSearchListingPage.vue
- packages/ripple-tide-search/components/TideSearchPage.vue
- packages/ripple-tide-search/components/global/TideCustomCollection.vue
**Issue**: https://digital-vic.atlassian.net/browse/SD-339
- Update filters label and always show filters toggle
> [SD-339] update filters toggle

- packages/ripple-tide-api/src/utils/markup-transpiler/cheerio.test.ts
- packages/ripple-tide-api/src/utils/markup-transpiler/default-plugins.ts
**Issue**: https://digital-vic.atlassian.net/browse/SD-414
- Adds support for drupal supplied column widths
> [SD-414] drupal table columns widths

- packages/ripple-ui-maps/src/components/map/RplMap.vue
- packages/ripple-ui-maps/src/components/popup/RplMapPopUp.css
**Issue**: https://digital-vic.atlassian.net/browse/SD-508
- Ensure popup area doesn't extend beyond popup, i.e. the margin at the top of the popup was blocking interactions
- Adjust active pin (was a pixel off)
> [SD-508] ensure popup area doesn't extend beyond visible popup

- examples/nuxt-app/test/features/publication/publication.feature
- examples/nuxt-app/test/features/site/search.feature
- examples/nuxt-app/test/features/sitemap/sitemap.feature
- packages/nuxt-ripple/pages/sitemap.vue
- packages/ripple-tide-publication/pages/[slug]/print-all.vue
- packages/ripple-tide-search/components/TideSearchPage.vue
- packages/ripple-tide-search/pages/search.vue
**Issue**: https://digital-vic.atlassian.net/browse/SD-527
- Add page detail to search, sitemap and print all pages so they come through in the analytics events
- Also update the sitemap page title to be consistent with the rest and avoid the double site name
> [SD-527] add page detail to search, sitemap and print all pages

- packages/nuxt-ripple/server/utils/verifyCaptcha.ts
- packages/ripple-tide-webform/mapping/webforms-captcha.ts
- packages/ripple-tide-webform/types.ts
**Issue**: https://digital-vic.atlassian.net/browse/SD-499
- Update recaptcha key 
- Added await to getWebform (recaptcha validation wasn't working for me without it)
> [SD-499] update recaptcha key

- packages/ripple-tide-search/components/global/TideCustomCollection.vue
- packages/ripple-tide-search/components/global/TideSearchListingResultsMapSidepanel.vue
**Issue**: https://digital-vic.atlassian.net/browse/SD-525
- Added the elastic id to the result mapping so that we have a reliable unique id to use as a key
- There's is no longer a need to pass in `itemIdObjPath` to the JSON blob
- 
-
> [SD-525] Fixed map sidepanel needed a unique id for highlighting

- packages/ripple-ui-core/src/components/data-table/RplDataTable.css
- packages/ripple-ui-core/src/components/data-table/RplDataTableRow.vue
Fix for bug issue #1408
**Issue**:
- Used responsively hidden div for mobile data label instead of pseudo-element content.
- Add data table using an HTML column (`isLabelHTML: true` and include HTML in the `label`)
- Ensure rendered correctly on desktop & mobile
> Fix data table HTML column labels on mobile

- packages/ripple-tide-webform/mapping/webforms-mapping.ts
PR for feature request #1410 
**Issue**:
- Use 'name' attribute if set in webform element config as the field key/name, else use machine_name as usual.
- Build a webform, and for an element, add a custom 'name' attribute in the element's config
- View the form in the frontend and confirm the HTML 'name' attribute uses the custom value
> Support 'name' attribute (if set) in webform mapping

- packages/ripple-tide-search/components/global/TideSearchStandaloneLocationBar.vue
**Issue**: https://digital-vic.atlassian.net/browse/SD-614
- Stop the de-coupled search input redirecting to a new page when there is no value set
> [SD-614] de coupled search submission

- packages/ripple-tide-grant/components/global/TideGrantSearchResult.vue
- Remove unused updated variable
> chore: fix lint warning

- packages/ripple-ui-core/src/components/search-banner/RplSearchBanner.stories.mdx
- Add example id to search banner story to fix axe error
> fix: add example id to search banner story

- examples/nuxt-app/layers/ripple-ui-forms-ext/__test__/forms-ext.feature
- packages/ripple-tide-landing-page/mapping/components/webforms/webforms-mapping.ts
- packages/ripple-tide-webform/mapping/webforms-mapping.ts
- packages/ripple-tide-webform/server/api/tide/webform.ts
- packages/ripple-tide-webform/types.ts
**Issue**: https://digital-vic.atlassian.net/browse/SD-604
- Changed the 'unsupported input message' to only show up when moderation_state = 'draft' 
- Improved the wording of the message to inform the user that it will only show in draft mode
- 
-
> [SD-604] - Changed the 'unsupported input message' in webforms to only show up in draft mode

- packages/ripple-ui-core/src/components/primary-nav/components/nav-bar/RplPrimaryNavBar.css
**Issue**: https://digital-vic.atlassian.net/browse/SD-308
- Fix max-height for mobile secondary logo, this stops the menu items being pushed down
> [SD-308] fix mobile secondary logo height

- examples/nuxt-app/test/features/landingpage/languages.feature
- packages/nuxt-ripple/composables/use-tide-language.ts
- packages/ripple-test-utils/step_definitions/common/languages.ts
**Issue**: https://digital-vic.atlassian.net/browse/SD-658
- Fix html lang
> [SD-658] fix html lang

- examples/nuxt-app/test/features/search-listing/result-items.feature
- examples/nuxt-app/test/fixtures/search-listing/result-items/request-source-exclude.json
- examples/nuxt-app/test/fixtures/search-listing/result-items/request-source-include.json
- packages/ripple-test-utils/step_definitions/content-types/listing.ts
- packages/ripple-tide-search/composables/useTideSearch.ts
- packages/ripple-tide-search/types.ts
**Issue**: https://digital-vic.atlassian.net/browse/SD-676
- Allow elastic response source to be customised, this means you can set and array of includes or excludes to streamline the response data
> [SD-676] allow elastic response source to be customised

- examples/nuxt-app/test/features/landingpage/languages.feature
- examples/nuxt-app/test/fixtures/landingpage/languages-ar.json
- examples/nuxt-app/test/fixtures/landingpage/languages-ko.json
- packages/nuxt-ripple/components/TideBreadcrumbs.vue
- packages/ripple-ui-core/src/components/breadcrumbs/RplBreadcrumbs.vue
**Issue**: https://digital-vic.atlassian.net/browse/SD-584
- Adds breadcrumb language support, we only know the the language of the current page so this just allows for setting the current pages language and direction. We wouldn't want to set direction on the entire breadcrumbs anyway it would break the layout. Also note different fonts can appear slightly differently even with the same font size, line height etc set, this means the alignment of the breadcrumbs text may looks ever so slightly off for certain languages.
> [SD-584] breadcrumb language support

- examples/nuxt-app/test/features/landingpage/home.feature
- packages/nuxt-ripple/components/TideSidebarRelatedLinks.vue
- packages/ripple-test-utils/step_definitions/content-types/landing-page.ts
- packages/ripple-ui-core/src/components/contact-us/RplContactUs.css
- packages/ripple-ui-core/src/components/contact-us/RplContactUs.stories.mdx
- packages/ripple-ui-core/src/components/contact-us/RplContactUs.vue
- packages/ripple-ui-core/src/components/header/RplHeader.css
- packages/ripple-ui-core/src/components/header/RplHeroHeader.stories.mdx
- packages/ripple-ui-core/src/components/header/RplHeroHeader.vue
**Issue**: https://digital-vic.atlassian.net/browse/SD-633
- Add support for multiple hero logos and contact us slot in Ripple UI core
-  See storybook
> [SD-633] support multiple hero logos and contact us slot

- packages/ripple-tide-api/src/utils/createHandler.ts
**Issue**: https://digital-vic.atlassian.net/browse/SD-648
- Changed logger to `.info` on user error
- 
- 
-
> [SD-648] Change log level for user errors

- packages/ripple-ui-core/src/components/stats-grid/RplStatsGrid.css
- packages/ripple-ui-core/src/components/stats-grid/RplStatsGrid.vue
- packages/ripple-ui-core/src/components/stats-grid/RplStatsGridItem.vue
**Issue**: https://digital-vic.atlassian.net/browse/SD-695
- ~Ideally, the stats blocks would all form one `dl` but the rules say that a `dl` can _only_ contain `dt` and `dd` els, so there is no way of wrapping them for alignment in flex. I think this (using a `dl` for each pair) is still correct, but a bit verbose - no difference visually or in size of markup.~
- Refactor markup to `dl` with `dt` and `dd` (wrapped in a single div), use border instead of margin/gap
- Chromatic
-
> [SD-695] Use DL in stats grid markup

- examples/nuxt-app/test/features/maps/suggestions.feature
- examples/nuxt-app/test/features/search-listing/suggestions.feature
- packages/ripple-test-utils/step_definitions/components/maps.ts
- packages/ripple-test-utils/step_definitions/content-types/listing.ts
- packages/ripple-tide-search/components/global/TideSearchLocationAutocomplete.vue
- packages/ripple-ui-core/src/components/search-bar/RplSearchBar.css
- packages/ripple-ui-core/src/components/search-bar/RplSearchBar.cy.ts
- packages/ripple-ui-core/src/components/search-bar/RplSearchBar.stories.mdx
- packages/ripple-ui-core/src/components/search-bar/RplSearchBar.vue
**Issue**: https://digital-vic.atlassian.net/browse/SD-486
- Implements the new map search bar changes, basically this just adds a prop to RplSearchBar that allows for a suggestion to be required for submission. 
- Adds props to set iconPosition and showSubmitButton
This fixes a couple behavioral issues, for example currently pressing enter or the search button does nothing, unless you have already preformed a search then it will behave the same as the clear button, i.e. hitting enter or clicking search button deletes what you've typed in and performs a new search.
> [SD-486] allow requiring a suggestion in RplSearchBar

- packages/ripple-ui-core/src/components/button/RplButton.css
- packages/ripple-ui-forms/cypress/support/component.ts
- packages/ripple-ui-forms/src/components/RplForm/RplForm.css
- packages/ripple-ui-forms/src/components/RplForm/RplForm.cy.ts
- packages/ripple-ui-forms/src/components/RplForm/RplForm.vue
- packages/ripple-ui-forms/src/components/RplForm/fixtures/sample.ts
- packages/ripple-ui-forms/src/components/RplFormActions/RplFormActions.vue
- packages/ripple-ui-forms/src/components/RplFormDropdown/RplFormDropdown.cy.ts
- packages/ripple-ui-forms/src/components/RplFormInput/RplFormInput.css
- packages/ripple-ui-forms/src/components/RplFormNumber/RplFormNumber.vue
**Issue**: https://digital-vic.atlassian.net/browse/SD-730
- Removed outer fieldset (see ticket), and moved to the FormKit disabled prop.
- The advantage here is that it will work for non-native fields like our dropdown, current that is never disabled when submitting the form 
- Also made some of our disabled states a bit more consistent (see before and after below)
> [SD-730] remove extra fieldset

- examples/nuxt-app/test/features/site/feature-flags.feature
- packages/nuxt-ripple/components/TideContentRating.vue
- packages/ripple-tide-api/types.d.ts
**Issue**: https://digital-vic.atlassian.net/browse/SD-747
- Add feature flag to remove content rating
> [SD-747] feature flag to remove content rating

- examples/nuxt-app/test/features/landingpage/home.feature
- examples/nuxt-app/test/fixtures/landingpage/home.json
- packages/ripple-tide-landing-page/components/global/TideLandingPage/SearchBanner.vue
**Issue**: https://digital-vic.atlassian.net/browse/SD-788
- Removed double encoding
- Added a test for search tests with spaces
- 
-
> [SD-788] Fixed double encoding of search terms in the search banner

- packages/ripple-tide-search/components/global/TideCustomCollection.vue
**Issue**: https://digital-vic.atlassian.net/browse/SD-810
- Add `id` to searchResultsMappingFn to match mapResultsMappingFn. i.e. both searchResultsMappingFn and mapResultsMappingFn now have an `id` set by default, previously one was `id` and the other was `_id`; Note `_id` is still set for backwards compatibility.
> [SD-810] add 'id' to searchResultsMappingFn

- packages/ripple-ui-maps/src/components/layer-list/RplMapLayerList.vue
- packages/ripple-ui-maps/src/components/popup/RplMapPopUp.vue
**Issue**: https://digital-vic.atlassian.net/browse/SD-815
- Adding functionality to the popup for the new RplMapLayerList component caused a regression in the existing sidebar popup behaviour
- To fix this I made the new close on click outside and escape turned off by default and enabled just for the layer list.
- 
-
> [SD-815] Fixed sidebar type popup closing on click

- packages/ripple-ui-forms/src/components/RplFormNumber/RplFormNumber.stories.mdx
**Issue**: https://digital-vic.atlassian.net/browse/SD-729
- Followup on QA - I could reproduce the failing test but the descriptive text was inconsistent, would likely need to test on something other than voiceover
- Added helptext in storybook example as discussed (this meets the AC by announcing the limits on the control)
- This control is only used in the shopping cart, so helptext will need to be added to [@dpc-sdp/ripple-tide-product](https://github.com/dpc-sdp/ripple-tide-product)
- Storybook https://624ac117357335003a84dac3-fxsdvomjgy.chromatic.com/?path=/story/forms-input--number-with-buttons
-
> [SD-729] Add helptext

- packages/ripple-tide-api/src/services/http-client.ts
**Issue**: https://digital-vic.atlassian.net/browse/SD-835
- Use request host instead of config (has api prefix baked in, resulting in double `/api/v1`
- 
- Put a BE in maintenance mode, check DEBUG log
-
> [SD-835] Fix incorrect url sent to logger

- packages/ripple-ui-core/src/composables/useAccessibleContainer.ts
**Issue**: https://digital-vic.atlassian.net/browse/SD-863
- Make sure a11y click only fires once, it was firing twice if the element the user clicked on was a span within the anchor.
*Before*
*After*
> [SD-863] make sure a11y click only fires once

- packages/ripple-ui-core/src/components/data-table/RplDataTable.css
- packages/ripple-ui-core/src/components/data-table/RplDataTable.stories.mdx
- packages/ripple-ui-core/src/components/data-table/RplDataTableRow.vue
- packages/ripple-ui-core/src/components/data-table/fixtures/sample.ts
**Issue**: https://digital-vic.atlassian.net/browse/SD-851 
- Switch to even/odd row classes on data tables, the nth selector wasn't working for this use case
**Before and after**
> [SD-851] switch to even/odd row classes on data tables

- examples/nuxt-app/test/features/publication/publication.feature
- examples/nuxt-app/test/features/site/page-meta.feature
- examples/nuxt-app/test/fixtures/landingpage/image-banner.json
- examples/nuxt-app/test/fixtures/publication/sample-index-large.json
- examples/nuxt-app/test/fixtures/publication/sample-index.json
- examples/nuxt-app/test/fixtures/publication/sample-publication.json
- packages/nuxt-ripple/components/global/RplImg.vue
- packages/ripple-test-utils/step_definitions/common/shared-elements.ts
- packages/ripple-test-utils/step_definitions/content-types/landing-page.ts
- packages/ripple-test-utils/step_definitions/content-types/publication.ts
- packages/ripple-tide-publication/components/TidePublicationPageActions.vue
- packages/ripple-tide-publication/components/TidePublicationSidebar.vue
- packages/ripple-tide-publication/pages/[slug]/print-all.vue
- packages/ripple-tide-publication/server/api/tide/publication-children.ts
- packages/ripple-tide-publication/server/api/tide/publication-index.ts
- packages/ripple-tide-publication/types.ts
**Issues**:
https://digital-vic.atlassian.net/browse/SD-856
https://digital-vic.atlassian.net/browse/SD-829
- Switch to short ids for the print page query so we can print larger pages before 414-ing, currently the limit is about 50 nodes, this update takes it up to about 80+ nodes
- Hide print link for excessively large publications
- Make sure images are loaded on printed publications
Of course the alternative to this PR is to just remove the print feature entirely which is fairly appealing. ⛔🖨️
- Large publication that can't be printed:
- Currently displays print button: https://www.vic.gov.au/literacy-teaching-toolkit-early-childhood
- Updated version hides the print button https://app.pr-1208.vic-gov-au.sdp4.sdp.vic.gov.au/literacy-teaching-toolkit-early-childhood
- Publication with …
> [SD-856][SD-829] publication print page updates

- examples/nuxt-app/mockserver.js
- packages/nuxt-ripple-cli/src/commands/mock/mockserver.ts
- packages/nuxt-ripple/composables/use-tide-page.ts
- packages/nuxt-ripple/composables/use-tide-site.ts
- packages/nuxt-ripple/server/api/tide/page.ts
- packages/nuxt-ripple/server/api/tide/site.ts
- packages/ripple-test-utils/step_definitions/common/mocks.ts
**Issue**: https://digital-vic.atlassian.net/browse/SD-883
- Use runtime site value in page and site endpoints instead site being passed to said endpoints as a query param. This is to avoid people being able able to pull data from other sites.
> [SD-883] use runtime site value in page and site endpoints

- examples/nuxt-app/test/features/landingpage/home.feature
- examples/nuxt-app/test/features/site/feature-flags.feature
- packages/ripple-test-utils/step_definitions/common/navigation.ts
- packages/ripple-tide-landing-page/components/global/TideLandingPage/SearchBanner.vue
- packages/ripple-ui-core/src/components/primary-nav/components/search-form/RplPrimaryNavSearchForm.vue
**Issue**: https://digital-vic.atlassian.net/browse/SD-788
- Update search encoding, this is for the primary nav search bar and the search banner component. The main driver for this is; if you search for example "local & community" currently it will only search for "local ".
> [SD-788] update search encoding

- packages/ripple-test-utils/step_definitions/components/maps.ts
- packages/ripple-tide-search/components/TideSearchPagination.vue
- packages/ripple-tide-search/components/global/TideCustomCollection.vue
- packages/ripple-tide-search/composables/useTideSearch.ts
- packages/ripple-ui-maps/src/components/map/RplMap.vue
- packages/ripple-ui-maps/src/components/popup/RplMapPopUp.css
- packages/ripple-ui-maps/src/components/popup/RplMapPopUp.vue
- packages/ripple-ui-maps/src/components/sidepanel/RplMapSidePanel.css
- packages/ripple-ui-maps/src/components/sidepanel/RplMapSidePanel.vue
- packages/ripple-ui-maps/src/components/sidepanel/RplMapSidePanelItem.vue
**Issue**: https://digital-vic.atlassian.net/browse/SD-707
- Changed the markup of the map sidepanel items to be `ul > li > button` so that we can take advantage of native keyboard navigation (previously a div with `role=button')
- Updated all search components with pagination (search listings, site search, custom collections, map sidepanel) to put focus back at the top of the list when paginating.
- Popups will now close on escape key press
- When a popup is opened, focus will jump to the popup
- When a popup is closed, focus will return to the element that triggered the popup (if still in the DOM)
- Improved the tab order of the map home/zoom/fullscreen controls in relation to the map sidepanel and popups
- 
-
> [SD-707] Maps keyboard nav improvements

- examples/nuxt-app/layers/example-data-driven-component/app.config.ts
- examples/nuxt-app/test/features/landingpage/content-collection.feature
- packages/ripple-tide-api/types.d.ts
- packages/ripple-tide-landing-page/app.config.ts
- packages/ripple-tide-landing-page/components/global/TideLandingPage/ContentCollection.vue
- packages/ripple-tide-landing-page/mapping/components/content-collection/content-collection-mapping.test.ts
- packages/ripple-tide-landing-page/mapping/components/content-collection/content-collection-mapping.ts
- packages/ripple-tide-search/README.md
**Issue**: https://digital-vic.atlassian.net/browse/SD-895
- Removed use of the useSearchUI composable in content collection, in support of removing usage app search.
- Simplified the content collection mapping. A new prop called 'searchQuery' is the body/queryDSL of the call to elasticsearch. There is no longer an intermediate format, this component is simple enough not to need it. All the complexity has been moved to the mapping function.
- Deprecated the `contentCollectionSearchConnector` feature flag as it's no longer relevant.
- Updated tests
- 
-
> [SD-895] Removed app search and useSearchUI from content collection component

- examples/nuxt-app/test/features/maps/maps.feature
- examples/nuxt-app/test/fixtures/maps/request-empty.json
- examples/nuxt-app/test/fixtures/maps/request-with-filter.json
- packages/ripple-test-utils/step_definitions/common/navigation.ts
- packages/ripple-test-utils/step_definitions/components/maps.ts
- packages/ripple-tide-search/composables/useTideSearch.ts
**Issue**: https://digital-vic.atlassian.net/browse/SD-959
- Fixes issue when user re-applies unchanged filters again, then tries to switch tabs the first time
_Note: This will probably need a patch release if `2.34.0` is going out, so can I get a bit of a critical eye 👀 on this, maybe a test too, cheers._ 
- There's 3 PR envirionments to test this to get good maps coverage
- Early learning 
- https://app.pr-20.earlylearning-vic-gov-au.sdp4.sdp.vic.gov.au/find-centre
- Police 
- https://app.pr-500.vicpol-vic-gov-au.sdp4.sdp.vic.gov.au/police-station-location
- Vic.gov.au
- https://app.pr-1233.vic-gov-au.sdp4.sdp.vic.gov.au/completed-connectivity-projects
- https://app.pr-1233.vic-gov-au.sdp4.sdp.vic.gov.au/find-vicfreewifi-hotspots-victoria
- …
> [SD-959] issue re-applying filters and switching tabs the first time

- examples/nuxt-app/test/features/publication/publication.feature
- examples/nuxt-app/test/fixtures/publication/sample-index-no-children.json
- examples/nuxt-app/test/fixtures/publication/sample-publication-no-children.json
- packages/ripple-test-utils/step_definitions/content-types/publication.ts
- packages/ripple-tide-publication/components/TidePublicationSidebar.vue
- packages/ripple-tide-publication/components/global/TidePublication.vue
- packages/ripple-tide-publication/composables/use-tide-publication-menu.ts
- packages/ripple-tide-publication/types.ts
**Issue**: https://digital-vic.atlassian.net/browse/SD-1033
- Only show the publication nav menu when there are publication pages within said publication
> [SD-1033] hide nav when there are no publication pages

- examples/nuxt-app/test/features/maps/suggestions.feature
- packages/ripple-test-utils/step_definitions/common/site/analytics.ts
- packages/ripple-tide-search/components/global/TideCustomCollection.vue
- packages/ripple-tide-search/components/global/TideSearchLocationAutocomplete.vue
**Issue**: https://digital-vic.atlassian.net/browse/SD-1034
- Stop search event fire twice when using the address lockup
> [SD-1034] stop search event firing twice

- examples/nuxt-app/test/features/landingpage/page-components.feature
- examples/nuxt-app/test/features/search-listing/table.feature
- examples/nuxt-app/test/fixtures/landingpage/home.json
- examples/nuxt-app/test/fixtures/search-listing/table/page.json
- examples/nuxt-app/test/fixtures/search-listing/table/response.json
- packages/ripple-test-utils/step_definitions/components/data-table.ts
- packages/ripple-test-utils/step_definitions/content-types/listing.ts
- packages/ripple-tide-landing-page/components/global/TideLandingPage/DataTable.vue
- packages/ripple-ui-core/src/components/data-table/RplDataTable.cy.ts
- packages/ripple-ui-core/src/components/data-table/RplDataTable.stories.ts
- packages/ripple-ui-core/src/components/data-table/RplDataTable.vue
- packages/ripple-ui-core/src/components/data-table/RplDataTableCell.vue
- packages/ripple-ui-core/src/components/data-table/RplDataTableColumnOriented.vue
- packages/ripple-ui-core/src/components/data-table/RplDataTableRow.vue
- packages/ripple-ui-core/src/components/data-table/fixtures/sample.ts
- packages/ripple-ui-core/src/components/data-table/helpers.ts
- packages/ripple-ui-core/src/components/data-table/types.ts
**Issue**: https://digital-vic.atlassian.net/browse/SD-983
- Adds support for table orientation, not 100% sold on this approach but it keeps the orientation support issolated which is good considering it's narrow usecase.
NOTE: I need to update the PR base after the `2.36.0` release
- Storybook
- https://624ac117357335003a84dac3-pulfovohup.chromatic.com/?path=/story/core-containers-data-table--column-oriented-no-headings&globals=viewport.value:mobile1
- https://624ac117357335003a84dac3-pulfovohup.chromatic.com/?path=/story/core-containers-data-table--column-oriented-horizontal-headings&globals=viewport.value:mobile1
- https://624ac117357335003a84dac3-pulfovohup.chromatic.com/?path=/story/core-containers-data-table--column-oriented-vertical-headings&globals=viewport.value:mobile1
- …
> [SD-983] add support for table orientation

- examples/nuxt-app/test/features/landingpage/custom-collection.feature
- examples/nuxt-app/test/features/search-listing/table.feature
- examples/nuxt-app/test/fixtures/landingpage/custom-collection.json
- packages/nuxt-ripple-analytics/lib/index.ts
- packages/ripple-tide-search/components/TideSearchListingPage.vue
- packages/ripple-tide-search/components/global/TideCustomCollection.vue
- packages/ripple-ui-core/src/components/data-table/RplDataTableRow.vue
**Issue**: https://digital-vic.atlassian.net/browse/SD-1058
- Provide 'contextName' for data table toggle event, these means the data table toggle event will get `name` set to the relevant context i.e. the search listing title or custom collection title.
- Also noticed the label value can be an array so added a check for that.
> [SD-1058] Provide 'contextName' for data table toggle event

- packages/ripple-tide-search/app.config.ts
- packages/ripple-tide-search/components/TideSearchPage.vue
- packages/ripple-tide-search/composables/useSearchUI.ts
- packages/ripple-tide-search/pages/search.vue
- packages/ripple-tide-search/types.ts
- tsconfig.json
**Issue**: https://digital-vic.atlassian.net/browse/SD-981
- Added extra prop `maxValue` to change number of topics shown, increased in the search page template to 30
- Some lint / ts / imports tidy up while I was in there
- nuxt-app `/search`
-
> [SD-981] Add config for number of topics in user filter

- packages/ripple-ui-core/src/components/primary-nav/RplPrimaryNav.cy.ts
- packages/ripple-ui-core/src/components/primary-nav/components/mega-menu/RplPrimaryNavMegaMenu.vue
- packages/ripple-ui-core/src/components/primary-nav/components/nav-bar/RplPrimaryNavBar.vue
- packages/ripple-ui-core/src/components/primary-nav/components/search-form/RplPrimaryNavSearchForm.vue
**Issue**: https://digital-vic.atlassian.net/browse/SD-1083
- Add aria attributes to primary nav, specifically `aria-haspopup`, `aria-controls`, `aria-expanded` and `aria-label`
- This also adds descriptive labels to the disparate 'submenus'; because there's no heirachy to our menus this tries to somewhat mimic what you would get if there was. For example, a typical nested list will tell the screen reader what level within the ul your currently at.
> [SD-1083] add aria attributes to primary nav

- examples/nuxt-app/app.config.ts
- examples/nuxt-app/test/features/search-listing/search-query.feature
- examples/nuxt-app/test/fixtures/search-listing/search-query/page-curations-custom.json
- examples/nuxt-app/test/fixtures/search-listing/search-query/page-curations.json
- examples/nuxt-app/test/fixtures/search-listing/search-query/request-curation-custom.json
- examples/nuxt-app/test/fixtures/search-listing/search-query/request-curation-edupay.json
- examples/nuxt-app/test/fixtures/search-listing/search-query/request-curation-key.json
- examples/nuxt-app/test/fixtures/search-listing/search-query/request-curation-police.json
- examples/nuxt-app/test/fixtures/search-listing/search-query/response.json
- packages/ripple-test-utils/step_definitions/content-types/listing.ts
- packages/ripple-tide-search/components/TideSearchListingPage.vue
- packages/ripple-tide-search/components/global/TideCustomCollection.vue
- packages/ripple-tide-search/components/global/TideTideSearchListing.vue
- packages/ripple-tide-search/composables/useTideSearch.ts
- packages/ripple-tide-search/types.ts
**Issue**: https://digital-vic.atlassian.net/browse/SD-1134
- Adds support for search curations, this allows people to promote specific results when the user enters a specific term. For example; you might want to ensure that when people search for "how do i get paid?" that the "edupay" page is the first result. (The CMS mapping will come later).
- Search listing
- FE: https://app.pr-227.reference-sdp-vic-gov-au.sdp4.sdp.vic.gov.au/listing
- Config: https://github.com/dpc-sdp/reference-sdp-vic-gov-au/blob/feature/search-curations/pages/listing.vue#L138
- Custom collection
- BE: https://app.pr-227.reference-sdp-vic-gov-au.sdp4.sdp.vic.gov.au/collection
- Config: https://github.com/dpc-sdp/reference-sdp-vic-gov-au/blob/feature/search-curations/pages/collection.vue#L67
> [SD-1134] search curations

- packages/nuxt-ripple/package.json
- pnpm-lock.yaml
- The site builds are failing in lagoon right now, hoping this fixes that (move sanitize-html to regular dependencies)
> fix: move sanitize-html to regular dependencies

- packages/ripple-tide-landing-page/components/global/TideLandingPage/ContentCollection.vue
**Issue**: https://digital-vic.atlassian.net/browse/SD-1215
- The content collection component is rendering "Sorry! Something went wrong. Please try again later." server side, which is causing a hydration mismatch issue client side, Vue seems to be getting a little confused when dealing with this mismatch issue which results in the rpl-content class being applied to the results container which is then causing the layout issues. We need a fix for this in UAT envs today as it needs to be rolled out in tomorrows release (we'll need a `2.38.2` release). The simple solution for now is to just restore the previous behavior, i.e. previously content collection results were only fetched and displayed client side.
- Current develop: https://develop.vic-gov-au.sdp.delivery/testing-page-analytics#cont …
> [SD-1215] revert custom collection behaviour

- packages/ripple-tide-api/src/services/tide-api-base.ts
**Issue**: https://digital-vic.atlassian.net/browse/SD-1218
- Added separate 404 under WrappedAxiosError to handle disabled API endpoint
- 
- 
-
> [SD-1218] Improve api error handling
